### ISSUE TITLE
Optimised mode won't turn on dGPU if Power-Brick & USB-C+PD is plugged in

### ISSUE THREAD

**Issue by zakimohzani** [seerge/g-helper#1008]
Device: Zephyrus G14 2022, GA402RJ

So basically I have the following:
1. The G-helper option "Keep GPU disabled on USB-C charger in Optimised mode" = ON
2. 230W power brick plugged into my charging port
3. Monitor connected via USB-C. Also, this monitor can do 65W USB-C Power Delivery

So basically there's 2 simultaneous chargers running but G-helper doesn't seem to recognise that the 230W charger is plugged in and that 65W USB PD isn't neccessary. Therefore the "Optimised mode" causes the dGPU to be turned OFF. 

Is this a bug?

**Comment by seerge** [comment]
@zakimohzani check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/12266924/GHelper.zip)

**Comment by marcelomijas** [comment]
@seerge please, if you can make a note in the release about the dangers of trying this on G14 2020 (and 2021 I think) models that break when you plug both, barrel and USB-C PD simultaneously...

**Comment by seerge** [comment]
@marcelomijas what kind of dangers?

**Comment by marcelomijas** [comment]
@seerge here's a detailed thread: https://www.reddit.com/r/ZephyrusG14/comments/inrdx3/usbc_power_delivery_power_adapter_issue/

It's an Asus hardware design flaw on the G14 2020 model. If you have plugged both, USB-C PD and the barrel plug, you have a chance to kill the laptop (it's sporadic, it's doesn't happen with all USB-C PD chargers, but the possibility is there and it's not low...)

**Comment by seerge** [comment]
@marcelomijas ah, i see :) so you just want app to show some kind of a warning (as it can't do anything else anyway)
I'm not sure how to detect that case properly ...

**Comment by marcelomijas** [comment]
@seerge I wasn't specifically referring to that (but it's a great idea...) I was proposing that you put a warning in the release v0.106 changelog in GitHub telling something like "G14 2020 users, DO NOT try this feature or it will break the laptop because Asus flaw...".

I think the average Joe with the 2020 model could see the v0.106 changelog and try the feature with a bad ending (enven optimized mode is not supported)

**Comment by seerge** [comment]
@marcelomijas oke :) but this feature is not about allowing that method at all (it was always possible to do it before) ;) it’s just about detecting barrel plug / usb c within app itself:)

**Comment by zakimohzani** [comment]
> @zakimohzani check this build, should be ok (test on my G14 2022 and G16 Strix 2023)
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/12266924/GHelper.zip)

Yes, that fixed it. Thank you, sir.

**Comment by joe-700** [comment]
Just for the record; IMHO its not a good idea to use the PD charging at all during laptop use. From my understanding the PD charging does not support power passthrough on any model year. The G14 will run at high power draws when plugged into PD power, above the 100W limit, this results in frequent charge/discharge cycles. You are liable to degrade the battery health faster if you do this. I have also not seen any definitive proof that the duel mode charging issues have been fixed on recent model years. I think the community is accepting that the issue has been fixed due to lack of recent reports of MB failures.

Maybe someone can clarify my statement, but it may be prudent to only use the PD charging when the laptop is turned off or in hibernation. You can still use USB-C for docking station, just use the right hand port to avoid PD charging and plug in the barrel connector.

I will reach out to Asus and see if they can clarify this issue for us.

I don't think G-Helper requires a feature to protect against this, but it is worth mentioning it here for anyone that reads through the version history and chat.
