### ISSUE TITLE
Please add a limit to the 'CPU Power Consumption Slider' for FLOW X13.

### ISSUE THREAD

**Issue by woki-wchange** [seerge/g-helper#1029]
**Is your feature request related to a problem? Please describe.**
When I use G-helper to control the ROG FlowX13, I found that I can unlock the CPU power consumption to over 75W using the CPU power control slider. This is very dangerous for the FlowX13 because the maximum sustained power consumption of the CPU when it was released is only 55W. When G-helper is used on the FLOWX13, the power control menu can be adjusted up to 150W (I haven't tried to see if setting it to 150W actually allows the CPU TDP to reach 150W, but when I set it to a maximum of 75W, the CPU can indeed run at 75W for an extended period).
I'm concerned that if I accidentally set the power limit too high one day without noticing, my computer might overheat and get damaged. Although I know there's a CPU temperature limit, I found that when I set it to 75W, the CPU's instantaneous temperature still reached 100°C. This is because the power consumption far exceeds the machine's cooling capacity, causing the temperature to rise too quickly for the system to respond in time.

**Describe the solution you'd like**
When used on the FLOWX13, set an upper limit for the G-helper CPU power consumption slider, such as 65W, instead of the current unsafe 150W.

**Describe alternatives you've considered**
Can you add some kind of protection against accidental touches, instead of the current simple checkbox？

**Additional context**
I'm truly grateful to have someone like you who wrote such a tool! It has really helped me a lot.
![image](https://github.com/seerge/g-helper/assets/39522148/e07ee7f6-ef2a-4d02-9829-2c7a7443d746)

**Comment by woki-wchange** [comment]
![Snipaste_2023-08-08_20-19-00](https://github.com/seerge/g-helper/assets/39522148/dca1ef46-ed0c-442a-a0cc-b1b5d887aa8d)
I just tested it under 75W, and it indeed ran at 75W. I dare not set a higher power consumption. This is just a 13-inch laptop, and its design power consumption is only up to 55W. I'm concerned that even if there's a 90W limit in the BIOS as you mentioned, 90W is still unsafe for the FLOWX13. Currently, at 75W, the cooling system of this computer is already at its limit.

**Comment by woki-wchange** [comment]
Due to the laptop's cooling limitations, I can't test its maximum power consumption for you. However, what I do know is that its out-of-the-box maximum is 60W FPPT.

**Comment by seerge** [comment]
Your CPU has a throttle temp (usually it's 96C), as soon as it hits it - it immediately and dramatically drops power (in order to not to go higher). You can monitor that as a chart by double-clicking on needed value.

On your screenshot it's consuming 72W. But most probably there is still some hard limit :) (like 80w or 90w) and you won't see higher wattage on HWinfo charts either cause of this cap or cause of throttling :)

**Comment by woki-wchange** [comment]
Thank you for your response. The reason I only reached 72W is because the CPU temperature hit its limit. What I'm more concerned about is that, under normal circumstances, I turn off the computer fan below 60°C. If I set the power limit higher at that time, for example to 90W, the instantaneous 90W might cause the temperature to rise so quickly that the fan and temperature throttling mechanisms can't react in time, potentially damaging the computer. Of course, this is just my concern, and it might not happen. I just think, perhaps there could be a limit in Ghelper for situations that would exceed the manufacturer's power limits.

**Comment by seerge** [comment]
I can hardcode limit for specific model, but i need to know what real limit is :)

**Comment by woki-wchange** [comment]
Thank you for your patience. Based on the current situation, I believe it might be 90w. However, due to the cooling conditions, I can't test the actual limit. But can you hide the options to unlock more than 65w in the UI?

**Comment by woki-wchange** [comment]
SPL+SPPT : 55W
FPPT : 60W

**Comment by Wolper321** [comment]
x13 6900HS Ghelper actually unlocking the CPU and I can confirm it. Turbo sets the limit at around 54w for CPU and if you customize it the limit seems to be as high as you want lol. My system can only keep up with 65w at max. 72w is actually impressive.
![image](https://github.com/seerge/g-helper/assets/12784148/2b3108ee-e15a-4a2c-b816-3c85896e9a03)

**Comment by woki-wchange** [comment]
"I'm sorry, I made a mistake in my previous answer. I remembered it wrong. The correct power limits are: sppt 54w, Fppt 65w. It's the same as the screenshot above. In fact, if I lift the body of my laptop to allow better airflow, my CPU can sustain 75w. However, at this time, the CPU temperature is 95 degrees Celsius. Regardless, I think it's better to set a limit on this power unlocking feature."

**Comment by woki-wchange** [comment]
Alright, thank you very much for the work you've done. I will try it out and give you feedback later.

**Comment by IceStormNG** [comment]
Just some info. The instantaneous thermals are not a problem. The chips has more or less 0 thermal mass. Yes, it does reach 100°C shortly, but that is not a problem, it will throttle down asap to maintain a safe operating temperature, which is 95°C for that chip.
On intel it is similar, but 5°C higher for both (ASUS reduced that to 95°C though). The reason is that the temperature spikes faster than the thermal management can react due to the chip being so small and so little mass that it heats up in a few milliseconds. On some machines, especially from ASUS, the liquid metal is often .... questionable (both my M16s had a dry spot in the middle, which was very noticeable as 4 cores were hitting 99°C in no time, while the other cores were slower and never reached that). 
<img width="342" alt="image" src="https://github.com/seerge/g-helper/assets/12786283/b5542101-9cb8-4f8c-9524-3fe7ebc9618f">


This causes bad thermal connection and will cause thermal overshoot as the heatsink cannot absorb the heat fast enough.

Either way, setting a "safe limit" is not wrong, but if the CPU ever reaches critical temperatures, it will shut off the VRMs immediately, which results in your machine to shutoff. The throttle temps are set with overshoot in mind, as this is how thermals work, so there is some safe headroom that for such scenarios. AMD and Intel do not build CPUs for the first time.

**Comment by woki-wchange** [comment]
> 

It works, thank you for your help!
