### ISSUE TITLE
UX suggestion

### ISSUE THREAD

**Issue by fennectech** [seerge/g-helper#1037]
you have made a poor choice of bar for your battery meter.   The dot suggests that it is something that can be interacted with (presumably to set the maximum charge)   i recommend using a standard progress bar instead of a slider.

**Comment by seerge** [comment]
?

**Comment by fennectech** [comment]
oh  it is interactive?   i havent been able to grab it on the ally

**Comment by seerge** [comment]
It is, but unfortunately due to a very slow hardware call to set charge limit / technical reasons it can be slow to respond

**Comment by fennectech** [comment]
is there any way you can make the dog bigger / easier to grab on tiny touch screens like the rog ally?

**Comment by seerge** [comment]
It’s not only
this slider :) honestly whole app (due to a very light but native windows ui) is not very touch friendly as it has never been designed for that in a first place.

I might optimize ui for touch/ally eventually, but not now cause it’s very resource intensive and ally is only 1-2% of app users

**Comment by fennectech** [comment]
It’s becoming very popular to use on the ROG Ally so touch optimization (or gamepad support) would be really nice
