### ISSUE TITLE
Windows Power Mode

### ISSUE THREAD

**Issue by BBeBeeBeef** [seerge/g-helper#1091]
Just updated to version 0.110.0 and the windows power mode dropdown menu in fans + power automatically keeps selecting 'best power efficiency' for turbo mode not 'best performance'. I wondered why my computer felt sluggish!

**Comment by seerge** [comment]
@BBeBeeBeef hello, post a log here. I don’t have telepathic skills

**Comment by BBeBeeBeef** [comment]
[log.txt](https://github.com/seerge/g-helper/files/12342674/log.txt)

You're welcome.

**Comment by seerge** [comment]
@BBeBeeBeef i see, it may not save edits sometimes (you have changed it initially)

Try this build 

[GHelper.zip](https://github.com/seerge/g-helper/files/12342739/GHelper.zip)

**Comment by BBeBeeBeef** [comment]
Also, unplugging and plugging in the power cable changes the power mode to 'balanced' too.

Very annoying lol

**Comment by seerge** [comment]
@BBeBeeBeef changes where ? in windows or in app? app remembers separate preset for plugged and unplugged :) (it has always been like that) and would set last mode used on battery.

Does the build that I have linked save your "windows power mode" correctly now ?

**Comment by BBeBeeBeef** [comment]
0.112 appears to have fixed the problems, both are no longer happening now.

**Comment by seerge** [comment]
Great. Closing as completed then.

**Comment by TheBestPessimist** [comment]
For me this is still not fixed in 0.112. All windows power modes are shown as balanced in Ghelper, and when i change them, they dont stick.

repro:
- start with ghelper balanced profile
- change to ghelper turbo
- current win profile is balanced. => change to highest performance
- change ghelper to balanced
- changed ghelper to turbo

at this point, the windows profile is still balanced, not highest performance.

Logs:
[log.txt](https://github.com/seerge/g-helper/files/12356187/log.txt)

**Comment by seerge** [comment]
@TheBestPessimist can you change then in windows settings or are they locked in powerpoan?
