### ISSUE TITLE
GPU mode not working after bios update

### ISSUE THREAD

**Issue by JgS7** [seerge/g-helper#1107]
Hi, 
I have a Zephyrus G15 2022 (GA503RM) and after the new bios update (315) looks like gpu mode is broken.

I have my external monitor connected by USB-C and previously, if I switched to eco mode, if the display was connected to the "dgpu usb c" it should go black. Now when I switch to eco, the screen goes black and seconds later, the image comes again. 

The windows screen manager says that the source of image is coming from the dgpu.

![imagen](https://github.com/seerge/g-helper/assets/116883652/1e8a22e2-9e2a-47e3-8172-a8413777929b)

Thank you so much.

**Comment by seerge** [comment]
@JgS7 hello.

As you have said - if it's after BIOS 315 - i guess problem is there? :) 

Since UI shows Eco, it means that BIOS reports GPU as disabled. Mb that's a new "feature" that keeps port working?

Try to reboot or do a hardware reset https://github.com/seerge/g-helper#how-do-i-do-a-hardware-reset-on-a-laptop to make sure nothing is stuck.

Anyway, I can't neither modify / nor fix your bios, and you can always just roll back if you are not happy with that :)
