### ISSUE TITLE
Power Mode and Fan Speed inconsistencies.

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#1127]
First things first, this is what I noticed, however I don't believe it's G-Helpers fault. I made this 'issue' to get more information on what could possibly going on here.

Here's a video displaying what's up:
<video src='https://user-images.githubusercontent.com/2539661/261703723-6598f784-921e-4486-8b08-52edd3bf93a7.mp4' width='480' />

Long story short, while switching power modes, I noticed the Speed Shift EPP values doesn't really make sense.
For example: 
> Best Power Efficiency - 127 Speed Shift EPP
> Balanced - 0 Speed Shift EPP
> Best Performance - 63 Speed Shift EPP

Why would 'Balanced', instead of 'Best Performance' power mode set Speed Shift EPP to 0 ? 

...

Regarding fan speeds - are the fan profiles really the default ones? Why would my fans work harder when I have the checkbox unmarked compared to when it's marked, indicating that I use the 'custom', in this case - default, fan curve?

**Comment by IceStormNG** [comment]
> Why would 'Balanced', instead of 'Best Performance' power mode set Speed Shift EPP to 0 ?

In balanced mode, the value from the power plan is used. In the other two modes not. And ASUS power plans set it to 0 because... they have to win some benchmarks and they like if the laptops get glowing red... /s

Windows Default for balanced plan is 115 or so (45%) on AC and 153 (60%) on battery by default.
