### ISSUE TITLE
GPU Power Draw - GA401QM 

### ISSUE THREAD

**Issue by kountary** [seerge/g-helper#1154]
When running benchmarks/stress tests for the gpu, the max tdp it hits is ~60w (via gpu-z and hwinfo). I have disabled cpu boost yet it doesn't inch past this amount. Are there any GPU/CPU settings (such as SPL+SPPT States) that I need to adjust in order to prioritize the gpu? 

Thank you and sorry if I have omitted any necessary information. Please let me know what to include.

**Comment by seerge** [comment]
@kountary hello, most probably you have either Whisper mode enabled or something else limiting it inside NVidia settings

https://github.com/seerge/g-helper#i-have-uninstalled-armoury-and-my-gpu-performance-is-lower-than-it-was

G-Helper doesn't limit GPU power anyway (more over it can't as it's not possible to do that due to limitations on driver level)
