### ISSUE TITLE
Why it needs a reboot for Ultimate Mode when Standard+Nvidia GPU only in DDS doesn't?

### ISSUE THREAD

**Issue by Henning742** [seerge/g-helper#1186]
Sorry if this is not really related to G-helper. But I think this is the best place for my question, and the discussion, though not very likely, may help to improve G-helper.

From my understanding, 
1) Ultimate Mode and 
2) Standard Mode + Nvidia GPU only in DDS 

are basically the same: dGPU is directly connected to the display. But (1) requires a reboot and (2) doesn't. So I guess it would be better to make switching to (2) easier and decrease the visibility of mode (1).

Any help is appreciated.

**Comment by seerge** [comment]
@Henning742 hello,

Because this is how it's done on hardware level, Ultimate mode requires restart also in Armoury. As this is a hardware MUX switch. 

You can keep using Standard and just set display mode to Nvidia GPU only if you want in Nvidia Control panel. But from my observations you still lose a little bit of power to optimus.
