### ISSUE TITLE
OSD for keyboard backlight mode

### ISSUE THREAD

**Issue by flankedgonerogue** [seerge/g-helper#1191]
All in the title.

**Comment by seerge** [comment]
@flankedgonerogue 
[GHelper.zip](https://github.com/seerge/g-helper/files/12446789/GHelper.zip)

**Comment by squee666** [comment]
anyway to turn osd off for this, i use the asus osd with armoury crate disabled for certain 2nd display processes for my zeph duo

**Comment by seerge** [comment]
@squee666 you can disable OSD completely via config https://github.com/seerge/g-helper#disable-osd

But I didn't get your comment. Do you get a second OSD notification for backlight modes from asus ?

**Comment by squee666** [comment]
> @squee666 you can disable OSD completely via config https://github.com/seerge/g-helper#disable-osd
> 
> But I didn't get your comment. Do you get a second OSD notification for backlight modes from asus ?

thanks i missed this about osd disabling

yeah i have armoury crate disabled only by renaming the exe.
so I have Asus giving me an OSD popup on backlight changes.

heres what it looks like https://i.imgur.com/YiXhrUu.png

I need to keep it on because Asus processes control the secondary display on the zephyrus duo


it lets me turn off display entirely , turn off 2nd display backlight only or turn on display
https://i.imgur.com/YdPIXmq.png
