### ISSUE TITLE
[Feature Request] ROG Falchion Software Support

### ISSUE THREAD

**Issue by IncognitoFawkes** [seerge/g-helper#1203]
Currently, there aren't any software other than Armoury Crate to set the Macros for ROG Falchion.

Is there any way by which we can have G Helper work with ROG Falchion?

**Comment by seerge** [comment]
@IncognitoFawkes Hello, there is a separate topic where you can [request peripherals support ](https://github.com/seerge/g-helper/discussions)

So far only mice are supported. What kind of settings does keyboard have that you need to change constantly ?

**Comment by IncognitoFawkes** [comment]
I don't care about customizing the RGB. I'd just like to get the firmware updates for my keyboard, set the Macros, and set what the side touch panel does.

**Comment by seerge** [comment]
@IncognitoFawkes i really doubt that firmware updates will be done by the app anyway, as this is proprietary asus stuff, and don't want to risk bricking someone's device. As far as I understand they are quite rare anyway. 

Handling keyboard hotkeys can be tricky as well, as I don't have it and have no idea how exactly it communicates with computer :)

**Comment by IceStormNG** [comment]
@seerge  right. I already wrote that to a request in the discussion. I won't implement firmware updates, even though I could do it. Simply because I don't want to read all the reports here "GHelper bricked my mouse/keyboard/whatever". Firmware updates are quite rare and you could use a spare computer to update, or just don't update if you have no issues.

As for keyboards in general: I have no ASUS keyboard and therefore no understanding of the communication via AC. Someone would have to analyze and reverse engineer the configuration protocol first.

**Comment by seerge** [comment]
@IceStormNG ye, i agree :) So I assume that this falls into not planned then (for now), unless someone wants to buy a keyboard ...

**Comment by ardissaps** [comment]
@seerge I would want to added support for it, yes I use Falchion NX keyboard. I support the laptop with arms so I play with keyboard.

**Comment by seerge** [comment]
@IncognitoFawkes hello, 

If you are interested you can test external keyboards support in a new build https://github.com/seerge/g-helper/discussions/5710 

Thanks!

**Comment by seerge** [comment]
Live in the latest release https://github.com/seerge/g-helper/releases

**Comment by ardissaps** [comment]
Thanks!
