### ISSUE TITLE
Keep Settings on Boot

### ISSUE THREAD

**Issue by jmdvella** [seerge/g-helper#1430]
Is there an option somewhere to keep settings after boot? 

For example my CPU Boost is set to Disabled, however goes back to Aggressive after reboot. Same with the GPU Clock/Memory Offsets. I set them to 0 and after a reboot they go back to Clock: 100hz Memory: 150hz

Edit:
I was able to resolve this by removing armory crate. 

1. Two last questions. Is there a way to stop the battery from continuing to charge after the laptop is switched off? This works in Armory Crate so it always stays at 60% regardless if its off, turning on etc. since I have it plugged into the wall most of the time?

2. Cant find in the documentation some specifics on the CPU Boost, what does Aggressive, Effecient Agressive, Effecient Enabled, Aggressive at Guaranteed mean? Thanks for the great app btw!

**Comment by Kikimahe** [comment]
Hi 

1) Normally your battery does not charge when the PC is turned off or when it is asleep.
But it charges some 0.x% after shutdown/startup or restarting the computer until windows and Ghelper are started to block battery charging.
Observe your charging LED indicator :)

2) Look [#492](https://github.com/seerge/g-helper/discussions/492)

**Comment by jmdvella** [comment]
Great thanks for that @Kikimahe , Yes my LED indicator says its charging while asleep or off til it get to 100%. Usually with Armoury Crate it stops at 60% or whatever is set in Armoury.

2. Thanks a bunch! Still unsure what 'Aggressive Guaranteed' means though, do you know? I would have a hunch and say it tries to keep boost at the expense of heat/power consumption.

**Comment by seerge** [comment]
@Kikimahe hello, 

1. Your CPU boost is just a property in windows power plan. It should not reset on reboot. If it does - check if other apps are changing that.
2. Your GPU clock / memory offsets are being re-applied  by G-Helper automatically on start every time (since you have ignored issue template template and didn't provide any logs i can't help further). Make sure that you don't have any other apps (including AC service) resetting your clocks afterwards.
3. If battery start charging when laptop is off - this is how your hardware works. AC can't set charge limits at all, it's done by MyASUS.
4. [CPU boost differences](https://github.com/seerge/g-helper/discussions/492)

**Comment by jmdvella** [comment]
With MyAsus its not able to run when the services are turned off in G-Helper correct? So how can I use the charge limit in Asus while running G-Helper? 
![Screenshot 2023-10-06 170222](https://github.com/seerge/g-helper/assets/41462638/174fc69d-2afe-4d86-8ed7-475a734d6e31)

**Comment by jmdvella** [comment]
Ah yes thank you, you are correct @seerge ! 

Excellent job on this software, thank you so much!
