### ISSUE TITLE
Disable Armoury Crate "Resource Monitor" feature

### ISSUE THREAD

**Issue by ThatOtherAndrew** [seerge/g-helper#1496]
**Is your feature request related to a problem? Please describe.**
Armoury Crate has built-in "Resource Monitor V2" functionality, which is pretty awful - it's redundant as it doesn't display anything that the NVIDIA or Xbox Game Bar overlays don't display already, it appears to be always running in the background, and worst of all it registers and captures 5 keyboard shortcuts which can't be unbound. After a quick search online, I'm not the [only](https://www.reddit.com/r/techsupport/comments/1759htt/fps_overlay_on_ctrlalts/) / [person](https://www.reddit.com/r/ASUSROG/comments/176c6sf/armoury_crate_resource_monitor/) / [having](https://www.reddit.com/r/ZephyrusG14/comments/1761ypm/is_there_any_way_to_disable_certain_global/) / [this](https://www.reddit.com/r/ASUSROG/comments/176ebjs/armoury_crate_overiding_system_shortcuts/) / [issue](https://www.reddit.com/r/ROGAlly/comments/164f15x/disable_armoury_crate_keyboards_shortcut/).

**Describe the solution you'd like**
I'm not sure what ASUS driver, process or service intercepts these keybinds, but it'd be very helpful if the G-Helper in-app option to stop ASUS services could find and kill this as well.
<img width="368" alt="image" src="https://github.com/seerge/g-helper/assets/26030336/193ef8d3-cf1a-492a-a0c6-0714b448f972">

**Describe alternatives you've considered**
One alternative is to rebind the shortcuts to other keys which aren't used as often, but this is still less than ideal.

**Additional context**
N/A

**Comment by seerge** [comment]
@ThatOtherAndrew hello 

G-Helper has never been designed to "fight" with AC :)  Its service stopper / starter doesn't touch AC services neither, it stops leftovers (ones coming with asus control interface)

If you don't want to use AC or it's stuff - you should better [uninstall it temporarily or permanently ](https://github.com/seerge/g-helper#recommendations-optional)

**Comment by ThatOtherAndrew** [comment]
Hello, sorry for misunderstanding the project. I'm coming from Lenovo with the Lenovo Legion Toolkit, where the utility can halt all Lenovo Vantage processes to take precedence, and falsely assumed that G-Helper intended to do the same.

I would uninstall Armoury Crate, but there are a couple of features it has which I haven't spotted any alternative implementations for - for example for configuring AniMe Matrix beyond a simple on/off toggle while the screen is on. Are you aware of any standalone implementations for that by any chance?

**Comment by seerge** [comment]
@ThatOtherAndrew you can set and position any custom picture or even gif on anime matrix, also set up clock or audio visualizer.

This far from "simple on/off toggle"

**Comment by ThatOtherAndrew** [comment]
Sorry, I should've been more specific - I was talking about changing the animation during boot, shutdown, sleep, etc. As for the picture/gif button, that just shows a black screen for me - I haven't been able to get that working, and I'm not sure if that's a result of a bug or my own incompetence with using the tool 😅

Regardless, that's for another issue / discussion, if at all. I'll give it my best shot, do a bit of digging online, and see what I can make of it.

Thanks for a fantastic tool!

**Comment by seerge** [comment]
Boot / shutdown animations are hardcoded and have only 2 settings. Sleep is always "starfal" animation and is also hardcoded in matrix.

For picture - it's a preview /editor. You just select custom picture by clicking picture / gif button and then position / resize it on preview as you want

![Screenshot 2023-10-20 212208](https://github.com/seerge/g-helper/assets/5920850/a8d3eeba-e8e4-4799-bff0-c84a0e4fa24e)

**Comment by Hexagonl** [comment]
> **Describe alternatives you've considered** One alternative is to rebind the shortcuts to other keys which aren't used as often, but this is still less than ideal.

I don't use G-Helper but do use Armoury Crate, and I found this GitHub issue while searching online for other users with this problem.

I found a reasonable alternative solution to this problem, and if you don't mind me being slightly off-topic, I'd like to redirect you to a post I made on reddit that explains how to do the solution: https://www.reddit.com/r/techsupport/comments/1759htt/comment/k5qb2nn/

Hopefully this is helpful to @ThatOtherAndrew

**Comment by ThatOtherAndrew** [comment]
@seerge I appear to not have that button - that'd explain my confusion! Is this a bug?

<img width="332" alt="image" src="https://github.com/seerge/g-helper/assets/26030336/1b365f13-dc15-48e6-9190-bb7cb3fdcea4">

**Comment by ThatOtherAndrew** [comment]
@Hexagonl Nope, no luck unfortunately.

<img width="194" alt="image" src="https://github.com/seerge/g-helper/assets/26030336/8f281b5a-b02d-4bbf-844a-5bd97ebc4066">

**Comment by Hexagonl** [comment]
@ThatOtherAndrew yeah I'll just post it here, I'll try to figure out reddit eventually

---

I've found probably the best solution so far, which doesn't sacrifice any keyboard shortcuts for most, if not all users.

The configuration file that stores the settings (including the keyboard shortcuts) for the Resource Monitor is located at `%LocalAppData%\ASUS\Armoury Crate Service\MonitorPlugin` (to get here, press `WINKEY + R` to open the run menu, paste this location, and press enter)

Open the text file called "MonitorSettings.ini" in Notepad (right click and select "Open with..." or "Open with >" and go through the menu until you open the file with Notepad or your text editor of choice)

You'll either be greeted with a blank file or some text depending on if you played around with the settings already. All you need to do now is paste the following into the file (if you already have something that looks similar in the file, make sure you replace it):

    [Hotkey]
    OSDSwitcher=458892
    OSDMoving=458893
    RecordSwitcher=458894
    LevelSwitcher=458895
    TimeSwitcher=458909

Once you've done that, just save the file, close Armoury Crate if it's open, and reopen it. If you head to `Armoury Crate -> System -> Resource Monitor -> Real-time Monitor Settings` (if the button is grayed out, you have to enable the option right above it), you'll see all the keybinds say "Ctrl + Alt + Shift" (if not, please reply what it says for you so we can help you further)

All you have to do now is disable the Resource Monitor, which you can do by heading to `Armoury Crate -> System -> Resource Monitor -> Real-time Monitor Settings` and disabling the option on the right that says "Real-time Monitor"!

Why this works: The values I gave correspond to the keybind for Ctrl + Alt + Shift plus the keys that correspond to the ASCII codes of 140, 141, 142, 143, and 157. I found that Armoury Crate doesn't recognize a corresponding key to these values, so it essentially disables that keybind as it doesn't know what to check for. If you find that Armoury Crate DOES correspond that code with a key, try replacing the value with 458752 plus a number from 1-256, which corresponds to an ASCII code (you can find these online to make sure you're not accidentally replacing anything you need)

Why these values: You have to use these arbitrary values instead of values like 0, -1, and 2147483647 because the latter makes Armoury Crate flat-out ignore the custom keybinds and use the annoying defaults that we're trying to avoid in the first place.

I hope this is helpful to everybody who found this Reddit post! Hopefully ASUS updates Armoury Crate to fix this unnecessary feature.

---

Admittedly, this solution is similar to your alternative solution, but this instead sets the keybind to something invalid and doesn't steal any keybinds from you

**Comment by seerge** [comment]
@ThatOtherAndrew try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13058317/GHelper.zip)

**Comment by ThatOtherAndrew** [comment]
That's fixed it, thank you! May I ask what you changed in that build?

**Comment by ThatOtherAndrew** [comment]
And @Hexagonl thank you for your detailed answer as well, that's perfect! I actually tried to do exactly what you did, and found the same file, but it didn't contain any hotkey entries - it seems that they're only autogenerated after you change/customise them. Overall some very questionable design decisions on Asus' part, good job on your little bit of reverse engineering :>

**Comment by seerge** [comment]
@ThatOtherAndrew i changed panel layout a bit, apparently (by some unknown reason) it was resizing panel with buttons incorrectly in your specific case.

**Comment by ThatOtherAndrew** [comment]
I see, thanks! It's time to finally toss Armoury Crate in the bin :D

**Comment by sebastienbo** [comment]
How can i disablz this shitty on screen resource manager?
I ve tried everything, even clsoe every possible armory crate process, but that stupid anoying resource manager continues to stay on my screen and it stays active even when i dsabled it in the config.

I've never had an anoying app like this one
![image](https://github.com/seerge/g-helper/assets/8308674/ba522ca0-d3c0-47b3-a9cf-3045bdb28ece)

**Comment by seerge** [comment]
@sebastienbo it's something that you can toggle on and off in Armoury Crate itself I think :) I have no idea how it's controlled
