### ISSUE TITLE
Performance drop

### ISSUE THREAD

**Issue by dmittryyyy** [seerge/g-helper#1579]
## NOTE
none

**Describe the bug**
During battery operation, changing the performance mode from "silent" to any other leads to a terrible drop in performance. 
The processor frequencies drop if you switch modes in a row and sometimes it works fine. It feels like the regime change is being applied incorrectly.
For example, I set "balance" and the frequencies drop to 0.40
I noticed that when I change the Windows power mode, everything returns to normal, no matter what mode is selected.

**Clear scenario to Reproduce**
1. Starting the laptop in battery mode
2. In g-helper change the performance mode to "balance" or "turbo"

**Expected behavior**
Performance drops significantly, animations slow down, opening folders and files takes a long time

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13310108/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Laptop zephyrus g14 AW SE GA401QEC-K2064T

**Asus software**
- Armoury Crate uninstall
- MyASUS uninstall

**Comment by seerge** [comment]
@dmittryyyy 

All modes are baked in firmware / BIOS, and not controlled by the app anyhow. App can only switch between them.

Given that it happens when device is on battery, I can make a guess that it's something with battery itself (especially if it's replaced recently, as laptop model is ancient and battery report 104% capacity ...)

```
09.11.2023 21:52:36: Design Capacity: 75998mWh, Full Charge Capacity: 79449mWh, Health: 1,0454090897128871812416116214%
```

There is nothing that can be and should be done here on the app side.
