### ISSUE TITLE
feature request: allow flipping mux switch without immediate reboot

### ISSUE THREAD

**Issue by colemickens** [seerge/g-helper#160]
Hi, again. Still love G-Helper, another small request.

In Linux, I am able to "flip" the mux switch without rebooting. Right now, I'm in Windows, with the dGPU disabled and I'd like to go ahead and enable it. But I'm also waiting on Steam to finish updating and Windows Update to complete an installation.

It would be great if I could switch this to Ultimate mode. I believe that it would also be possible for G-Helper to disable a little banner somewhere that says "Ultimate Mode will be enabled after reboot" along with a Cancel button, should the user change their mind.

Thanks!

**Comment by seerge** [comment]
Hello, from my experiments turning ultimate ON and not rebooting could cause windows to go nuts. That's a reason why both armoury and g-helper require immediate reboot :)

Therefore - i don't have any plans to change it for now

**Comment by vddCore** [comment]
This is can be done in a way that doesn't cause system instability, but given the unpredictable nature of ASUS' crapware, consider this an R&D trivia rather than a potential feature improvement.

On my machine (GA402RJ, FW .317), the following ACPI WMI register sequence has been used successfully:
1. Check the value of `DSTS_GET_ECO: 0x00090020`. If enabled, issue a corresponding `DEVS_` call with argument `0x00`.
2. Wait until embedded controller finishes the cycle - there is a hardcoded 7000-millisecond delay before the ACPI system continues, and only after that threshold is reached the system will become unresponsive ___if eco mode is enabled___.
3. Issue a call to `DEVS_SET_MUX: 0x00090016` with argument of `0x00` to switch the discrete GPU bus on.

Key takeaway is to ensure eco mode is switched off before trying to interact with the discrete GPU bus WMI control register.
Again, your mileage may vary, but eh. Might be worth a try if you're exceptionally bored.
