### ISSUE TITLE
Auto-stop ASUS Services

### ISSUE THREAD

**Issue by lucidnx** [seerge/g-helper#1628]
ASUS Services are automatically enabled and started after driver update.

I would like to have option to auto-stop and disable them as a checkbox next to Stop button maybe? Once set and forget :)

**Comment by H1m4ru** [comment]
There is a debloat file in the homepage which you can use to solve your problem. Check the FAQ section and you'll find it ;)

**Comment by lucidnx** [comment]
> There is a debloat file in the homepage which you can use to solve your problem. Check the FAQ section and you'll find it ;)

That's different scenario

**Comment by seerge** [comment]
@lucidnx hello.

I'm honestly not a big fan of doing that, cause you update Control Interface like couple of times a year only, and that's the only case when windows would re-enable all asus services.

Problem is that in some situations, windows may refuse to stop one of the services due to some permissions settings / etc and then app would be helplessly trying to stop them every time it starts.

What I can add somewhere in future, is a (closable) "notification" / banner on main app window, just telling that there are windows services running and it's better to stop them. It will be also handy for a first-time app users.

**Comment by lucidnx** [comment]
> @lucidnx hello.
> 
> I'm honestly not a big fan of doing that, cause you update Control Interface like couple of times a year only, and that's the only case when windows would re-enable all asus services.
> 
> Problem is that in some situations, windows may refuse to stop one of the services due to some permissions settings / etc and then app would be helplessly trying to stop them every time it starts.
> 
> What I can add somewhere in future, is a (closable) "notification" / banner on main app window, just telling that there are windows services running and it's better to stop them. It will be also handy for a first-time app users.

This may be nice solution too. Just some way to quickly disable all services without need to check whether they are running. This year, I'v got more than 10 updates, or at least it was re-enabled for some reason and it's quite annoying :)

**Comment by seerge** [comment]
@lucidnx ok, I'm closing this for now then :) and will think on suitable UI solution to notify users about running asus services
