### ISSUE TITLE
Panel Overdrive Should be disabled by default

### ISSUE THREAD

**Issue by ronellsalunke** [seerge/g-helper#1634]
Tuf devices (others as well) from 2019-2020 do NOT support panel overdrive. However, ghelper unlocks that functionality but these panels are basically running overclocked which permantently damages the panel (including mine) where I almost thought I'd have to get a display replacement. The display would be fine at 60hz but there is varying degree of artifacting when running at 144hz making the display (and by extension, the device) unusable until reverted back to 60hz. After investigating the issue across multiple reddit threads I eventually found that this is entirely due to panel overdrive and when I found the toggle in ghelper and disabled it, my laptop was fine at 144hz as well as 60hz.

**Describe the solution you'd like**
Panel overdrive being disabled by default like on armoury crate by default as these displays are not designed to be running with overdrive enabled at all times.

**Describe alternatives you've considered**
Alternatively, hiding the option for devices that don't natively support the feature.

**Comment by seerge** [comment]
@ronellsalunke hello,

If you say that overdrive option is not only available but actually makes visual difference (on the screen) it's clearly supported.

G-Helper just looks at asus very own endpoints exposed in windows, and since endpoint with overdrive on/off switch is there - it shows it in the app. Since endpoint exists - it means asus engineers have explicitly programmed it there by some reason, right? :)

When 60Hz is turned, app **always turns overdrive OFF**, so if you have issues with 60hz - i think reason is something else. What kind of artifacting are we talking about?

**Comment by ronellsalunke** [comment]
> When 60Hz is selected app always turns overdrive OFF, so if you have issues with 60hz - i think reason is something else. What kind of artifacting are we talking about?

My laptop is fine at 60hz, 144hz (with overdrive enabled) is the issue. 

> Why no one else mentions issues with overdrive ?

https://www.reddit.com/r/Asustuf/comments/11dm6bb/help_asus_tuf_f15_screen_flickering_at_144hz/?rdt=33148
https://www.reddit.com/r/ASUS/comments/y55cl6/screen_flickers_on_144_hz_but_is_normal_on_60_hz/
https://www.reddit.com/r/ASUS/comments/15wzieq/laptop_screen_breaks_only_on_144hz/
and other threads are describing the exact same issue but I can't seem to find how they started facing the issue to begin with. [This](https://www.reddit.com/r/Asustuf/comments/ydcimg/comment/itrg694/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) comment made me recheck and armoury crate shows no panel overdrive option for my device and disabling overdrive from settings seems to have gotten rid of the issue on my end.

>  Since endpoint exists - it means asus engineers have explicitly programmed it there by some reason, right?

Does the endpoint existing explicitly mean that the hardware is supported? If I don't have an overdrive button in armoury crate that also could be because of some reason. I was running in Auto mode (144+OD when plugged in and 60hz when charging) for a few months and while it did work perfectly until recently, I'm guessing it has damaged my display due to running with OD on constantly.

**Comment by Constrat** [comment]
@ronellsalunke The Display Panel Overdrive does not stand for 144Hz refresh rate. It means that it will reduce the latency (from 6 ms to 3 ms usually).
It's NOT "Overclocking" the screen (which is what happens when a monitor is pushed from 165Hz to 180Hz (for example the 27GP850 from LG).
I'm also not a fan of Overdrive because the reduction in latency is so miserable it doesn't make it worth. But from what I could understand your issue lies directly with 144Hz. If a screen is rated for 60 AND 144 it should not have any problems in both of them, and I think it can hardly be the fault of G-Helper.

**Comment by seerge** [comment]
@ronellsalunke 

I don't see this topics related anyhow honestly

1. https://www.reddit.com/r/Asustuf/comments/11dm6bb/help_asus_tuf_f15_screen_flickering_at_144hz/?rdt=33148
**It's 100% not related to g-helper**. As user switches refresh rate in windows(!) not in g-helper.  So overdrive simply can't be ON here by definition. Also overdrive is not mentioned anywhere ? Moreover there are no signs that g-helper is there even, cause i have only published first version in march and it had like 50 users in total.

2. https://www.reddit.com/r/ASUS/comments/y55cl6/screen_flickers_on_144_hz_but_is_normal_on_60_hz/
100 % not related to g-helper, **topic is 1 year old** ,app didn't exist on that moment

3. https://www.reddit.com/r/ASUS/comments/15wzieq/laptop_screen_breaks_only_on_144hz/
Also doesn't mention anything related to both **overdrive** and g-helper

> Does the endpoint existing explicitly mean that the hardware is supported? 
Based on how everything else works - yes

**Comment by seerge** [comment]
@ronellsalunke P.S. As @Constrat mentioned, you seem to mix up two separate and absolutely independent things - overdrive and just higher refresh rate (i.e. 144Hz).
