### ISSUE TITLE
dGPU fan not starting/switching off in custom fan curve

### ISSUE THREAD

**Issue by hmm-mm** [seerge/g-helper#1673]
**Describe the bug**
whenever custom fan curves are set in any mode(silent/balanced.turbo/custom) the dGPU (right side fan) doesnt start.
And if the dGPU fan was previously on and spinning it will stop after custom fan curve is enabled
{and yes its the same when dGPU is idle or *in use*}
(left side fan/ CPU fan always works, no problem there it follows the fan curve).
this has been happening for quite a while...

**Clear scenario to Reproduce**
just set a custom fan curve and enable it in any and all mode, the right side fan (dGPU fan) will completely stop spinning.

and after disabling the custom fan curve the dGPU fan starts spinning again  
 

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/131739165/534adaf4-23e6-426f-bd42-aec2eee18311)
with custom fan curve disabled

![image](https://github.com/seerge/g-helper/assets/131739165/a671d6c8-f033-4c4c-a049-b6c261613f2f)
with custom fan curve enabled(you can see the GPU fan with 0RPM)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - GA503RM

**Asus software**
- Armoury Crate (or it's services ) = all uninstalled
- MyASUS = uninstalled
- Other Asus services running in background = stopped

**Additional context**
tried clean install of Ghelper, enabling asus services , nothing helped
its been happening for months, always hoping for a fix in the next release but it never came so i thought its best to directly bring it to your attention.

**Comment by seerge** [comment]
@hmm-mm g-helper doesn't control your fans, they are controlled by bios. Check other similar issues and optionally try oled bios versions

**Comment by hmm-mm** [comment]
that is my point, the bios  doesnt seem to understand Ghelper's instruction about custom fan curve properly and thus it sets it at zero RPM.
Custom fan curve worked in armoury crate but it doesnt in ghelper.
So i think this is a gHelper issue ...

**Comment by seerge** [comment]
@hmm-mm custom fan curve command is exactly same for all models. If you would include log as it was asked in issue template, it would be visible there as well :)

In AC you can't even set a custom fan curves in Balanced (Performance) mode at all, you can only set in Manual, which is actually Turbo :) 

- Do fans work in Turbo with custom curve?
- Do fans work if you would restart laptop?
- Do fans work in exactly same settings when you start AC now ?

On a side note, G15 is known to have notoriously bugged BIOS, that's why I recommended checking older versions of it. Someone else here had similar issue after disabling / enabling dGPU and bios was refusing to turn on GPU fan after it, which was solved with other bios version

**Comment by seerge** [comment]
@hmm-mm https://github.com/seerge/g-helper/discussions/448

**Comment by seerge** [comment]
@hmm-mm Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
