### ISSUE TITLE
Brightness Control Doesn't Work

### ISSUE THREAD

**Issue by IlNEOlI** [seerge/g-helper#1688]
When I switch from Eco Mode to Balanced Mode, I can't change the brightness of the screen. I was using Armory Crate for couple of months and never experienced this issue. Is there any way to solve this?

Also there was an audio responsive keyboard backlight mode in Armory Crate. I know you have managed to add Ambient mode without stressing the CPU so much. Is it possible to add the audio mode as well?

**Comment by seerge** [comment]
@IlNEOlI hello,

Since you have ignored all requested info, and don't even know your model I can't help anyhow.

You may check this topic where I have explained a known nvidia driver behavior on 2023 models https://github.com/seerge/g-helper/discussions/1042 . As brightness is controlled by windows, not by some apps :)

As for "audio" backlight modes, I might add something in the future.
