### ISSUE TITLE
[Feature Request] Temperature Hysteresis for fan curve

### ISSUE THREAD

**Issue by chorong761** [seerge/g-helper#169]
**Is your feature request related to a problem? Please describe.**
A lot of times when the CPU boosts, it causes a temp spike and the fan kicks in for a short period

**Describe the solution you'd like**
A Temperature Hysteresis for when the temps increase 

**Describe alternatives you've considered**
I tried lowering the fan speed at higher temps but that would mean low fan speed when the CPU is actually loaded

**Comment by seerge** [comment]
As I understand you want to adjust a temperature throttle point (i.e since what temp CPU starts slowing down a bit)?

I think it really depends on a model, on G14 2022 it is set to 96C

There is no known to me way to adjust this limit that wouldn't require administrator permissions (so it would be possible to add it to the app)

But alternatively you can use more "hardcore" CPU tuning tool like https://github.com/JamesCJ60/Universal-x86-Tuning-Utility 
or smaller https://github.com/FlyGoat/RyzenAdj - they should let you set throttle point lower :)

**Comment by chorong761** [comment]
No, I don't mean to set when it's going to throttle, but rather a Hysteresis. Basically saying if I set the fans to kick in at 60c and I have a hysteresis of 5C, it would kick in at 65C and won't turn off until 55C

**Comment by seerge** [comment]
Ah, that's something is outside of app control completely :) 

Fans are controlled by bios, app just can apply (optionally) a custom fan curve to it, how it will be treated (i.e. when to start running fans and when to stop) is decided by asus :)

**Comment by seerge** [comment]
Closing, cause there is nothing that can be done here
