### ISSUE TITLE
Left side of the RGB lightbar doesn't light on Asus Rog Strix G531GV

### ISSUE THREAD

**Issue by Konnos998** [seerge/g-helper#1691]
**Describe the bug**
On G-Helper app when I open the RGB settings and put it to "Static" the left side of the lightbar doesn't light, but the keyboard lighting is ok.

**Clear scenario to Reproduce**
1. Go to G-Helper app.
2. Click on Laptop Keyboard -> Static

**Expected behavior**
Expecting RGB lighting to work without a problem in mode "Static".

**App Logs**
Attaching log.txt from ``%AppData%\GHelper``
[log.txt](https://github.com/seerge/g-helper/files/13539843/log.txt)

**Laptop OS & Name:**
 - OS: Windows 10 Home, 22H2 version
 - Asus Rog Strix G531GV (i7-9750H, RTX 2060)

**Comment by seerge** [comment]
@Konnos998 well, it's strange cause Rainbow or Strobbing is not different from Static from technical standpoint.

Have you tried OpenRGB, does lightbar work correctly if you set color there ?

Cause otherwise, I don't know what to offer :) as your device seem to be quite old, and could use some non-standard methods to set backlight otherwise :)

**Comment by Konnos998** [comment]
Oh I see. I'll try that also, thanks a lot!
