### ISSUE TITLE
UI Bug in Updates window

### ISSUE THREAD

**Issue by bourbonbourbon** [seerge/g-helper#1701]
**Describe the bug**
Weird UI text bug in the Updates window.

**Clear scenario to Reproduce**
1. Open G-Helper and click on the Updates button.

**Expected behavior**
No weird UI bug.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/13598078/log.txt)

**Screenshots or screencasts**
![image](https://github.com/seerge/g-helper/assets/109749723/42f7a5d3-02f4-4ea8-88bf-5a2073a85d60)

**Desktop (please complete the following information):**
 - OS: Windows 11, Build 22621.2715
 - Laptop model: ROG Strix G513RS

**Asus software**
- Armoury Crate (or it's services installed): Services Installed
- MyASUS installed: No
- Other Asus services running in background: Yes

**Additional context**
N/A

**Comment by seerge** [comment]
@bourbonbourbon it's just second line saying BIOS update(windows) not fitting :) this build should make that window a bit bigger
[GHelper.zip](https://github.com/seerge/g-helper/files/13598557/GHelper.zip)

**Comment by 0x5b62656e5d** [comment]
Describe the bug
Some more weird UI text bugs in updates window

Clear scenario to Reproduce
Steps to reproduce the behavior:

Open G-Helper and click on the Updates button, scroll down
Expected behavior
No weird text UI bug.

App Logs
[log.txt](https://github.com/seerge/g-helper/files/13626319/log.txt)

Screenshots or screencasts
![image](https://github.com/seerge/g-helper/assets/112295217/0652bcc4-137a-40c7-8270-54947c5f9c2c)

Desktop (please complete the following information):

OS: Windows 11 Pro WS, Build 22631.2792
Laptop model: GA401IU

Armoury Crate (or it's services installed): None
MyASUS installed: No
Other Asus services running in background: No
Additional context
N/A

**Comment by seerge** [comment]
@0x5b62656e5d hello, reason is the same - name of the driver is just too long :) problem is that table component in .net is not super flexible in terms of auto-resizing and making whole window even bigger may be too much here .
