### ISSUE TITLE
I strongly hope there is a complete Chinese translation!!!

### ISSUE THREAD

**Issue by JYGSaMa** [seerge/g-helper#1704]
G-Helper has many users in China. However, some options still do not have complete or reasonable translations. I hope you can see this feedback and optimize the translation. Finally, on behalf of Chinese users, I would like to pay tribute to you and thank you for developing such a perfect program.

**Comment by Kikimahe** [comment]
Hi Seerge,

I wanted to propose a french translation of "Windows Power Mode" and submenu in Crowdin to be identical to Windows.

I couldn't find the corresponding English text in Crowdin. Is it impossible to translate it because it comes from Windows settings?


In Ghelper (FR):

![Sans titre-1](https://github.com/seerge/g-helper/assets/142881210/71665369-5e63-4bdf-be3d-49314e2b9635)


In Windows (FR)

![Sans titre-2](https://github.com/seerge/g-helper/assets/142881210/7c5791d8-f49e-47c2-b5a4-7c644653bfda)

**Comment by seerge** [comment]
@Kikimahe I intentionally don't want to translate "technical" terms from windows, like CPU Boost settings or windows Power Mode. Main reason is that there is like 10 times more open info in google on what is that and what do those settings / value actually mean :)
