### ISSUE TITLE
Enable GPU on shutdown bug

### ISSUE THREAD

**Issue by Sanaan01** [seerge/g-helper#1727]
Hello, this feature has been working flawlessly on my asus strix g16 the bug of brightness controls not being present in standard mode is gone.

But a new issue is happening whenever i open my laptop from sleep the GPU is on which leads to high power consumption. I think ghelper gets mixed between sleep and shutdown?

**Comment by seerge** [comment]
@Sanaan01 hello, it doesn't mix sleep and shutdown :) but if you did hibernate, it's also shutdown.

Since you have ignored issue template and didn't include logs, I can't help much further.

I would recommend to just use Optimized GPU mode, then it will turn off dGPU on battery (even if it was turned off as a "workaround" before reboot/shutdown)

**Comment by seerge** [comment]
@Sanaan01 hmm, well, your windows reports to the app that it's about to Suspend (which is Hibernate)

And on that moment app acts, in logs it looks like that : 

```
12/12/2023 2:58:30 PM: Power Mode Changed:Suspend
12/12/2023 2:58:30 PM: Forcing Standard Mode on shutdown / hibernation
12/12/2023 2:58:31 PM: GPUEco = 0 : OK
```

Do you by any chance have some setting in windows power plan, that tells to put into hibernate in sleep ? Even G-Helper lets you control that (under ``Extra``).

May be try to reset your Balanced power plan in Control Panel to defaults ?
