### ISSUE TITLE
Bug when switching from Standard mode to Optimized while on battery

### ISSUE THREAD

**Issue by alibk94** [seerge/g-helper#1853]
**Describe the bug**
While on battery, I tried to switch from Standard mode to Optimized, but the computer abruptly restarts.

**Clear scenario to Reproduce**
1. Laptop was on AC power, and modes Balanced and Standard. Laptop screen refresh rate is on Auto.
2. Removed power plug
3. Went to G-helper
4. Click on Optimized under GPU mode
5. Computer suddenly restarts (or shutdown and boot itself back up - but Windows doesn't show "restarting")
6. When I log in to Windows, g-helper shows that it is in Eco mode
7. I switch to Optimized, it then switches successfully

**Expected behavior**
Switch to Optimized normally

**App Logs**
I attached them. I'm really not sure but it was either January 3 or January 4.
[log.txt](https://github.com/seerge/g-helper/files/13840949/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Laptop model: Asus TUF A16 FA617NS Advantage Edition. 

**Asus software**
- MyASUS installed
- Other Asus services running in background (_detected by g-helper_)

**Additional context**
Thank you for this amazing tool.

**Comment by seerge** [comment]
@alibk94 hello,

Optimized mode just swithces between Eco on battery and Standard when plugged in :) 

I don't see any switches on Jan 3 or 4 int the log.

Only on Jan 2 

```
02-Jan-24 2:16:56 PM: Running eco command 1
02-Jan-24 2:16:56 PM: Display configuration changed.
02-Jan-24 2:16:56 PM: Display configuration changed.
02-Jan-24 2:16:56 PM: GPUEco = 1 : OK
02-Jan-24 2:16:57 PM: TUF Brightness = 128 : OK
02-Jan-24 2:16:57 PM: Eco flag : 1
02-Jan-24 2:16:57 PM: Mux flag : 1
```

And Jan 5

```
05-Jan-24 12:24:20 PM: Running eco command 1
05-Jan-24 12:24:21 PM: GPUEco = 1 : OK
05-Jan-24 12:24:21 PM: Eco flag : 1
05-Jan-24 12:24:21 PM: Mux flag : 1
05-Jan-24 12:24:21 PM: \\?\DISPLAY#CMN1624#5&13619720&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL
05-Jan-24 12:24:21 PM: \\?\DISPLAY#CMN1624#5&13619720&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} \\.\DISPLAY1\Monitor0
```

In both cases there  are other entries in the log after that, so your device didn't reboot after that.

I don't know why it has rebooted that time. But due to the way asus as implemented GPU powering on or off, it could be that windows has acted or something else has happened :) Since your laptop was showing Eco mode after, it means that everything worked, and GPU was off. 

I wouldn't be too concerned about it.

I can't do anything else here, but would recommend to stop Asus services from running in the background to make sure they don't interfere.

Good luck

**Comment by alibk94** [comment]
Thank you for your follow-up seerge. I wanted to ask please, usually when I click "Optimized", the button itself stays highlight and it does not highlight "Eco". But when the computer abruptly restart, it was when after I entered g-helper again that I found "Eco" highlight. Usually it does not do that, so I'm confused about the normal expected behaviour.

**Comment by seerge** [comment]
@alibk94 it should be Optimized :) it could be that app's config got corrupted (or erased) due to unexpected windows' reboot, so then app just showed actual GPU state (which was Eco in your case).
