### ISSUE TITLE
Matrix Light Effect Range on ROG Zephyrus G14

### ISSUE THREAD

**Issue by Fenger1228** [seerge/g-helper#1860]
Is your feature request related to a problem? Please describe.
Yes, it is. I've noticed that the Matrix LED light's range on the ROG Zephyrus G14 2022 (GA402RJ) model is actually an irregular pentagon. However, this specific detail is not accurately represented on the light effect preview page in G-helper.

Describe the solution you'd like
I would appreciate it if the light effect range could be defined according to its actual irregular pentagonal shape on the G-helper's light effect preview page. This would provide a more accurate and satisfying user experience when customizing the Matrix LED lights.

Describe alternatives you've considered
An alternative solution could be to provide a detailed guide or illustration that clearly indicates the irregular pentagonal range of the Matrix LED lights.

Additional context
This feature request aims to improve the user experience when customizing the Matrix LED lights on the ROG Zephyrus G14 2022 (GA402RJ) model. A more accurate representation of the light effect range can help users better visualize their customizations.
![Snipaste_2024-01-07_01-13-23](https://github.com/seerge/g-helper/assets/63437924/3db45791-b7a9-469c-9194-9c7d6bda7fdb)

**Comment by seerge** [comment]
@Fenger1228 it's actually not that easy to do :)

Currently it's just a picture component that you can move / resize, but you can't really draw anything over it due to how windows forms and it's stuff works :|

Also that line won't be super precise anyway, as whole picture is only approximate indication of how it will look on real matrix.

So, sorry. I can't add it atm :)
