### ISSUE TITLE
Power Limit PL2

### ISSUE THREAD

**Issue by Licht555** [seerge/g-helper#1892]
You asked for proof of CPU power consumption above 130W.
![throttlestop_PL1](https://github.com/seerge/g-helper/assets/153838104/c6cf2b0d-d85e-4435-b33a-6526d991a197)

**Comment by Licht555** [comment]
![Licht555](https://github.com/seerge/g-helper/assets/153838104/dbe6219c-3a60-4255-865f-521054fffac1)

**Comment by seerge** [comment]
@Licht555 above 150W

I see that on first screenshot it says 139W ? So it's lower than 150 :) 

I don't have Intel device atm, can you run Cinebench23 (or any other CPU benchmark) and check power consumption using HWinfo for example ?

**Comment by Licht555** [comment]
In these images you can see that the maximum power consumption is above 150 W (170 and 190 W).

**Comment by seerge** [comment]
P.S. On first screenshot it says 139W and also POWER is red (i assume it means that POWER limit is reached on that stage?)

**Comment by seerge** [comment]
@Licht555 quick example of what I mean (it's just rog ally, so neglect actual values) :) 

![Screenshot 2024-01-11 151653](https://github.com/seerge/g-helper/assets/5920850/9587dce3-d92d-4bcd-9de2-1808723173cc)

**Comment by seerge** [comment]
@IceStormNG that's why I wanted to see actual chart of CPU usage, then it's much easier to see, if it's some 0.1ms jump (while actual average usage is way lower) or not :)

**Comment by seerge** [comment]
@Licht555 did you had a chance to run a benchmark and record CPU power usage using HWinfo ?

Also can you post a screenshot of your AC settings that you were using for that

**Comment by seerge** [comment]
@Licht555 also since you are here, do you mind to point out what exactly is saved in the registry from your previous posts ?

<img width="875" alt="Screenshot 2024-01-12 at 00 58 07" src="https://github.com/seerge/g-helper/assets/5920850/65ae6a90-ba4e-47da-82b4-362d3d2bd461">

<img width="882" alt="Screenshot 2024-01-12 at 00 59 30" src="https://github.com/seerge/g-helper/assets/5920850/26d41af5-3065-4b6f-9b7a-0b6f748ee785">

I would gladly remove that, but since app doesn't write anything in a registry in a first place it would be difficult to do :)

**Comment by Kikimahe** [comment]
Hi,

I think @Licht555 used the **ThrottleStop bench** to show a maximum power of 190W. 

If it helps to understand, I made 2 benches and looked at the results:


**ThrottleStop Bench Max Power : **
- Hwinfo64: 117.8 W max
- ThrottleStop: **127.2W** max !


**Cinébench 2024 Max Power : ** 
- Hwinfo64: 117.3 W max
- ThrottleStop: 121.8W max


My CPU has a PL2 at 115W max  (PL1 90W). 
For me, HWinfo therefore displays truer values than ThrottleStop. :) 



ThrottleStop Bench : 
![01](https://github.com/seerge/g-helper/assets/142881210/ea81ee6f-1635-43bf-8506-6d4b944d8ff2)

Cinebench 2024 
![02](https://github.com/seerge/g-helper/assets/142881210/6caea0bd-c978-4f17-8c6a-4b9532678519)

**Comment by squee666** [comment]
> > @Licht555 as far as I understand cluttered Throttlestop UI that's a limits ?
> 
> The right values with "Max" are the highest values observed by TS. So the machine did reach 98°C and 190.9W at some point (holy fu** .. is that really a laptop? how can Intel and ASUS think pumping almost 200W into the CPU is a great idea?)
> 
> The Power limit will also turn on if the value shown is lower. The reason is that the CPU can sample much faster than throttlestop can query the values. So the CPU can run into power limits for < 1ms and Throttlestop does not see those values, even though it runs with "Realtime" priority. The CPU still sets the registers for "Power limit".

yeah the intel 13900hx can peak 200w when unlocked its kind of a joke considering the 7945hx performs better and peaks 130w when unlocked

**Comment by squee666** [comment]
![image](https://github.com/seerge/g-helper/assets/628576/2611e785-8860-489c-a96e-893bfd389219)

**Comment by seerge** [comment]
@Licht555 any updates on the matter?

**Comment by Kikimahe** [comment]
Hello Seege,

I think you can close. :(
Unfortunately he will not give you any factual elements to justify all of this.

I'm very sad for you and for your unfairly criticized work. ;'(

https://rog-forum.asus.com/t5/tuf-asus-gaming-notebooks/can-you-safely-remove-ac-from-an-rog-laptop/m-p/988363#U988363
![Capture d'écran 2024-01-17 102007](https://github.com/seerge/g-helper/assets/142881210/f6afe7ed-c7f7-49dc-87ee-2a7cc89c2b73)

**Comment by seerge** [comment]
@Kikimahe it's sad, being accused in doing things that **opensource**(!) app doesn't do in a first place :)

**Comment by IceStormNG** [comment]
The problem is that they do not understand that there is something like "Intel Innovation Platform" / "Intel Dynamic Tuning" which constantly fiddles with the Power limits depending on GPU load and thermals.
Throttlestop can circumvent this by locking the MSRs, but this is not open source (afaik) and a little tricky.

**Comment by seerge** [comment]
@IceStormNG story is a bit longer :) 

Issue starter has stated that G-Helper "permanently" lowers power limits by "writing PL1/PL2 limits in registry" (?)

This is obviously not the case, as app just lets you select between predefined and hardcode in BIOS performance modes (same as AC does), and optionally set extra power limits / custom fan curves (same as AC does)

Selected mode is not saved anywhere "permanently", and BIOS just resets it after reboot back to default Balanced / Performance mode.

App is open source and this can be simply checked, but it doesn't seem to resonate. 

I wanted to help him and investigate what is specific situation in his case (and if there is an issue in a first place), but since there is no response I don't really know what is expected here.

**Comment by Kikimahe** [comment]
Don't be too worried Serge, GHelper has an excellent reputation. 👍 

Even ASUS Customer Service Agents suggest installing Ghelper instead of Armory Crate. 
It's funny. :)

![Capture d'écran 2024-01-17 111859](https://github.com/seerge/g-helper/assets/142881210/7f4d9f88-148d-4c8e-868f-69707b834730)
