### ISSUE TITLE
f11 always sleep on g14 2022

### ISSUE THREAD

**Issue by Dark1638** [seerge/g-helper#1899]
#
[log.txt](https://github.com/seerge/g-helper/files/13919440/log.txt)
# NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. Please respect the time of the developer. Thanks.

**Describe the bug**
doesnt matter if i hold f11 or not it always goes to sleep when pressed, only with FN-lock disabled does it go fullscreen and not to sleep
**Clear scenario to Reproduce**
1. press f11 -sleep
2. press f11+FN -sleep
3.fn lock off-> press f11- fullscreen
4. fn lock off->press fn+f11-sleep
5.so withfn lock enabled it always goes to sleep

**Expected behavior**

**App Logs**
Please include and attach log.txt from ``%AppData%\GHelper``

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - win11
 - asus rog g14 2022 GA402RJ

**Asus software**
- Armoury Crate uninstalled but services arent, just disabled from ghelper always
- MyASUS is installed

**Additional context**

**Comment by seerge** [comment]
@Dark1638 hello,

If you have Fn-Lock on your F11 performs the secondary action of that button (i.e. what would happen if you would press Fn+F11). So it works absolutely as intended.

FN+F11 will always trigger action, no matter if Fn-Lock is ON or OFF :) This is because asus keyboards don't have a hardware Fn-Lock, and G-Helper just imitates it by binding F1-F11 keys to corresponding actions on windows level when Fn-Lock is ON.

**Comment by Dark1638** [comment]
So with fn lock enabled it is always supposed to put it to sleep, no matter
if fn is pressed or not?

**Comment by seerge** [comment]
@Dark1638 'with Fn-lock enabled, all F-keys do the action of Fn-F-keys :) that's the only thing Fn-Lock does. There is no "reverse" option

**Comment by Dark1638** [comment]
Ok thx for the answer and explanation, so ig to use fullscreen fn lock just
has to be disabled. :)
