### ISSUE TITLE
Rog G703 Heatmap + GPU Mode + Ambient not working

### ISSUE THREAD

**Issue by Vox87** [seerge/g-helper#1995]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

ASUS Rog G703
Thanks for the great software
I hvae a problem with the Heatmap + GPU Mode + Ambient 
I only care about the Ambient 
It's not working, or shows last color ( Static Green most of the time)

all the other modes are working fine without any problem

Laptop: Rog G703GX
Win 10
G-helper 15

### How to reproduce the bug?

selecting the ambient option from the dropdown menu

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14079503/log.txt)

### Device and Model

Rog G703GX

### Additional information.

I tried with Armoury Crate installed and without, nothing changes 

### Armoury Crate

Installed

### Asus Services

2

### Version

015

### OS

Win 10 latest

**Comment by seerge** [comment]
@Vox87 hello, I'm afraid your device is just simply too old and therefore has different RGB protocol to set colors.

Do other RGB modes work ? 

If you have per-key or at least 4-zones RGB in it, can you try OpenRGB and check if you can set color per each key or zone ?

**Comment by Vox87** [comment]
> @Vox87 hello, I'm afraid your device is just simply too old and therefore has different RGB protocol to set colors.
> 
> Do other RGB modes work ?
> 
> If you have per-key or at least 4-zones RGB in it, can you try OpenRGB and check if you can set color per each key or zone ?

ikr. Thanks for reply, 

Yes, other modes are working perfect with G-Helper, I even manged to download the old AURA software and all modes are working but unfortunately it doesn't have an ambient mode!

OpenRGB is buggy AF for me, I couldn't get it to operate not even close to G-Helper. In the other hands, SingleRGB is good but it detected the laptop wrong and the size of the monitor is wrong. All effects are working but in wrong size. Example: The num pad at far right not lit

I think each led is individually addressable, but I have no idea how confirm it.

**Comment by seerge** [comment]
@Vox87 hello,

SignalRGB is a same closed / proprietary app as Armoury :) so it can't help anyhow.
Since OpenRGB is not working for you - then there is no open (source) information about how RGB is controlled on your device.

I can make only one guess, that your device is same as other ROG Strix models, and accepts per-key RGB.

Try this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14095845/GHelper.zip)

If it won't work neither, I don't have any other ideas :)

**Comment by Vox87** [comment]
> @Vox87 hello,
> 
> SignalRGB is a same closed / proprietary app as Armoury :) so it can't help anyhow. Since OpenRGB is not working for you - then there is no open (source) information about how RGB is controlled on your device.
> 
> I can make only one guess, that your device is same as other ROG Strix models, and accepts per-key RGB.
> 
> Try this build [GHelper.zip](https://github.com/seerge/g-helper/files/14095845/GHelper.zip)
> 
> If it won't work either, I don't have any other ideas :)

Amazing work! I appreciate it, all modes are working perfectly!

just to make it more better and accurate see the images, 

- The size of the keyboard and monitor isn't accurate.
- Sometimes the blacked area is lit with little brightness it should be off


idk if this is a hardware limitation or software.
Anyways, it's all good by my side

**Comment by seerge** [comment]
@Vox87 hello, thanks for the photos.

All of them look fine as for me, and app works as it was programmed.

It splits screen only in 4 x 2 zones and measures colors for them. First row for screen, second row for lightbar (your model is rare exception in this case)

This is done in order to have universal approach for 4-zone RGB models and per-key RGB models (as yours) and also to keep things simple and fast (!).

So I consider this done then :) All this changes are already live in 0.151

Thanks :)
