### ISSUE TITLE
Peripheral Support in G-Helper (subset of Armoury Crate)

### ISSUE THREAD

**Issue by sinful-asura** [seerge/g-helper#2031]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Yes, mainly I have a problem with armoury crate itself as a product which is annoying and causes various crashes and has some magic miracle formula where you have to disable fast startup or it stops working & stuff like that - we're all aware about it.

Asus has some nice peripherals and currently there's no alternative to control their functions if AC is uninstalled so I'm not sure if it's possible to create a segment inside G-Helper related to peripherals, that was an idea I had

### Describe the solution you'd like

I'd honestly just like to be able to control peripherals without installing the AC bloatware, e.g. I have two Asus ROG peripheral items and currently can't control them

I've Asus ROG Azoth and not being able to control that is okay, nothing much there aside from macro remap and oled display animations

But the main problem is I also have Asus ROG Theta 7.1 and default windows drivers are horrible for these headphones, it sticks it permanently into echo-y theatre-like mode and I lose all the options that are present in AC for these headphones

### Describe alternatives you've considered

I'm currently using Dolby Atmos to control the headphones but it's a very limited subset of control, e.g. microphone and 7.1 and various AI-related stuff as well as modes & levels are missing from it

### Device and Model

Asus ROG Flow X16, Asus ROG Azoth, Asus ROG Theta 7.1

### Additional information.

I'm a programmer as well so if there's any way I can help, I'd be glad to do so - but I'm mainly focused on Web Dev so I'd have to learn ins and outs of what has to be done here

**Comment by seerge** [comment]
@sinful-asura hello,

I can't add support for those peripherals, cause I don't own them and have absolutely no idea how are they controlled.

In case of your headphones, if it's some hardware-setting - why don't you just set desired mode inside AC prior to uninstalling it? If it's emulated on software level, like AC has own service for AI noice cancellation - then there is no chance it will be in G-Helper obviously :)

P.S. You've also used a wrong issue template, as there is a separate one for a peripheral support request.

**Comment by IceStormNG** [comment]
Problem with hardware support is, that I would need the respective hardware to support it. Most devices of the same category work the same, but I only have an ASUS mouse and soon an ASUS gamepad to implement those.

Headsets and Keyboards can only be done after I did the initial reverse engineering process with one of these devices, and this is nothing I can teach anyone in reasonable time. 
I mean, if anyone manages to decode the protocol, I can implement it. Otherwise this has to wait until I can get my hands on one of those devices.
And for sound, some features rely on Realtime processes from AC, like the noise cancelation. We will probably not integrate those, because it is a whole other can of worms. But any setting that can be configured to be done in hardware can be implemented if there is an USB endpoint we can access.

**Comment by seerge** [comment]
@sinful-asura hello, 

If you are interested you can test external keyboards support in a new build https://github.com/seerge/g-helper/discussions/5710 

Thanks!
