### ISSUE TITLE
Asus ROG Zephyrus M16 (2023), switching between balanced and turbo constantly while under load

### ISSUE THREAD

**Issue by num421337** [seerge/g-helper#2086]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When playing a game it will switch between balanced and turbo modes. This will cause a temporary stutter in performance as the modes switch as well as taking focus away from my game when the turbo/balanced message pops up. If I close G-helper the stutter still happens as it's likely switching modes still.  Is there anywhere that shows

### How to reproduce the bug?

Play a game, after a while mode is switched from balanced to turbo fans speed up game stutters and loses focus from the icon popping up. I have to click back into the game, and then after some time sometimes almost immediately it switches back to balanced and keeps repeating the loop.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14324803/log.txt)

### Device and Model

Asus ROG Zephyrus M16 (2023) GU604VI

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154

### OS

Windows 11

**Comment by seerge** [comment]
@num421337 hello,

The reason your device switches is cause windows (and asus bios next that) reports that device is unplugged. And balanced is last mode used on battery.

2/16/2024 9:22:10 PM: AutoSetting for Offline

It looks like a faulty charger, that doesn't provide enough power for your device in turbo mode.

Even if you will quit g-helper as you say, your device will think it's unplugged while under load in gaming and stutter. It's not the app's fault in a first place.

As a temporary measure try to set lower power limits in turbo (for example 50w instead of 80w) to see if it helps.

But in general you need to find a way to fix hardware, for example get a new charger.

**Comment by num421337** [comment]
the charger is brand new It would be weird to be already faulty but I can test some things with that. perhaps a different outlet or something

**Comment by seerge** [comment]
@num421337 even if it's brand new windows switches to battery mode :)

**Comment by seerge** [comment]
@num421337 try to do what i suggested above 

I.e. either set lower power limits  (cause you use manual mode de facto) or just reset it to default Turbo.

May be then device won't be switching to battery

**Comment by seerge** [comment]
@num421337 hello, any updates on the matter? :)

**Comment by seerge** [comment]
Closed as abandoned
