### ISSUE TITLE
modern standby switch from Armoury crate

### ISSUE THREAD

**Issue by s4-Liuzhuang** [seerge/g-helper#2105]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I would like ghelper to implement the modern standby switch from armoury crate so I can enter sleep mode properly

### Describe the solution you'd like

Modern standby switch

### Device and Model

Asus zephyrus M16 2023

**Comment by seerge** [comment]
That “switch” is just a hibernate in sleep setting. It already exists in the app for ages under Extra

**Comment by RamouzK** [comment]
Hi @seerge - to not open a new issue about this, under Extra, it's the "Minutes till Hibernation in sleep on battery"?
The one I'm looking for is Modern Standby Assist from Armoury Crate.
Enable/disable feature so that we can stop it from hibernating if we want to.
If that's the setting, I've always had it set to 0, and now a few days ago I moved to a G18 2025 laptop, G815LR, from a G18 2023 edition, with modern standby unfortunately, and after it sleeps for a few hours, it goes to hibernate on its own. Not sure how to resolve that. Sleep mode in control panel power options has Hibernate set to never.

Armoury Crate fully uninstalled. Services stopped in G-Helper Extra.

**Comment by seerge** [comment]
@RamouzK windows generally has 2 conditions when it would hibernate device in sleep

- Hibernation by timeout ([setting in windows power plan](https://www.tenforums.com/tutorials/108391-add-remove-hibernate-after-power-options-windows.html)). This is what you can configure under `Extra`
- Hibernation when battery loses certain % of charge (usually something like 10%). That's what happens in your case I think :)

**Comment by RamouzK** [comment]
Wow, I never knew about number 2! Not sure it's entirely accurate in my case because I woke up and after waking it up from hibernate, it was at 94%. Maybe after 5 % it activates. Any way to change that? Boy do I hate modern standby.

**Comment by seerge** [comment]
@RamouzK try to r[eset power plan to defaults](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults), may be it will reset to 10%

**Comment by RamouzK** [comment]
> [@RamouzK](https://github.com/RamouzK) try to r[eset power plan to defaults](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults), may be it will reset to 10%

Sadly, it doesn't work. It's okay, it seems to be a Windows issue then since neither G-Helper's settings nor power options are working. Or, it's an Asus firmware issue.
Or maybe G-Helper really needs the Modern Standby Assistant setting so that we can disable that?

**Comment by seerge** [comment]
@RamouzK it's not a firmware, it's windows thing. But I don't know if can be disabled.

You can only disable hibernation completely from what i know, but it's handy to have it actually.

**Comment by RamouzK** [comment]
Thanks for the help so far. Back to the original request though, is it possible to add "Modern Standby Assistant" as a toggle, on or off, like Armoury Crate? Or will it interfere with G-Helper's "Minutes till Hibernation in sleep on battery"?
I really just want G-Helper to be a full replacement and have all the latest goodies from AC :).

**Comment by seerge** [comment]
@RamouzK from my understanding this is what Standby Assist does in AC, it enables hibernation in sleep. So instead of making it fixed ON / OFF  i have made if configurable, from 0 - OFF, to any minutes up to your liking :)

Of course you still have that other hibernation reason in windows itself, that seem to act independently from AC or G-Helper's wil

**Comment by RamouzK** [comment]
Yeah, so I have no idea if your setting is the same as Modern Standby Assistant (MSA). I suspect it's not.
I changed the Windows Power Options battery hibernate after setting to 90 minutes, and it also reflects that in G-Helper. I did this because my G18 2025 goes into hibernation even if set to never. It seems to have after about 6 hours of being in sleep. It seems to be a firmware thing from what I can see, and not a Windows thing since I have it set to never. Of course, who knows.

But, the MSA setting seems different.
I don't know if it's possible for you to add it or not, but if it is, I wonder if it would solve the issue I have where it goes to hibernate even though I have it set to never. 
Having all settings from AC would also help, since many of us are looking for all features. Anything you do is appreciated though since it's your time.

Thank you for all you do.
