### ISSUE TITLE
Factory defaults under fans and power is not working correctly. 

### ISSUE THREAD

**Issue by LeoRH123** [seerge/g-helper#2193]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

factory defaults used to set G-helper fans+power settings to default: CPU turbo boost, power limits, but now it doesn't appear to work unless I manually change the options. 

### How to reproduce the bug?

1. Go to G-helper fans+power settings
2. choose a different CPU turbo boost like efficiently enabled
3. check box apply power limits
4. click factory defaults button trying to get everything back before the change
5. nothing happens

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14551969/log.txt)

### Device and Model

ASUS TUF Gaming A15 FA506QM

### Additional information.

I just clicked on apply power limits (80W appears when I choose something different from aggressive under turbo boost), I clicked the factory defaults button nothing happens, tried to delete G-helper data, but nothing changed, and I don't see anything related under the log file.
![image](https://github.com/seerge/g-helper/assets/33641164/54df68c3-8f9c-4975-8bec-b916fc8e29ae)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.154.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@LeoRH123 hello,

App doesn't reset power sliders on "Factory Defaults" ,it just unchecks Apply under them. When power limits are not applied - they have no effect, system will use whatever asus engineers have hardcoded in this mode by default. There is no way to read those values.

CPU boost is just a setting in windows power plan, it's not being reset , as there is no "default" setting for it as well :)

It's by design.

Power mode / fans reset to their default states, can be read.

Thanks.
