### ISSUE TITLE
Disable ASUS Update Checker 2.0 in task scheduler

### ISSUE THREAD

**Issue by nopeless** [seerge/g-helper#2213]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Related #362 

In task scheduler, there is a very frequently running task that checks for asus updates. Since G-Helper has its own update tab, I think this is relevant to disable as well (also automatic updates are the bane of my existence)

### Describe the solution you'd like

`schtasks /change /tn "ASUS Update Checker 2.0" /disable` for stop asus services. Most people don't know the difference between a service and a task and I think such abstraction in the button itself is ok. I'll write extra docs about what that button does if needed in the wiki

### Describe alternatives you've considered

This is a rather niche thing but considering the community using this app, it should be included as well

### Device and Model

N/A

**Comment by Kikimahe** [comment]
Hi, 

There are also the Asus Optimization and AsusSystemAnalysis tasks. These tasks are used by My ASUS and can be disable.
If you have never installed MY ASUS or AC, ASUS drivers install these unnecessary tasks (and services). :'(

Only Asus Hotplug controller is required and must be enable.

**Comment by seerge** [comment]
@nopeless hello,

I honestly don't want to design app in order to "fight" with leftowers from AC / etc.

The reason Services stopper exists, is mainly cause Asus Optimization Service would otherwise take over hotkeys and some other important functions. And also cause those services would be present even on a clean windows install, cause they are part of driver package.

As for the others - AC uninstaller wipes everything quite effectively. If i start cleaning them here, it will literally open a pandora box of requests to delete / disable some other things, etc.

**Comment by nopeless** [comment]
AC is not installed on a fresh windows install. on the other hand, this task is. But i understand your concern and decision that this is out of scope. thanks for replying :)

**Comment by nopeless** [comment]
I remembered why I raised this issue for myself. 

This thing sent me a notification using asus survey whatever and I got mad.

For those who don't want to disable this but still want the updater to run 

```ps1
taskkill /im asussurvey.exe /t /f
rmdir -recurse -force C:\ProgramData\Asus\AsusSurvey
```
