### ISSUE TITLE
Fans shortly turn on then off when plugging/unplugging charger or when waking up the display

### ISSUE THREAD

**Issue by nathancdy** [seerge/g-helper#2227]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Recently happening where my 2024 G14 fans turn on for a few seconds then turns back fof when I plug/unplug the charger (happens with both proprietary or USB-C charger) or when waking up the display when it turns off.

### How to reproduce the bug?

1. Plug/unplug charger or wake up display
2. Fans ramp up for a couple seconds then turns back off

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14609429/log.txt)

### Device and Model

ASUS Zephyrus G14 GA403UV

### Additional information.

I understand fans are controlled by BIOS, but I haven't updated my BIOS and this only happened recently.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.159

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@nathancdy hello

When you plug / unplug app would would set last used mode for that state and all corresponding settings in it if they are applied lied fan curve, limits, etc.  It's needed or laptop's bios may forget it's settings when unplugged. And when you set a mode - bios may decide to restart whole fan control algorithm and run fans for a second (that depends on the model)

Same happens when device wakes up

**So this is normal** :) and i can't really change this.

P.S. When I keep everything on Silent mode mg G14 2024 is tend to stay silent.

**Comment by seerge** [comment]
@nathancdy P.S. Next to that, cause you have a custom power limits for your Silent mode, app would do a limits "reset" trick that I have explained here https://github.com/seerge/g-helper/issues/2148#issuecomment-1978684019

```
2024-03-14 5:47:08 PM: AutoSetting for Online
2024-03-14 5:47:08 PM: BatteryLimit = 80 : OK
2024-03-14 5:47:08 PM: Reset = 1 : OK <--- reset setting turbo for a second, to "reset" limits before applying a new mode
....
2024-03-14 5:47:09 PM: Mode = 2 : OK
```

But since even after "reset", in your case it applies limits again, it may be not needed in this specific situation.

I have added one more small tweak, so this "reset" will be done only if app needs to switch to default mode w/o any custom limits.

So check this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14614788/GHelper.zip)

P.S. I hope asus fixes this sticky limits in future bios updates, so "reset" won't be needed at all, as it's not needed for any other model :|

**Comment by nathancdy** [comment]
@seerge Fans no longer ramp up with this build! However, I switched my Slash Lighting for Dim to Off while testing, and I noticed that when I plug in my charger, the Slash Lighting still turns on briefly then turns off (I have it disabled on battery)

[log.txt](https://github.com/seerge/g-helper/files/14617021/log.txt)

**Comment by seerge** [comment]
@nathancdy before setting Slash (or AnimeMatrix) settings app would send an Init command to it, or they don't accept that.

I have removed Init for case when you are about to set it off. Please test carefully in all circumstances, if you can also turn it off later after it being on

[GHelper.zip](https://github.com/seerge/g-helper/files/14618572/GHelper.zip)

**Comment by nathancdy** [comment]
@seerge I've had Slash Lighting to OFF since my last comment and had it turn on/shut down a few times since then, however, on startup the Slash Lighting briefly turns on at Logo screen (Transmission Pattern). I then downloaded the opened the new build you just sent, plugged my charger to my laptop, and the Slash Lighting briefly turns on then off again (Flux Pattern, which was my previously set pattern). Not sure why it's doing that, and I'm not sure if this was the case before as I didn't notice the Slash Lighting turn on until now.

Do you possibly share the same behaviour for your 2024 G14? (Slash Lighting turning on briefly at startup and when plugging in charger despite the setting it to OFF)

**Comment by nathancdy** [comment]
> P.S. When I keep everything on Silent mode mg G14 2024 is tend to stay silent.

I typically only use Silent mode and the fan problem does still occur, when the fans turn on it only goes to 2000RPM at most.

**Comment by nathancdy** [comment]
> I have added one more small tweak, so this "reset" will be done only if app needs to switch to default mode w/o any custom limits.
> 
> So check this build [GHelper.zip](https://github.com/seerge/g-helper/files/14614788/GHelper.zip)

I reinstalled this build as the latest build you sent didn't fix the Slash Lighting problem I was getting anyways, but now my original problem reoccurs. I can definitely live with the problem at the moment, just wanted clarification on whether the problem is BIOS-bound or fixable through G-Helper. thanks

**Comment by seerge** [comment]
@nathancdy the "slash-lightning" build also includes the change I did for mode switching :) So there is no need to redownload that.

1. If fans still briefly turn on on mode swap (sometimes) it's likely due to the reason I explained in my very first comment in this thread.

2. It could be that Slash Lightning has separate startup / shutdown "animations" like AnimeMatrix has. Anyway I'm not sure if this can be controlled here. 

How does the build I linked behave when you plug / unplug charger if Slash setting was already set to OFF beforehead ? Can you post a log ?

**Comment by seerge** [comment]
@nathancdy can you also check this build, I have removed one more init / wake up command for slash lightning for situations when it needs to be OFF
[GHelper.zip](https://github.com/seerge/g-helper/files/14623049/GHelper.zip)

**Comment by nathancdy** [comment]
@seerge Hi, from the latest build, it still remains the same behaviour where when I plug in the charger, the Slash Lighting turns on for a few seconds then turns off. Unplugging doesn't turn on the Slash Lighting, maybe because I have it Disabled on Battery. 

I haven't owned another G14 using the AnimeMatrix, so it is possible the Slash Lighting that turns on on startup/shutdown is meant to happen during those times. 

Here is the log:

[log.txt](https://github.com/seerge/g-helper/files/14625069/log.txt)

**Comment by seerge** [comment]
@nathancdy oke, can you do a simple test. Quit G-Helper and check if Slash lightning still turns on for a few seconds when you plug / unplug ?

**Comment by nathancdy** [comment]
@seerge Yeah, the behaviour still occurs even when G-Helper isn't running (Pressed Quit from tray application). I think I already asked about this but does the same Slash Lighting behaviour happen to you? Not sure if my problem is an isolated incident or not.

**Comment by seerge** [comment]
@nathancdy i don't have access to g14 2024 anymore, so can't say :) But if same happens when app is completely stopped, it's not due to app's settings in a first place ... :|

**Comment by seerge** [comment]
@nathancdy but from what I remember from my usage of 2024 model, slash lightning was showing charge level when you plug / unplug ... :|
