### ISSUE TITLE
Custom fan profile not working

### ISSUE THREAD

**Issue by TrooperZ** [seerge/g-helper#2232]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Whenever I set my custom fan profile and tick the box to use it, My CPU fan starts dropping and my GPU fan starts skyrocketing (CPU at 88c, GPU at 68), almost as if the temperatures used for the profiles were switched. Using the option disabled with automatic fan control, the fans work fine as expected.

### How to reproduce the bug?

Set custom fan profile and check the option to use them.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14622271/log.txt)

### Device and Model

Asus G15 2022 R9 6900HS 3060

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.158

### OS

Windows 11 10.0.2261

**Comment by seerge** [comment]
@TrooperZ hello, you clearly did not read FAQ.

G-Helper is not controlling your fans. Your problems are due to a bugged BIOS on your device.

Please check what other people say with same model / bios write her https://github.com/seerge/g-helper/issues/2049#issuecomment-1995687645 or numerous of times on reddit about this behavior independently if you use AC / GH or anything else

**Comment by seerge** [comment]
@TrooperZ  Hello, if you are interested you can try an experimental build with actual "manual" fan control https://github.com/seerge/g-helper/discussions/2272 . Thanks
