### ISSUE TITLE
Switching profiles GPU limit

### ISSUE THREAD

**Issue by mrunknown9999** [seerge/g-helper#2252]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have set for the Balanced Mode a 25/15 Watt limit on the CPU. I have also a new custom profile created for usbc 100 Watt charging which has as 1600 Mhz limit on the GPU. When I switch between these 2 modes, the Balanced + retains the GPU limit form custom mode, although I had not set one up. If I cycle through other standard modes (without + changes) the switch is correct. 

### How to reproduce the bug?

When I switch between these 2 modes, the Balanced + retains the GPU limit form custom mode, although I had not set one up. If I cycle through other standard modes (without + changes) the switch is correct. 

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14655858/log.txt)
![gpu limit](https://github.com/seerge/g-helper/assets/128497652/36283d7c-bb41-4dac-925b-f57e236d4e01)
erge/g-helper/files/14655858/log.txt)

### Device and Model

Flow X13 2023  RTX 4060 

### Armoury Crate

Uninstalled

### Version

0.158

**Comment by seerge** [comment]
@mrunknown9999 hello,

This is actually quite intentional.

As there is no "default" clock setting for GPU app wouldn't touch them for any mode unless user explicitly have set them to something.

This is done to prevent overriding from the app side settings set by other overclocking apps like Afterburner or nvidia-smi

So just set a new clock limit for your other mode (or drag it to Default i.e "no limit" state) and next time you select that mode it should apply

**Comment by mrunknown9999** [comment]
Perfect! Thank you!
