### ISSUE TITLE
CPU Boost dropdown updating bug

### ISSUE THREAD

**Issue by manciuszz** [seerge/g-helper#227]
CPU Boost dropdown menu fails to update properly when cycling through profiles.
<video src='https://user-images.githubusercontent.com/2539661/231302625-447fc299-c0a1-4c73-bcd6-4a1966503856.mp4' width=480 />

**Comment by seerge** [comment]
@manciuszz can you post your config.json here ?

**Comment by manciuszz** [comment]
**config.json**
```json
{
  "performance_mode": 0,
  "performance_1": 0,
  "gpu_mode": 1,
  "frequency": -1,
  "overdrive": 1,
  "aura_mode": 3,
  "aura_speed": 0,
  "gpu_auto": 0,
  "mid_fan": 0,
  "limit_total_1": 125,
  "limit_cpu_1": 80,
  "limit_total_2": 125,
  "limit_cpu_2": 80,
  "charge_limit": 80,
  "limit_total_0": 125,
  "limit_cpu_0": 80,
  "auto_boost_2": 2,
  "auto_boost_0": 3,
  "auto_apply_1": 0,
  "auto_apply_power_1": 0,
  "fan_rpm": 0,
  "scheme_0": "6d264563-183f-431a-ab92-f2607da30dba",
  "scheme_1": "30b7929b-a695-4451-8425-7ba3253260f4",
  "scheme_2": "2c01786e-b4e6-4b88-830e-b02a8104a168",
  "auto_boost_1": 2,
  "fan_profile_cpu_1": "14-3F-44-48-4C-50-54-62-11-1A-22-29-34-43-51-5A",
  "fan_profile_gpu_1": "14-3E-43-47-4C-50-53-62-16-22-2C-33-40-4A-58-5F"
}
```

**Comment by seerge** [comment]
@manciuszz ok, looks like it's connected with a custom power plans i have added for you, i will push a fix tomorrow

**Comment by manciuszz** [comment]
Although this is not related to the bug, I don't want to create a new issue if I can help it.

---

It would be nice to have an **on hover (or on mouse down) tooltips** inside the graph over each fan node. 

At the moment we only see tooltips when we interact with a specific node, usually by dragging it 1 pixel. That's not very user friendly. It's pretty difficult to adjust nodes fast on first try using a HIGH DPI mouse :/

**Comment by seerge** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/11209918/GHelper.zip)

1. This build should set CPU Boost after switching power scheme, so it should work as intended (even tho you config may be messed and you may want to set boost settings for each profile again)
2. Chart tip should appear every time you move mouse over a curve
3. Reset factory defaults is done like that because how "technically" all those settings work :

- app sets one of 3 predefined modes in bios
- app sets fan curve (if selected)
- app sets PPTs (if selected)

Reset - just sets predefined mode, without setting anything else.
