### ISSUE TITLE
GHelper crashes instantly when executed

### ISSUE THREAD

**Issue by Nudelul** [seerge/g-helper#2318]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi. I followed every step in the installation guide, even the optional ones.
But somehow the app instantly crashes when I execute it. It doesn't even open up.
Attached is a screenshot of the event log of the error (i have installed the latest version of .NET 7).
Thanks.
<img width="464" alt="Screenshot" src="https://github.com/seerge/g-helper/assets/118117967/b4212dd9-00f8-4388-a924-fef1bb980861">

### How to reproduce the bug?

I don't know? I just followed the installation guide.

### Logs

I have no log file. Not even a GHelper folder in AppData, be it in Roaming, Local or LocalLow.

### Device and Model

Asus Zephyrus G15 GA503RM 068W

### Armoury Crate

Uninstalled

### Asus Services

In taskmanager I see 11 of Asus and 3 of Armory Crate (Control Interface, C.I. Monitor and Key Control)

### Version

0.161

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Nudelul hello, looking at error message it doesn't crash inside app's own "code", but rather inside .NET library itself (otherwise it would point out what exactly is wrong there)

I don't know why it happens, honestly.

Do you have any tricky permissions in windows, that would prevent app from creating ``%appdata%\GHelper`` folder ?

Try to completely uninstall .NET7 from windows, and then download SDK (not runtime) from https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.407-windows-x64-installer and install again ?

**Comment by Nudelul** [comment]
Thanks so much! Reinstalling .NET7 actually worked!!
Have a nice day ^^

**Comment by seerge** [comment]
@Nudelul amazing
