### ISSUE TITLE
Freeze On-touchpad numberpad and personalize M4

### ISSUE THREAD

**Issue by LuzeBillan** [seerge/g-helper#2327]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

1. Well, I found the virtual numberpad enabled as long as I pressed number lock on my physical keyboard, but I don't like the virtual numberpad at all. Could you please freeze this function?
2. And... I still would like to personalize M4 on my strix. You told me that it is just the same as pressing Fn+F5, but I still want this function even if that of Fn+F5 is also altered.

### Describe the solution you'd like

Freeze the virtual numberpad and personalize M4

### Device and Model

Strix 7

**Comment by seerge** [comment]
@LuzeBillan hello, I have no information on how that "virtual touchpad" is toggled. 

Since it works for you as is, most probably it's controlled completely by hardware / firmware and not by apps. So I can't offer anything w/o having access to the actual device.

As for Fn+F5 binding, as I have already answered, changing that will have a **negative impact** on other users, so I don't plan to change that.

Thanks.

**Comment by LuzeBillan** [comment]
All right... thanks
