### ISSUE TITLE
Constant running fans and higher tempeartures

### ISSUE THREAD

**Issue by SynStark** [seerge/g-helper#2358]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

So for the last few updates I've been noticing a slightly higher temps and fan noise. I remember 3-4 months ago my fans were quiet during day to day stuff with temperatures like  up to 40c GPU and 46-49c CPU. After the last update yesterday, now my fans are running constantly even when doing nothing at 1900 RPM for both CPU and GPU and Mid Fan at 2400 RPM. Temps are in the 60s.

Should I try going back to older versions with the risk of losing newer options or is there any alternative?

Thank you for all the help!

### How to reproduce the bug?

N/A

### Logs

N/A

### Device and Model

Scar 18

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.164.0

### OS

11

**Comment by seerge** [comment]
@SynStark hello, new updates has nothing to do with your temps (and correspondingly fan speeds). 

Temperatures depend on actual usage of your CPU (i.e. what processes do you have running in windows and what settings do you have). So you should look what else did you change.

You are free to use any version of the app as it will not affect abovementioned issues anyhow.

Since you didn't include logs, i can't assist you further.

Thanks and good luck

**Comment by seerge** [comment]
Closing this as answered. 

If you will find a previous version that somehow changes behavior of your device, please feel free to re-open and upload logs from both. 

Thanks.

**Comment by SynStark** [comment]
> Closing this as answered.
> 
> If you will find a previous version that somehow changes behavior of your device, please feel free to re-open and upload logs from both.
> 
> Thanks.

Man.. day and night difference. Downloaded the Nov 20 0.134 version and I'm back in the 40s. Granted, I'm missing out on some good CPU options but..

<img width="1101" alt="Untitled" src="https://github.com/seerge/g-helper/assets/140649954/614e4ff6-b80f-444d-a55c-14b776743a00">

**Comment by seerge** [comment]
@SynStark can you run latest release now and compare? 

And post screenshots from all settings you have in both, thanks

**Comment by SynStark** [comment]
Sure. Here is 0.134

![134](https://github.com/seerge/g-helper/assets/140649954/ddd59f3d-e61b-4acf-8bc6-ab17fad8d64a)

And here is 0.164

![164](https://github.com/seerge/g-helper/assets/140649954/0140724d-1e5c-414c-9f05-c93760bed250)

Both are with same settings. 

Balanced Mode for CPU
Ultimate Mode for GPU
Best Power Efficiency 
CPU Boost Disable
Power Limit for PL1 80w
Default Fan Curve

But 10c+ difference in temps and difference in fan noise as well.

**Comment by seerge** [comment]
@SynStark ok. I think I know what could be a reason.

Thing is that Strix (G634 / 834) models **require** custom fan curve to be applied in order to make custom power limits work. As in Armoury you simply can't set only power limits, but not fans (you apply both at the same time)

So what was changed in the app that it would also apply custom fan curve as soon as you tick ``Apply Power Limits``

In very old versions (like yours 0.134) it didn't set fans next to power.

---

Can you run a quick benchmark (for example cinebench23) and using HWinfo (or any other similar app) actually check if CPU power limit is working in old version (0.134) ? I.e. if it stays on **80W only ?**

---

And also check this build
[GHelper.zip](https://github.com/seerge/g-helper/files/14836965/GHelper.zip)

**Comment by SynStark** [comment]
@seerge 

I read in Reddit that if PL1 is lower the laptop will use less power in day-to-day stuff like browsing, youtube, moves etc and if PL2 is higher it will pull more power when needed in gaming. Would changing the Power limits or unchecking the box and leave it to default fix that issue?

**Comment by seerge** [comment]
@SynStark yes, unchecking power limit would reset it back to whatever is set by default by manufacturer for Balanced mode on your device 

But I want to understand if custom power limits work when set w/o fan curves on your device :)

**Comment by seerge** [comment]
@SynStark did you had a chance to test build i linked here and test if power limits actually work in old 0.134 ?

**Comment by SynStark** [comment]
@seerge Yes.

In the 0.134 the Apply Power Limits did not work. In Cinebench I was pulling over 120 no matter the 'W' was manually put.

In the 0.164 the Apply Power Limits DID work to whatever I put manually.

In the 0.165 you linked the Apply Power Limits DID work as well.

The thing that worked on all versions was the CPU Boost option. If it was Disabled the W was limited to 40w. 

Can you give me suggestions what would be the best option in that CPU Boost field, as well as if I should use the Power Limits or leave it un-checked at Default?

**Comment by seerge** [comment]
@SynStark 

For boost you can turn it OFF for dekstop use (whatever you use there Silent or Balanced) and ON for Gaming if it's needed. All Boost options except OFF are almost same.

For power limits - its' up to you :) it seems like you "liked" 0.134 where power limits were not working and you were good with that ? so then just use defaults (i.e. dont' check anything).  **I assume that any recent build works fine for you if you don't set custom fan curves / power limits ?**

If you still want to set limits, it really depends on your usage. For desktop or even gaming something like 30-50W is more than enough I think :) For proper CPU intensive tasks you can set higher values. But you clearly don't need 120W PL2 (this is a limit for a first 2 minutes of load) for desktop

**Comment by seerge** [comment]
@SynStark do I understand that this resolved for you now ?

**Comment by SynStark** [comment]
@seerge I would say yes. I have a much better understanding of the program now. Thank you very much for all the help!

**Comment by seerge** [comment]
@SynStark ok. Great

TO summarize your problem - cause you had power limits ``applied`` but not fans, before they did not work (due to specifics of your model series as for most of other devices it is possible to apply power limits w/o fans)

And since it was "fixed" in one of the intermediate releases, your custom power limits finally started working causing difference in behavior :)

Thanks for checking
