### ISSUE TITLE
[Question] Do I need to run Asus Services?

### ISSUE THREAD

**Issue by Astra060** [seerge/g-helper#2361]
I noticed Battery Charging limit won't work unless I have Asus Services Running, is this a problem or me nuking anything about Armory Crate after using this app? When Services are off it's ignored.

**Comment by seerge** [comment]
@Astra060 hello, no. You do not need them for app to work, but it’s up to you to keep them or not.

Since you have ignored issue template and didn’t include any logs or other information it’s impossible to assist you further besides advising to check FAQ related to battery limit

https://github.com/seerge/g-helper/wiki/FAQ#battery-charge-limiter-is-not-working

Thanks
