### ISSUE TITLE
[Question] About Visual Mode

### ISSUE THREAD

**Issue by Niloy-Sarker** [seerge/g-helper#2376]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Why display color tone (warmest/warmer/warm/neutral/cold/colder/coldest) changing asking for administration privilege when choosing 'No' in permission popup still changes color tone?

### How to reproduce the bug?

Change Neutral to any of the option.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14855218/log.txt)

### Device and Model

Tuf 506LH

### Armoury Crate

Uninstalled

### Asus Services

none

### Version

0.164.0

### OS

Win 11 23h2

**Comment by seerge** [comment]
@Niloy-Sarker hello,

On 2 devices where I tested it G14 2022 and 2024 for changing color temperature ``AsusSplendid.exe`` (that app calls to do that) required admin permissions. Or change did not happen.

It's cool that it works w/o admin permissions on your device. It could be because you have Intel iGPU , and drivers there don't require that. But since app doesn't know in advance what kind of situation you have and it asks for admin permissions just to be sure

Thanks
