### ISSUE TITLE
Support for Asus Zephyrus Duo Laptops

### ISSUE THREAD

**Issue by Onotseike** [seerge/g-helper#2407]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I would like to ask for support for dual screen laptops, specially the Asus Zephyrus Duo line of laptops.
Currently the Visual mode only affects the Main display and not the secondary display just abov the keyboard. 

### Describe the solution you'd like

A means of adjusting the visual mode the secondary display

### Describe alternatives you've considered

ScreenXpert. 

### Device and Model

Asus Zephyrus Duo 16 GX650PY

**Comment by seerge** [comment]
@Onotseike hello, does the Visual Mode (or Game Visual from AC) affect second screen when you set it in Armoury Crate ?

**Comment by Riccorbypro** [comment]
Zephyrus Duo 16 2022 (GX650RW) here. GameVisual in Armoury Crate does not seem to affect the lower screen in any noticeable way. Same for the Visual Mode in GHelper.

 I'm intrigued by the mention of ScreenXpert in the OP - I don't see anything relating to colour management in any of the settings menus for the version of ScreenXpert I have on mine (latest according to MyASUS and GHelper).

**Comment by seerge** [comment]
@Riccorbypro that's why I have asked if it works in Armoury or not :)

To set Visual Modes G-Helper just calls ``AsusSplendid`` utility from Asus System Control Interface driver under the hood. And this is exactly same as Armoury does. So if it doesn't affect second screen when you set it in Armoury - then it won't work in G-Helper and it's simply not possible.

**Comment by seerge** [comment]
@Onotseike 
> No it doesn't.

Then it means that Visual Modes can not be set to the second screen (due to the reasons I have explained in a previous comment)

> I think I was trying to explain if a feature to detect dual screen asus laptops was introduced and upon detection settings including but not limited to brightness modification, toggling screen pad on or of via key bindings. 

You already can control screenpad brightness with 
- ``Fn + Shift + F7 / F8`` - Screenpad brightness Down / Up (works only if asus services are stopped, as otherwise they take over hotkeys)
- Dedicated screenpad button (if you have it on your DUO)
- Using custom bindings from ``Extra``

I believe that's enough already :)

Closing as not planned, as Visual modes for second screen are not possible anyway.

Thanks.
