### ISSUE TITLE
Can g-helper has an option that hide the icon of the taskbar like OneDrive?

### ISSUE THREAD

**Issue by LoadLife** [seerge/g-helper#2413]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

when i foucus on g-helper, there always a icon display on the taskbar, I think it's redundant because there has been already a icon in the system tray and the UI also above the system tray.

### Describe the solution you'd like

1.if can provide an option that when i open g-helper from system tray,  don't show a additioal icon on the taskbar? 
2.when i click the desktop or other area and g-helper  lose focus, can auto hide g-helper UI to the system tray like OneDrive's action?
thanks a lot. : ）

### Device and Model

Asus TUF Gaming A16 FA607PV

**Comment by seerge** [comment]
@LoadLife hello,

There is aways an icon for main window and this is absolutely intentional. 

When window is visible G-Helper does some things  like refreshing fan readings / temp readings and battery charge reading. It's all stopped when app is hidden to tray, to save resources. So it's important that user sees that app is actually doing something by seeing it in taskbar.

Also there is some other internal logic connected to that.

So I don't plan to change that, sorry.

Thanks
