### ISSUE TITLE
Slash Lighting "Disable on Lid Close" does not work 

### ISSUE THREAD

**Issue by adelbtw** [seerge/g-helper#2435]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After ticking the "disable on lid close" button on G-Helper, my G14 2024 still has slash lighting when in sleep mode. AC is uninstalled and all all assus processes are stopped. 

### How to reproduce the bug?

Simply closing the lid or clicking the power button.

### Logs

[log copy.txt](https://github.com/seerge/g-helper/files/14971812/log.copy.txt)

### Device and Model

Asus Zephyrus G14 GA403U

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.0165.0

### OS

Windows 11 Home 23H2

**Comment by seerge** [comment]
@adelbtw hello, this is a dublicate [of a same issue](https://github.com/seerge/g-helper/issues/2381) https://github.com/seerge/g-helper/issues/2381

I need someone to actually record what exactly AC sends to a device in order to disable sleeping animation. So if you want - please check original issue for a details

Closing as dublicate
