### ISSUE TITLE
blank updates page

### ISSUE THREAD

**Issue by FluXolo** [seerge/g-helper#2436]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

when clicking the updates tab to check for updates only says " no new updates " and the page is blank and all the drivers are gone. 
![image](https://github.com/seerge/g-helper/assets/74671564/ee8dd632-d3d8-4037-aaa6-fca764485c49)

### How to reproduce the bug?

1. Go to Ghelper 
2. open updates tab.

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14971927/log.txt)

### Device and Model

Asus TUF Gaming A15 FA507NV

### Armoury Crate

Installed

### Asus Services

None

### Version

0.165 & 0.166

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@FluXolo hello, 

It's because G-Helper just takes data from asus API, and apparently it's either just malfunctioning or doesn't have any drivers for your model

https://rog.asus.com/support/webapi/product/GetPDDrivers?website=global&model=FA507NV&cpu=FA507NV&osid=52
https://rog.asus.com/support/webapi/product/GetPDBIOS?website=global&model=FA507NV&cpu=FA507NV

I can't fix anything on the app side, cause data is just not available unfortunately :| 

P.S. Is that your reddit post ? :) cause model name is same
https://www.reddit.com/r/Asustuf/comments/1c3snqa/why_is_my_the_drivers_and_software_in_ghelper_is/

**Comment by seerge** [comment]
@FluXolo actually seems like they changed API a bit .. try this build

[GHelper.zip](https://github.com/seerge/g-helper/files/14972167/GHelper.zip)

**Comment by nathancdy** [comment]
@seerge might be related, my 2024 G14 BIOS section in Updates is blank, but the Drivers and Software section is normal.

**Comment by seerge** [comment]
@nathancdy blank in 0.165 ? or in 0.166 ?

**Comment by nathancdy** [comment]
@seerge 1.65, but also noticed on the ASUS Website on the  Driver Support page for my model it has errors saying 'We don’t currently provide a software utility or drivers for this model.'

**Comment by nathancdy** [comment]
@seerge on 0.166 now, the Updates section is blank entirely.

![image](https://github.com/seerge/g-helper/assets/103626631/1e9cdb00-614e-4d3e-9ddb-72490fa80715)

**Comment by seerge** [comment]
@nathancdy try this one

[GHelper.zip](https://github.com/seerge/g-helper/files/14972338/GHelper.zip)

**Comment by nathancdy** [comment]
@seerge I'll wait until the Drivers section on the support page is fixed before trying that build. For my model, it either says it currently has no drivers for the model or the Drivers section is not there entirely. Pretty sure ASUS is just having API problems at the moment.

**Comment by seerge** [comment]
@nathancdy well .. how does that stop from trying the build ? :| 

There is a good chance they won't fix it for a while ...

**Comment by nathancdy** [comment]
@seerge I just think it's because it's not an error related to GHelper directly but just on the side of ASUS with their API.

I did decide on trying the new build though and the Updates page is back to normal :)

**Comment by FluXolo** [comment]
> @FluXolo hello,
> 
> It's because G-Helper just takes data from asus API, and apparently it's either just malfunctioning or doesn't have any drivers for your model
> 
> https://rog.asus.com/support/webapi/product/GetPDDrivers?website=global&model=FA507NV&cpu=FA507NV&osid=52 https://rog.asus.com/support/webapi/product/GetPDBIOS?website=global&model=FA507NV&cpu=FA507NV
> 
> I can't fix anything on the app side, cause data is just not available unfortunately :|
> 
> P.S. Is that your reddit post ? :) cause model name is same https://www.reddit.com/r/Asustuf/comments/1c3snqa/why_is_my_the_drivers_and_software_in_ghelper_is/

hey thanks for the fast answer, that is not my reddit post just a coincidence.
Just tried the new build and the updates show after refreshing a couple times or sometimes instantly, thx again :)

**Comment by seerge** [comment]
@FluXolo ok, great.

As I have mentioned above, it seem to be some issues with Asus API. Cause it seem like event heir website sometimes doesn't return drivers / BIOS updates and sometimes does.

I hope they will fix that (as otherwise even website is malfunctioning)

Current tweak that I did should help as a fallback scenario. Closing as completed.
