### ISSUE TITLE
Updates tab do not show other updates after updating to 0.165

### ISSUE THREAD

**Issue by slidjet** [seerge/g-helper#2440]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I udated to 0.165 and i am unable to see any other driver updates other than bios updates from g helper. Is there something i can do to get the updates tab back again? I also disabled somethings in task scheduler, is there any setting in task scheduler that was necessary for that to work?
![Screenshot 2024-04-16 030235](https://github.com/seerge/g-helper/assets/167120462/5f1bd8e8-7db2-46b0-82ee-373434cda6ea)
![image](https://github.com/seerge/g-helper/assets/167120462/f5f131b4-1c0c-4e98-a6b2-9e3b9f879dae)

### How to reproduce the bug?

Clicking the updates tab

### Logs

[log.txt](https://github.com/seerge/g-helper/files/14982282/log.txt)

### Device and Model

Asus Zepherus G14 G402XY

### Armoury Crate

Installed

### Asus Services

None

### Version

0.165

### OS

Windows 11 Pro

**Comment by seerge** [comment]
@slidjet hello, it's not because of updating to 0.165, but because asus servers have issues now, and doesn't always return data (their website is also not working properly now)

Please check this issue for more details https://github.com/seerge/g-helper/issues/2436 and try 0.166 where i have added a fallback method to get drivers list

Thanks. Closing as dublicate
