### ISSUE TITLE
Touchpad toggle on when in laptop mode (ROG Flow x16 - 2 in 1)

### ISSUE THREAD

**Issue by IncognitoFawkes** [seerge/g-helper#2455]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Sometimes, when my laptops wakes up from having been shut down in tablet mode, the touchpad doesn't turn on, and I need to manually turn it on. I don't have this same issue with the keyboard, which also turns off in tablet mode. Sometimes, the touchpad doesn't turn on for no reason at all, even when it was shut down in laptop mode.

### Describe the solution you'd like

A service G-Helper run that turns the touchpad on if my laptop is in Laptop mode.

### Device and Model

Asus ROG Flow x16 (2022) - RTX 3060 version

**Comment by seerge** [comment]
@IncognitoFawkes hello,

App already automatically toggles touchpad ON and OFF every time it gets notified about tablet mode change on X13/X16

Since you didn't include logs, I don't know what exactly happens on your device.

You can completely disable this automatic toggle as explained here
https://github.com/seerge/g-helper/wiki/Power-user-settings#disable-tablet-mode-on-x13x16
