### ISSUE TITLE
Dynamic lighting support

### ISSUE THREAD

**Issue by riyanshlunia** [seerge/g-helper#2530]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not exactly but it would be a nice feature to use on native windows settings 

### Describe the solution you'd like

https://www.asus.com/support/faq/1051416/

I was thinking maybe we could implement something like the above article which could help us control the windows dynamic lighting from the settings app

### Describe alternatives you've considered

Using the ghelper lighting control 

### Device and Model

 ASUS TUF F15 FX507ZE

### Additional information.

None

**Comment by seerge** [comment]
@riyanshlunia hello,

If your device already supports DynamicLighting it will be possible to control it in corresponding setting page in windows already (it happens on hardware/driver level)

If it doesn't support that (which is most probably the case since you have older model) - then it's not possible.

It's not something that G-Helper can do

Thanks.
