### ISSUE TITLE
Temp going above max temp on cpu

### ISSUE THREAD

**Issue by dvdganon** [seerge/g-helper#2540]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Temp going above max temp on cpu

### How to reproduce the bug?

1. Give lower max temp for cpu
2. Run time spy or heavy game
![FB_IMG_1714720945978](https://github.com/seerge/g-helper/assets/33452960/e0b26d06-3d8d-4808-9134-2814b62935c7)

### Logs

See image

### Device and Model

Asus zephyrus duo 16 2023 win11

### Armoury Crate

Uninstalled

### OS

Win 11

**Comment by seerge** [comment]
@dvdganon hello,

Temp limit slider is a "Throttle" setting for your CPU. It's supposed to tell it when to slow down (lower it's power) when it hits that. If it doesn't drop power fast enough - it will still heat up of course, as you can't change laws of physics.

I see that you have a VERY HIGH power limit set to 100w (!). I would advice just to set something like 40W-50W and test your game / app with that setting. You will get similar effect as limiting temperature.

Also keep in mind, that if you have underlying hardware issues (like bad liquid metal application, etc), limiting power won't do much.

Since you have ignored issue template and didn't include logs,  I can't assist further.

Thanks and good luck
