### ISSUE TITLE
Clamshell mode makes Projection mode switch to "Extend" when re-opening lid, would be cool if we could choose what it does

### ISSUE THREAD

**Issue by ywaltjs** [seerge/g-helper#2566]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Mostly in the title. When Clamshell mode is active in Extra settings, and when you have "Second Screen Only" as Projection Mode, when you reopen the lid, it automatically switches to "Extend" mode.

### Describe the solution you'd like

It would be cool for us to be able to decide what Projection Mode gets selected after re-opening the lid. I understand it's a feature already, but more customisation would be even more practical and cooler. Something like a dropdown menu next to the check box.

### Device and Model

ASUS TUF F17 GAMING

**Comment by seerge** [comment]
@ywaltjs hello,

G-Helper doesn't do that. What Clasmshell checkbox does is turning off "Sleep" on "Lid Close" setting in Control Panel when you are plugged in and have external monitor connected. That's it. Nothing else.

![Screenshot 2024-05-09 110207](https://github.com/seerge/g-helper/assets/5920850/9bf80bc8-dc98-48af-847d-11960e933edd)

---

But your observation seem to be correct. 

If you have "Lid Close" setting set to "Do Nothing" in Control Panel (**even if you set it manually by hand**) after you open lid windows will set Projection mode to Extend no matter what. It happens with or without G-Helper even running (as it doesn't depend on it)

It could be some hiccup caused by recent windows updates.

To my best knowledge, you can't change Projection mode programmatically anyhow. So you can't override it in the app after.

Therefore I just suggest to accept it as another "feature" of our beloved Microsoft Windows :))

Thanks

**Comment by seerge** [comment]
P.S. I even tried setting this hidden option in power plan to keep screen off, but it doesn't make any differnce
![Screenshot 2024-05-09 111348](https://github.com/seerge/g-helper/assets/5920850/6205ea85-6a91-4869-9ac8-b27cb7149d04)

Every time lid is open - windows just re-initializes all displays and resets projection mode
