### ISSUE TITLE
Brightness adjustment on internal panel not working after Optimized mode switch

### ISSUE THREAD

**Issue by jasbur** [seerge/g-helper#2570]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Internal panel brightness is sometimes unresponsive when switching GPU from Eco to Standard mode. The brightness adjustment UI still presents, but has no actual effect on panel brightness while in Standard mode.

Any adjustments that you have made will be visible after switching back to Eco mode though. For instance, if I switch to Standard mode while the panel is at 50% brightness, adjust the brightness level to 100% (with no change visible yet), then switch back to Eco mode the panel will display at 100% brightness.

Activating the `Enable GPU on shutdown` option seems to have no effect.

### How to reproduce the bug?

1. Start in Standard GPU mode (brightness is working)
2. Switch to Eco GPU mode (brightness is working)
3. Switch to Standard GPU mode (brightness is not working)
4. Internal panel brightness is unresponsive in Standard mode until reboot

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15278034/log.txt)

### Device and Model

Asus ROG Zephyrus M16 GU604VI

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.170.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@jasbur hello, G-Helper is not able and not controlling brightness directly (it can just emit standard windows media-keys telling system to change brightness).

If even adjusting brightness in windows UI doesn't have effect, it's probably still due to this know issue with nvidia driver https://github.com/seerge/g-helper/discussions/1042

Even if you had ``Enable GPU on shutdown`` checked, it could be that your device still managed to shut down w/o doing that (for example by going into sleep and then hibernatng)

From the log i see that you have clearly booted in Eco mode at least once
```

**Comment by seerge** [comment]
@jasbur does restarting help ?

**Comment by jasbur** [comment]
Yes, rebooting fixes it. So, does the NVIDIA driver bug occur when booting the system while in Eco mode?

**Comment by seerge** [comment]
@jasbur yes, and checking Enable GPU on shut down should prevent that (but it won’t magically fix brightness if it’s already bugged, you need to reboot for that) :)
