### ISSUE TITLE
Can we have a floating-window at the top of the screen?

### ISSUE THREAD

**Issue by h4ck4t** [seerge/g-helper#2583]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

It's not about a problem.

### Describe the solution you'd like

Hi,
Is it possible to develop a floating window on top of the screen, so that we can see the discharging rate, mode, fps, etc on real time?
Thank you!

### Device and Model

Zephyrus G14 2023

**Comment by seerge** [comment]
@h4ck4t hello,

I don't plan adding any monitoring overlays in the app for the time being, cause it won't be visible on top of many full-screen games or apps due to windows permissions 

And there is a lot of nice apps that do that already like Afterburer/Rivatuner overlay or HWINfo overlay

Thanks.

**Comment by seerge** [comment]
@veristagnum hello,

I have found a way to show both overlay and OSD over old games.

Get latest (pre)release https://github.com/seerge/g-helper/releases 

And you need to place GHelper.exe into `C:\Program Files` folder. It's such weird windows requirement.

Thanks
