### ISSUE TITLE
Toggle indicator LEDs

### ISSUE THREAD

**Issue by smm-h** [seerge/g-helper#2584]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

While working in the dark, the four indicator LEDs in the top middle of my keyboard, just below the screen, and one LED on the top right of my keyboard, are very distracting and annoying, especially for a photosensitive person like me.

### Describe the solution you'd like

Please add options to temporarily disable these LEDs. Thank you.

### Describe alternatives you've considered

The only workaround for this is just putting a piece of tape on the LEDs. This is however very ugly and doesn't even work for the shutdown button LED (because I can't just push it to adjust the tape while my laptop is running).

### Device and Model

Asus TUF A15

### Additional information.

![led](https://github.com/seerge/g-helper/assets/8294988/6ec62f5b-09c6-49c0-a7b6-aa4505c6f670)

**Comment by seerge** [comment]
@smm-h hello, 

Unfortunately that's not possible.

For devices that can do that (i.e. Scar 2024) you can already toggle this leds under ``Extra``. If you don't see corresponding checkbox there, it means your device doesn't support toggling indicator leds.

Thanks.

**Comment by Valour549** [comment]
@seerge I have the Scar 18 and your app works wonderfully in toggling the Status indicator LEDs (though I still have to use Armory Crate because I got some ASUS keyboards). I don't see any options in BIOS or Armory Crate but clearly the option is there.

1) Could you share how this was done? I want to make a script (or two scripts) that I can use to automate toggling the LEDs when the laptop turns on/off in combination with Task Scheduler. You see I would like them to be on when the laptop is on, and to be off when the laptop turns off. I leave on laptop plugged in all the time, and when it is off the battery LED indicator is still white, which annoys me when I sleep lol.

2) I also noticed that the toggle affects [all four indicators](https://i.imgur.com/0IYJ8OR.jpeg) including the power button, is it possible to leave the power button on and only toggle the other three indicators?

3) For the keyboard/logo/lightbar/lid backlight, if "Shutdown" is ticked, does that mean they will all be on even when the laptop is shut down? Because I have it ticked and they all turn off when the laptop turns off.

Thank you!
