### ISSUE TITLE
Gpu temperature limit is not working

### ISSUE THREAD

**Issue by MNDL-27** [seerge/g-helper#2613]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

So i have set my gpu temperature target to 80C but as you see on the photo its reaching higher. max temp recorded 89C

![Screenshot 2024-05-20 110653](https://github.com/seerge/g-helper/assets/96876555/4ec08944-2c81-4b91-8156-6ab8d4834488)
![Screenshot 2024-05-20 110713](https://github.com/seerge/g-helper/assets/96876555/511b00bb-55eb-43a1-ab97-62bf968840d1)

### How to reproduce the bug?

1. Fan Power
2. GPU
3. Temperature Target

### Logs

[log.txt](https://github.com/seerge/g-helper/files/15372923/log.txt)

### Device and Model

Asus ROG STRIX G814JZ

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.170

### OS

Windows 11 Pro 23H2

**Comment by seerge** [comment]
@MNDL-27 hello,

Temp target is just a setting on a device, that is supposed to tell nvidia GPU to drop it's power in order to maintain temperature lower than target. But in a combined loads when there is a lot of heat coming from CPU as well, it can still heat up - there is no magic here :)

- Can run HWinfo and check what does it show as GPU temp targer / limit (it has a dedicated reading for a limit) ?
- Does temp limit work with exactly same settings if you would set in AC ?

Thanks

**Comment by seerge** [comment]
@MNDL-27 any update on the matter?

**Comment by MNDL-27** [comment]
> @MNDL-27 any update on the matter?

Sorry for the t late reply. I am just traveling now so didn't get the chance to do so.
But I checked the hwinfo but couldn't find anything similar

**Comment by seerge** [comment]
@MNDL-27 it is there :) you need to look more careful. 

Or you can use ``nvidia-smi -q output`` for same metric.

Anyway as I have answered, G-Helper just uses asus endpoint to set it same as AC does. Rest is up to BIOS and Drivers how to handle it.

**Comment by seerge** [comment]
Closed as abandoned due lack of response
