### ISSUE TITLE
G-helper silent startup

### ISSUE THREAD

**Issue by martinville** [seerge/g-helper#2661]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not related to a problem just a nice to have

### Describe the solution you'd like

It would be nice to have a setting that will start G-Helper in silent mode so that you done have to close it when it starts up.
Perhaps a check box in the "Extras" screen. Please not on the main screen :-)

### Device and Model

ROG Ally Z1 Extreme

**Comment by seerge** [comment]
@martinville hello, it already has that.

When app starts from startup task (i.e. with windows) it doesn't show main window.

When you open it by clicking on exe (or a shortcut) - it will open main window.

Criteria for that - if working directory where app is started is same as exe (it assumes it's started manually) and shows window. Otherwise - it starts silently. 

If you want to force that - you can create windows shortcut, and just set different working directory there.

Thanks.
