### ISSUE TITLE
Add random color to keyboard LED in Star mode

### ISSUE THREAD

**Issue by Louis1501** [seerge/g-helper#2730]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Please add random color to the keyboard LED in Star mode. I would love for my keyboard to be colorful, it can be installed in Armory Crate. but in Ghelper there is no such option, nice if you listen to this

### Describe the solution you'd like

Please add random color to the keyboard LED in Star mode

### Device and Model

G713RW

### Additional information.

![Screenshot 2024-06-14 105725](https://github.com/seerge/g-helper/assets/172722934/1d305312-b0b2-40c3-959e-46313c8c887b)

**Comment by seerge** [comment]
@Louis1501 hello, 

Application lists all backlight modes that your device supports on hardware / firmware level (+ Ambient). There is no such thing as "random" color for the animation in firmware settings. 

If it existed in AC - it means AC was imitating that mode on software level, by manually setting backlight for each key few times a second. It's quite resource heavy thing and I don't plan to add it to the app in order to keep it simple and light. 

Thanks and sorry.
