### ISSUE TITLE
Visual mode bug

### ISSUE THREAD

**Issue by Sebastian-m-1408** [seerge/g-helper#2743]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I recently installed ghelper and tried a color filter that was the "warmest", what happened is that I wanted to return to the default mode, the screen continues to be very warm, any solution?

### How to reproduce the bug?

G helper

### Logs

1

### Device and Model

Asus ROG Strix G16

### Armoury Crate

Uninstalled

### Version

0.176.0

**Comment by seerge** [comment]
@Sebastian-m-1408 hello,

If you will set Neutral color temp - it would be default one. 

Please keep in mind that G-Helper (same as Armoury) just launches an ``AsusSplendid`` utility from Asus System Control Interface package to set all Visual mode / color temp / gamut. How exactly it's handled depends on this utility.

Sometimes even default colors set by ``AsusSplendid`` may be different, you can just reset them under Intel GPU settings on your device.

Since you have ignored issue template **and didn't provide log**, I can't assist further.

Thanks
