### ISSUE TITLE
GPU Eco Mode still can be activated if the NVIDIA Laptop display mode is set into NVIDIA GPU only, which it is prevented in original Armoury Crate software

### ISSUE THREAD

**Issue by ichigayamate** [seerge/g-helper#2764]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

My laptop has NVIDIA Advanced Optimus. if I change the Laptop display mode in my NVIDIA Control Panel into NVIDIA GPU only, then switch GPU mode into iGPU only (Eco), it will switch into iGPU mode. Meanwhile in Armoury Crate, switching into eco mode (iGPU only) while Laptop display mode into NVIDIA GPU only will prevent the GPU Mode into Eco mode.

### How to reproduce the bug?

1. Open NVIDIA Control Panel
2. Click manage display mode
3. Switch to NVIDIA GPU only
4. Open GHelper
5. Select GPU Mode into Eco (iGPU only)

Expected: The GPU Mode will be prevented to switch into Eco mode, and a warning message will popup (see additional information)
Reality: The GPU Mode is still switched in iGPU Mode

### Logs

[log.txt](https://github.com/user-attachments/files/15936689/log.txt)

### Device and Model

Asus ROG Zephyrus G16 GU603VV

### Additional information.

In the source code there is a string of code that prevents GPU Mode from switching. My laptop has Advanced Optimus but it seems it did not appear when GPU Mode is switched into Eco mode while NVIDIA Display Mode is set into NVIDIA GPU only

```
<data name="EnableOptimusText" xml:space="preserve">
    <value>Disabling the dGPU by going into Eco mode while Display Mode in NVIDIA Control Panel is not set to Optimus might cause problems with brightness controls until after the next reboot. 

Do you still want to continue?</value>
  </data>
  <data name="EnableOptimusTitle" xml:space="preserve">
    <value>NVIDIA Display Mode is not set to Optimus</value>
  </data>
```

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.176

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ichigayamate hello, 

You can still disable dGPU even if NVIDIA Control Panel is set to Nvidia GPU only :) It works fine as that as well. 

So I don't want to set extra barriers here.

The translation string that you see is from some old tweak where I suspected Optimus preventing Eco from working, but later on it turned out to be something absolutely different . Namely this - https://github.com/seerge/g-helper/discussions/1042

**Comment by ichigayamate** [comment]
Okay, thanks for the information

**Comment by ichigayamate** [comment]
Okay thanks for the information.

But if I shut down my laptop while in eco mode in GPU Mode, will my GPU Mode is switched into Standard Mode on the next boot?

**Comment by seerge** [comment]
@ichigayamate if you have ``Optimized`` mode - it will either enable or disable dGPU depending if you are plugged in or not.

Otherwise it will boot in ``Standard`` (assuming you have ``Enable GPU on Shutdown`` checked). But keep in mind, that not all devices are affected by that issue i linked. For example G14 / G16 2024 can boot in ``Eco`` and still behave absolutely normally after.

If you want to enforce Eco mode even GPU was enabled on shutdown, you can do that via config 
https://github.com/seerge/g-helper/wiki/Power-user-settings#force-last-used-gpu-mode-ie-standard-or-eco-on-app-start--restart

**Comment by ichigayamate** [comment]
Okay thanks for the information. I will close this thread
