### ISSUE TITLE
a user define feature for color temperature

### ISSUE THREAD

**Issue by AayushV12** [seerge/g-helper#2767]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

can we get a rgb channel user define for color temperature on display

### Describe the solution you'd like

can we get a rgb channel user define for color temperature on display

### Device and Model

asus rog strix g15 g513rc hn062w

**Comment by Minemetero** [comment]
I want to control each rgb keyboard because it is cool. Something like Razer's keyboard. You can control every key; it's so cool. Also something llike color wave.
https://www.google.com/search?client=opera-gx&hs=ocJ&sca_esv=d3364c1a04ef5487&sca_upv=1&q=razer+blade+rgb+keyboard&udm=2&fbs=AEQNm0DYVld7NGDZ8Pi819Yg8r6em07j6rW9d2jUMtr8MB7htoxbI0iAKNRPykigVf3e9aputkbr8jzmN5LYbANOqrq5HYnx4MjtyMxZ94LvgeHWmGBcuWUoydKfNaoB5JMdZlMtXmg2De2y5O7nn-eTbNdYHsRiT1RQ-pB6qp3ejXJ5VpdCk5NA1Jug5hVR16L7F-A1C1p-4xpfp7qj2HsGNaipPZQOiw&sa=X&ved=2ahUKEwjMv6a4nfOGAxUXia8BHXfmCdYQtKgLegQIDBAB&biw=1666&bih=996&dpr=1.5#vhid=m46urAmmSpB3FM&vssid=mosaic
Each key is showing a different color...

**Comment by Minemetero** [comment]
But ROG, it was just one color at a time.
