### ISSUE TITLE
Applications crash when automatically switching to Eco Mode

### ISSUE THREAD

**Issue by canlimimar** [seerge/g-helper#2814]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

When applications using dGPU (Archicad, Twinmotion etc.) are running and the power suddenly goes out, the system switches to iGPU and running applications crash and give an error. 

### Describe the solution you'd like

Can an additional feature be added to prevent the system from going into eco mode while applications that use dGPU are running?

### Device and Model

ASUS Rog Strix G814JZ

**Comment by seerge** [comment]
@canlimimar hello, 

I assume you speak about ``Optimized`` GPU mode ? It already checks if GPU is in use (current threshold is 10%) and doesn't disable GPU in that case.

https://github.com/seerge/g-helper/blob/ce765376879071c923a1cf3204d9ee7c477bb8a3/app/HardwareControl.cs#L236

I can imagine in your situation usage is lower ? Can you upload log from ``%appdata%\GHelper`` ? 

If you have unstable power connection - I would just advice to use ``Standard`` mode :)

**Comment by canlimimar** [comment]
Thanks for your answer. I unplugged it and tried again. Yes, it happened in optimized mode when the apps were in the background and the power was gone. At that time usage was 1%.

When I was using Armory Crate, it would not switch to eco mode until the applications were completely closed. That's why I wanted to write.

[log.txt](https://github.com/user-attachments/files/16120174/log.txt)

**Comment by seerge** [comment]
@canlimimar 

Right, this time usage was 1%
```
7.07.2024 20:16:19: GPU usage: NVIDIA GeForce RTX 4080 Laptop GPU 1%
``` 

It is possible to get a list of apps that "use" GPU from Nvidia Driver (like AC), but this list will also contain such apps like browser or some windows processes. Those survive GPU shutdown w/o any problems. 

And G-Helper absolutely intentionally skips them. As otherwise ``Optimized`` mode will almost never work, which happens to me all the time with AC :)

Unfortunately there is no way to separate apps that really depend on GPU (like Archicad) from Chrome or Edge except looking at real GPU usage.

My advice would be just using ``Standard`` mode if you have some unreliable power that can go off + you use those apps.
