### ISSUE TITLE
G15 Fn lock Issue

### ISSUE THREAD

**Issue by Kevinwzwu6** [seerge/g-helper#2822]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After turning on Fn lock, the F12 function(airplane mode) does not work properly. Moreover, while pressing F2 and F3(keyboard brightness up and down), although the brightness changed accordingly, there was no indicator for the change(see screenshot for the indicator shown while pressing fn+f2). 
![image](https://github.com/seerge/g-helper/assets/158231894/79049842-3f57-443e-a7fc-c2a45fae9485)

### How to reproduce the bug?

press f2 or f3
press f12

### Logs

[log.txt](https://github.com/user-attachments/files/16139865/log.txt)

### Device and Model

Asus Rog Zephyrus G15 GA503QR

### Armoury Crate

Uninstalled

### Version

0.178.0

**Comment by seerge** [comment]
@Kevinwzwu6 hello,

- `` F12`` is reserved by windows itself, and therefore it's impossible to bind it in the app. So it's absolutely intentional
- ``F2/F3`` - you need to stop asus services (from ``Extra``), or otherwise they will handle those hotkeys. Then you will see a notification from G-Helper

Thanks
