### ISSUE TITLE
GPU mode switches to standard after after hibernating

### ISSUE THREAD

**Issue by lgarlati** [seerge/g-helper#2833]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

If the GPU mode is set to eco (iGPU only) and the computer is hibernated, upon waking the mode is set to standard. This does not occur with sleep, only hibernate. 

### How to reproduce the bug?

1. set mode to eco
2. hibernate the machine
3. wait for it to finish...
4. wake it
5. see gpu mode is now standard

### Logs

[log.txt](https://github.com/user-attachments/files/16196091/log.txt)

### Device and Model

Asus Zephyrus G16 GU605MZ

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.179

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@lgarlati hello,

Because you have "Enable GPU on shutdown" checked under `Extra`, it turns it on to prevent this issue https://github.com/seerge/g-helper/discussions/1042

```
7/11/2024 9:09:24 PM: Forcing Standard Mode on shutdown / hibernation
7/11/2024 9:09:31 PM: GPUEco = 0 : OK
```

Since you have GU605MZ  2024 model, i think it doesn't suffer from that brightness thing at all, so you may just uncheck it and try if a scenario explained is reproducible. 

Alternatively you can add

``"gpu_mode_force_set" : 1,`` to config, and app will force last used mode on start / restart

https://github.com/seerge/g-helper/wiki/Power-user-settings#force-last-used-gpu-mode-ie-standard-or-eco-on-app-start--restart

Thanks
