### ISSUE TITLE
Asus Zephyrus g16 2024 GU605MI Fans wont go max

### ISSUE THREAD

**Issue by ILikeLight** [seerge/g-helper#2838]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

the fans on my laptop wont go maximum

this is pretty annoying considering that the CPU is almost always thermal throttling at 95 degrees Celsius

### How to reproduce the bug?

put the fans on max in the software but then the software reports that the fans stay at like 6100 rpm but the max is 6600
(in the second screenshot i show how i put the fans to max)

### Logs

[log.txt](https://github.com/user-attachments/files/16199863/log.txt)

### Device and Model

Asus Zephyrus g16 2024 GU605MI

### Additional information.

![image](https://github.com/user-attachments/assets/e9e4e0bb-b483-4f1b-a726-256ed2180aff)
![image](https://github.com/user-attachments/assets/ec0663dd-3d44-4581-b00b-1e5303a28122)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.179.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@ILikeLight hello, 

[Fans are controlled by BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds) , even when you use a custom fan curve.

If you set fan curve to 100% and they go to 6100-6200RPM - it sounds about right as a maximum speed for your device, so that's normal.

If you don't like how BIOS controls your fans you can try [Experimental build with manual fan control.](https://github.com/seerge/g-helper/discussions/2272)

Thanks.

**Comment by ILikeLight** [comment]
thank you
