### ISSUE TITLE
In G16 2023 models and some other G16s, The keyboard becomes unresponsive randomly when it's set to Ambient color mode

### ISSUE THREAD

**Issue by Tx-3011** [seerge/g-helper#2849]
To make it back responsive, I either need to set the laptop to sleep and wake it using any of the keys or wait for 3-4 minutes

**Comment by seerge** [comment]
@Tx-3011 hello, please fill the [**issue template properly**](https://github.com/seerge/g-helper/issues/new?assignees=&labels=&projects=&template=bug_report.yml), and include app log and other requested information so I can assist you further.

As for your question - some M16 and G16 have a firmware issue with keyboards, that when it is set to change color to often - it can become unresponsive. It can be triggered by pretty much any AuraSync mode in Armoury or by Ambient mode here (cause it by definition changes color)

Closed due to the lack of info and wrong template used
