### ISSUE TITLE
CCL, CCO and MCO values get applied to base profiles

### ISSUE THREAD

**Issue by deon10** [seerge/g-helper#2929]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Core Clock Limit, Core Clock Offset, and Memory Clock Offset dont switch back to their values when i click back on the default three profile (Silent/Balanced/Turbo)

They stay the same as the ones i put on the custom profile i created

### How to reproduce the bug?

Let's say i create a new profile with different Core Clock Limit, Core Clock Offset, and Memory Clock Offset

When i move back to the normal Silent/Balanced/Turbo profiles, GPU Power and Dynamic Boost change, but CCL CCO and MCO stay the same as those i put in the custom profile

Even if i click on Factory Defaults, and it switches to the factory values... If i switch to the custom profile then move back to the default ones, it occurs again

### Logs

[log.txt](https://github.com/user-attachments/files/16501717/log.txt)

### Device and Model

Asus Zephyrus G16  GU506MY

### Additional information.

https://github.com/user-attachments/assets/ada2496c-309e-48c3-b661-d262bb79c843

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.181.0 (But same problem in previous version)

### OS

Windows 11, Latest non-insider update

**Comment by seerge** [comment]
@deon10 hello, this is absolutely intentional behavior.

By default G-Helper for any mode wouldn't touch Clock limit and Clock offsets, cause they could be changed by other app (for example Afterburner, etc). So their "default" behavior - is just to read and show current value from nvidia driver.

If you would drag any of those sliders (even to 0 offset), it would save that for current mode, and then set every time you select this mode.

When you click `Factory Defaults` it resets saved values back to "default".

So just drag sliders to 0/0 for Balanced if you want them to become 0/0 again :)

Thanks

**Comment by seerge** [comment]
@deon10 does dragging sliders to 0/0 resolve your problem ?
