### ISSUE TITLE
CPU Turbo boost option per performance mode

### ISSUE THREAD

**Issue by hkaancaliskan** [seerge/g-helper#31]
CPU turbo boost option can be selected per performance mode
e.g. Set CPU turbo boost as ON while on Turbo/Performance and set it as OFF while on Silent

**Comment by hkaancaliskan** [comment]
Side note: Looks like you forgot to set gpuTemp
https://github.com/seerge/g-helper/blob/28aeeb7d5778f968215c2f44132ec339de952515/Settings.cs#L346-L356

**Comment by seerge** [comment]
1. Turbo boost is part of windows power plans, and it's against whole logic to constantly switch it (app has a checkbox for convenience). If you extensively use power plans features - you can add more power plans :)

2. I have (temporarily) removed GPU sensor (not "forgot"), because before i was using a heavy library to read all that data, and now - i have found a way to do it natively for all sensors except GPU. As soon as I will find a GPU sensor readings there - i'll put it back.
