### ISSUE TITLE
Battery Charge limit not working consistently on new verision

### ISSUE THREAD

**Issue by googlme123** [seerge/g-helper#3138]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

for some reason on the v0.190 the battery bar keeps shifting back to 80% from 60% even though I tried everything in Troubleshooting. Older v.187 works fine though and actually gets set have reverted back to v.187 for now but unsure what could be causing this.

### How to reproduce the bug?

click on battery limit bar and set to 60% will jump up to 80%

### Logs

[log.txt](https://github.com/user-attachments/files/17066178/log.txt)

### Device and Model

ASUS TUF F15 2022

### Armoury Crate

Installed

**Comment by seerge** [comment]
@googlme123 hello, 

Thanks for spotting! 

I changed UI in a way - that if you set a limit to 85% - it would jump to 80% (as a closest value) instead of jumping to 100% as it was before. But as a side effect, 60% was also jumping to 80% :)

Try this build, it should behave correctly
[GHelper.zip](https://github.com/user-attachments/files/17066782/GHelper.zip)
