### ISSUE TITLE
Extra > Asus Services Running

### ISSUE THREAD

**Issue by Arise** [seerge/g-helper#3147]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

G Helper shows in light blue/red color this text: Asus Services Running: 0 or some other number.

### Describe the solution you'd like

I would like to have a list with those services that are started and would be nice to know what each does (at least a summary/short description/or a link where we can learn more about), eventually which one we can individually turn on/off.

### Device and Model

Asus ROG Strix G733

**Comment by seerge** [comment]
@Arise hello, I'm not Asus so I can't speak for what they do :) G-Helper offers a simple solution to suspend all that (to prevent from interfering) or run back again.

I don't see any point in listing all services in the app, and letting to toggle it one by one individually as it will only raise a wave of a strange questions instead of keeping things simple.

Thanks
