### ISSUE TITLE
Less frequent reporting in event viewer.

### ISSUE THREAD

**Issue by 10011968** [seerge/g-helper#3168]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Service Control Manager reports every 30s that GHelper was installed as a service, filling my event log with a lot ot unncessary entries. 
![image](https://github.com/user-attachments/assets/7a0a64a3-418a-413a-a4df-76bf545f8e42)

### Describe the solution you'd like

Report once and only in case of service failure/stop. 

### Device and Model

Asus Rog Strix Scar g17

**Comment by seerge** [comment]
@10011968 hello,

It's not G-Helper installing itself as a service (it's not a service at all, it's a portable app at all).

This events are created by windows automatically because you either use undervolting feature or set a temp limit from `Advanced` tab. That in turn uses [winring.sys driver](https://github.com/seerge/g-helper/wiki/FAQ#whats-the-role-of-winring-file).

In particular temp limit resets at random (by AMD driver), so app re-applies it every 30 seconds. I can imagine windows registers each call as info-event. I can't do anything about that.

You can either stop applying a temp limit or undervolting, or just keep it as is :)

Thanks.

**Comment by 10011968** [comment]
@seerge Thanks for the super fast reply. 
Indeed I use the advanced tab to set cpu temp limit and undervolting. 
Will try to set the temp at the same level as amd driver to check if that cool down reporting.

**Comment by seerge** [comment]
@10011968 it's not about setting temp limit to other level. If you choose to set temp limit - G-Helper will re-apply it every 30 seconds (cause otherwise it just stops working at random).

If you don't want events in event viewer - you need stop using temp limit at all. You can compensate that with just limiting your CPU power for example as it has pretty much same effect.

**Comment by seerge** [comment]
@10011968 Hello, [latest app release](https://github.com/seerge/g-helper/releases) includes new AMD CPU undervolting and temp limits using PawnIO driver instead of Wirning. And since PawnIO driver always stays installed, it should not trigger events at all in the event viewer.

I suggest to test it and [comment if it works for you](https://github.com/seerge/g-helper/discussions/5210).

Thanks!
