### ISSUE TITLE
OLED Burn-in Prevention

### ISSUE THREAD

**Issue by spike0en** [seerge/g-helper#3201]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Hello @seerge. Firstly, a huge thanks for making this wonderful tool. I was wondering if an additional OLED burn-in prevention feature can be implemented directly into ghelper. 

Thank you for considering this request, and keep up the great work!

### Describe the solution you'd like

[Here](https://github.com/Marko19907/OLEDShift) is a relevant project for reference. A similar or better implementation would be great!

### Device and Model

Asus Zephyrus G16

**Comment by spike0en** [comment]
I have another question, and I'm not sure if I should open a new thread. According to the settings shown below, the backlit keyboard lights up when I try to boot my device initially, but it turns off after I log into the system, which is expected behavior.


![image](https://github.com/user-attachments/assets/91ecb0ac-fcd5-46ae-9a71-cd3868ae73cf)

However, if I turn off all the options as shown below, the keyboard won’t light up during startup, which is fine, but it also makes the function + backlight up/down keys non-functional until I turn on the awake option.


![image](https://github.com/user-attachments/assets/8aa2fa5d-7bfb-46f0-83ab-637ceef858a2)

Is it possible to prevent the keyboard from lighting up during power on while also preserving the functionality of toggling the brightness with the function + backlight keys after I log into the system?

**Comment by seerge** [comment]
@spike0en hello,

I'm not a big fan of overloading app with features you can achieve somehow else. Especially since Armoury Crate also don't move windows as the [project you linked](https://github.com/Marko19907/OLEDShift). I personally usually have windows maximized so that won't give any benefits. But you can use that app if you want of course next to G-Helper.

As "Oled fetures" Armoury offers only options to make Taskbar transparent or auto-hide it. Both of them can be simply toggled in windows settings directly as well.

---

As for your backlight question. Backlight toggles under `Extra` are separate from backlight brightness (they also exist in AC). And when backlight is turned OFF completely - brightness won't work :) This is how it works on firmware level.
