### ISSUE TITLE
rog xg mobile not activating 

### ISSUE THREAD

**Issue by NIKHITH-DEV** [seerge/g-helper#3226]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

i cant run rog xg mobile and when activated it wont use the xg mobile it keeps using the igpu in any mode 

### How to reproduce the bug?

i dont know

### Logs

i uninstalled g helper and installed armory crate cause I want to use the xg mobile 

### Device and Model

asus rog flow x13 

### Armoury Crate

Uninstalled

### Asus Services

only security services are still active

### Version

latest as of 05-october-2024

### OS

windows 11 64bit

**Comment by seerge** [comment]
> I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

@NIKHITH-DEV hello, since you demonstratively have **ignored issue template and didn't show any logs** I'm unable to help you. I'm not able to read minds and remotely say what exactly is happening on your device.


If you will change your mind - feel free to post logs and clearly explain your problem. Thanks.
