### ISSUE TITLE
Linking NVIDIA Services to Eco or Ultimate Mode

### ISSUE THREAD

**Issue by IncognitoFawkes** [seerge/g-helper#3240]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

This isn't related to a big problem, but even when we are in iGPU mode, NVIDIA Services, like NVIDIA Display Container LS, and NVIDIA LocalSystem Container, are still running on the background. Is there a way to link them to the start of the Ultimate Mode, over having them run all the time.

### Describe the solution you'd like

Just like how G Helper can control the ASUS Services, we can have the start of these services linked to Ultimate and Standard. So that way, we won't have these services running when in iGPU mode.

### Device and Model

ASUS ROG Flow x16 GV601RM

**Comment by seerge** [comment]
@IncognitoFawkes hello,

Those services are managed by Nvidia drivers, and are actually needed when you enable GPU (i.e. set Standard from Eco). So I don't see any point interfering here, as it will cause more harm than good. Armoury also don't touch them.

Furthermore : there [is known issue with Nvidia driver and it's components](https://github.com/seerge/g-helper/discussions/1042) not properly starting with windows when system boots in Eco mode, and then causing some software issues if you enable GPU  afterwareds. That's why G-Helper offers an option to `Enable GPU on shutdown` to prevent this from happening.

Thanks.
