### ISSUE TITLE
GPU custom fan curve doesnt work even checked the box.

### ISSUE THREAD

**Issue by Win9-1** [seerge/g-helper#3260]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

GPU fan doesn't work if it using the custom fan curve.( I have checked the use custom fan curve box. ) I have to use the preset from the ASUS bio fan curve in order to get the fan spinnning. I found this problem when i was playing cs2. The gpu temp was hitting 86C but the fan is at 0rpm. I have to switch the fan curve back to the BIO preset to get it spinning. All i change is GPU core clock limit to 1705 hz. I have notice when i use my custom fan curve. the name of the profile have a + after it. 

### How to reproduce the bug?

1. Open the custom fan curve section
2. Create a fan curve and check the box below
3. Restart the laptop and let a laptop sit for 2-3 minutes
4. Open a game that use a lot of resource 
5. GPU temp should be overheating and the fan speed is 0rpm
6. Click and use the BIO preset fan curve
7.GPU fan speed should back to spinning

### Logs

[log.txt](https://github.com/user-attachments/files/17361162/log.txt)

### Device and Model

ASUS TUF Dash F15 (i7 RTX 3060)

### Additional information.

![image](https://github.com/user-attachments/assets/d92c1c99-7338-4c93-a3ec-2c5fc0fcdf24)

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

0.194.0

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Win9-1 hello,

Even when custom fan curve is applied - [it is still controlled by the firmware / BIOS ](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds)same as it happens when you set a Manual mode in Armoury. So it's most likely some firmware hiccup in your case.

App sets fan curve exactly as you edited it
```
14/10/2024 16:13:42: FanCPU = 1E-3A-3D-41-45-4A-51-5C-00-08-11-20-31-46-59-64 : OK
14/10/2024 16:13:42: FanGPU = 1E-34-3D-42-47-4F-57-62-00-10-1A-30-44-55-64-64 : OK
```

You can try to
- Experiment with custom fan curve and try to set **first dot to be above zero**
- Use `Turbo` mode as base  for your customizations instead of `Balanced` (as in Armoury Manual mode is based on Turbo)
- Set `Eco` and `Standard` again (some BIOSes are bugged, and it helps to wake up fan control)


Or if nothing helps and you still want to use custom fan curve try [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Thanks
