### ISSUE TITLE
More refresh rate options between 60 and Highest in G Helper

### ISSUE THREAD

**Issue by detcordtech** [seerge/g-helper#3261]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Not an exact problem, but -
- I used CRU to add more refresh rates between 60 and Highest
- Options = 60, 90, 120, 144, 165, 240 Hz
- Only Auto, 60 and 240 are shown in G Helper
- Auto mode switches between 60 and 240 only
- Manually using 144Hz on my 240hz display, G Helper can read the correct refresh rate (screenshot)
![image](https://github.com/user-attachments/assets/83337d4d-756a-4bee-926a-c2b04aa5f35c)

### Describe the solution you'd like

Would love to have
- Configurable buttons that have more options (90, 144 Hz)
- Configurable Auto mode that switches between selected refresh rates (I use 90Hz on battery, 144Hz on charging mostly, barely use 240Hz - don't need it)

### Describe alternatives you've considered

Using Windows Settings > Display > Advanced Display > Select the desired refresh rate

Takes 30-45 seconds every time I plug or unplug. G-Helper is lightning fast and very handy at doing this in comparison! 

### Device and Model

ASUS Zephyrus G15 GA503RW (2022)

**Comment by seerge** [comment]
@detcordtech hello,

I can remotely understand why you want to use 90hz instead of 60hz (for smoothness). But I don't understand any downsides of using some 144hz instead of maximum possible .

This build should allow you to add a custom param in `%appdata%\GHelper\config.json` to set minimum refresh rate

```
"min_rate": 90,
```

[GHelper.zip](https://github.com/user-attachments/files/17368667/GHelper.zip)

**Comment by CaptainXLAB** [comment]
Thanks for the quick update! 😄

Reason for using 144Hz (lower-than-highest available) refresh rate:
- I often use **Type C PD charging** on the go and don't have the full charger
- Some software, popularly Discord activities, always have light games **rendering at highest framerate**
- 240Hz ends up **draining battery on PD** instead of charging
- 120Hz or 144Hz seems to be a better fit, laptop charges at 8-10w instead of discharging when I'm doing normal stuff

This is why I'm often using 144Hz instead of 240Hz as the upper framerate, Type C PD charging is what I use more.

**Comment by seerge** [comment]
@CaptainXLAB ok, even tho I still find it weird (as i doubt there is big power consumption difference between 144hz and 240hz), I have added an option to override maximum refresh rate as well.

You will still have 2 buttons in the app, but you can set your own refresh rates for them now:

```
"min_rate": 90,
"max_rate": 144,
```

Try this build
[GHelper.zip](https://github.com/user-attachments/files/17375338/GHelper.zip)

**Comment by huzaifahshahid71-ops** [comment]
Hey brother how did you add other refresh rates using cru like 48 hz , 90 hz , 144 hz and 165 hz ???  I was only able to get 120 hz working rest didn’t work
