### ISSUE TITLE
Temperature too high

### ISSUE THREAD

**Issue by M-Mahou** [seerge/g-helper#3274]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Ghelper shows cpu temperature higher than what it probably is ?

![image](https://github.com/user-attachments/assets/6e467647-3500-43fd-b2d0-86fa0ebe84a8)

and in consequence, the fans are always loud 

### How to reproduce the bug?

Launch ghelper ?

### Logs

[log.txt](https://github.com/user-attachments/files/17445804/log.txt)

### Device and Model

Asus TUF A15 tuf507rr-hn009w

### Armoury Crate

Installed

### Asus Services

8

### Version

0.194.0

### OS

Windows 11

**Comment by seerge** [comment]
@M-Mahou hello, G-Helper takes and shows CPU temperature from special Asus endpoint. On your screenshot in Task Manager you look at GPU temperatures (and they match - 48C)

This is the same temperature BIOS uses for controlling fans. Furthermore Armoury Crate also shows same temperature (since you have it installed, you can launch it and verify that). 

So everything is correct.

Thanks
