### ISSUE TITLE
PL1 and PL2 only working on Silent mode

### ISSUE THREAD

**Issue by Lucas85PL** [seerge/g-helper#3296]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

It seems that the PL1 and PL2 limits only work in Silent mode. Whenever I switch to Balance / Turbo the CPU by default runs at 30-40W.
If i switch on Turbo Boost, the CPU does indeed go to 'full'.
I have attached screenshots of all 3 modes with CPU benchmark running in the background (visible in screenshots).

Laptop: ASUS G16
CPU: Intel i7 13650HX

### How to reproduce the bug?

Change power modes with different PL1 PL2 limits.

### Logs

[log.txt](https://github.com/user-attachments/files/17508223/log.txt)

### Device and Model

Asus G16

### Additional information.

![Silent](https://github.com/user-attachments/assets/7697ebcc-ab78-4eb9-8cc2-f283f9f5a874)
![Balance](https://github.com/user-attachments/assets/c0921104-5361-4a5e-8f63-c0df191e36c3)
![Turbo](https://github.com/user-attachments/assets/a6ab3ba0-5b54-4a72-b34c-b3715dbbc689)

### Armoury Crate

Uninstalled

### Version

0.194.0

### OS

Windows 11

**Comment by Lucas85PL** [comment]
I think I am a dumdum. Seems that Turbo Boost must be anabled for PL1 and PL2 to work?

**Comment by seerge** [comment]
@Lucas85PL hello, 

When CPU Boost is disabled, CPU simply doesn't need more power and it usually runs on 30-40 watts maximum (depending  on actual CPU model of course). That's why some people advice to disable boost, it's just another way to limit power even tho not the most flexible.

When Boost is enabled it should be allowed to go higher.

I don't really see how exactly do you measure CPU power limits, but correct way would be to run a CPU-only benchmark (i.e. Cinebench 23 or so) and check actual CPU power consumption using HWinfo or similar app.

Thanks

**Comment by Lucas85PL** [comment]
Thank for explanation, I get it now.
Also, the app is absolutely brilliant!
