### ISSUE TITLE
Key Bindings Messed up

### ISSUE THREAD

**Issue by Rumit95** [seerge/g-helper#3310]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After running the G-helper, my laptop's keyboard key binding got messed up. Key C, key K, key P, and the spacebar were not working. Also, the calculator app would sometimes pop up multiple times, and the keyboard colour cycle would change just by pressing the arrow keys without the fn key. 

### How to reproduce the bug?

Dont know how could you recreate this its just started happening suddenly after removing the config.json and G-helper my keyboard seems to be running fine.I'm not sure how to recreate this issue. It just started happening suddenly after I removed the config.json and G-helper. However, my keyboard seems to be functioning fine now.

### Logs

Deleted in panic

### Device and Model

Asus TuF ryzen 7 4800h model

### Armoury Crate

Uninstalled

### Asus Services

Dont know

### Version

Recent

### OS

Windows 11

**Comment by seerge** [comment]
@Rumit95 hello, sorry to read that.

G-Helper **is not able to rebind your C, K, P or other keys**. It's not a driver. So if something was not working - it was not related to the app in a first place.

In terms of hotkey processing, it can only to WMI events that that special hotkeys (FN+1, FN+2, etc) emit.

Since you don't provide any logs and don't use app I obviously can't assist you anyhow.

Thanks and good luck.
