### ISSUE TITLE
Visual mode "disabled" flicker issue

### ISSUE THREAD

**Issue by Julien999** [seerge/g-helper#3334]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi ! So when I set the visual mode to "disabled", my screen changes between visual modes by itself sometimes depending on what app I have open for some reason (if i am on chrome, it'll switch to the last selected display mode from time to time) it also doesn't reapply on boot.
Here is what it writes in the log file :
![image](https://github.com/user-attachments/assets/7aae814a-b9b1-4dae-bdfe-32f957bf0345)

### How to reproduce the bug?

1. Set visual mode to disabled
2. Have the laptop display set to Optimus in NVIDIA control panel
3. Open chrome
4. Watch the screen change visual modes

### Logs

[log.txt](https://github.com/user-attachments/files/17603475/log.txt)

### Device and Model

Asus Rog Zephyrus G14 GA402XV

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.197.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@Julien999 hello,

Just to clarify how [Visual Modes work](https://github.com/seerge/g-helper/wiki/FAQ#how-do-visual-modes-and-color-gamuts-work):

They are handled by `AsusSplendid.exe` utility (part of Asus Control Interface).  Both Armoury Crate or G-Helper just call it with a parameter for each mode (11 is Default, 13 is Vivid, 18 Disabled, etc)

You can see this calls in the log:
```
C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_a61e5ab0aed04d3c\ASUSOptimization\AsusSplendid.exe 18 2 
...
C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_a61e5ab0aed04d3c\ASUSOptimization\AsusSplendid.exe 13 0 50
...
C:\WINDOWS\system32\DriverStore\FileRepository\asussci2.inf_amd64_a61e5ab0aed04d3c\ASUSOptimization\AsusSplendid.exe 11 0 50
```

Unfortunately this "Disabled" state doesn't seem to work with AMD drivers sometimes, especially with ones from AMD itself. When some process like Chrome starts actively using GPU AMD driver changes colors back to a previously used mode. This is some internal thing in the way `AsusSplendid.exe` does this. I hope eventually with updates of Asus Control Interface it will be fixed.

I have also experienced that on my G14 2022 (all AMD model), and even double-checked that **exactly same** happens if you would disable Game Visual in Armoury Crate. 

What seemed to help - **is using Asus own AMD drivers** (from their website or G-Helper's `Update` section). Then it works fine. Alternatively you can just use Default mode, as it's almost same as Disabled.

Besides I can't do much. Sorry.
Thanks.

**Comment by Julien999** [comment]
Thanks for the answer and for your explanation, I understand why you can't do much.
Have a nice day

**Comment by seerge** [comment]
@Julien999 ok. Let me know if Asus own AMD drivers make any difference :)

**Comment by Julien999** [comment]
Hi, the Asus's AMD driver seems to have resolved it, thanks :)

**Comment by seerge** [comment]
@Julien999 good to know! I still managed to catch a "psychodelic" colors once after reboot even with Asus AMD drivers. But that happened cause I went into color modifications in Adrenaline app.

**Comment by Julien999** [comment]
I have the same issue on reboot but it's much better now
