### ISSUE TITLE
Battery miscalibration after changing GPU mode

### ISSUE THREAD

**Issue by Vital-Fernandez** [seerge/g-helper#3336]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I wonder if anyone could help me please on how to avoid this issue and properly use Ghelper.

On two occasions once I try to change the GPU mode with g-helper on my asus zephyrus G14 2021 the GA401QM the battery charge level sets itself to zero.

Afterwards I have to let the computer discharge itself, turn it off, charge the battery to be able to have it work again.

### How to reproduce the bug?

Change GPU mode .

### Logs

[log.txt](https://github.com/user-attachments/files/17608695/log.txt)

### Device and Model

Asus Zephyrus G14 GA401QM 

### Armoury Crate

Uninstalled

### OS

Windows 11

**Comment by seerge** [comment]
@Vital-Fernandez hello,

I'm sorry but this is not due to G-Helper in a firs place :) Battery calibration happens on hardware / firmware level by itself, and then windows or any apps reading it from windows just reports it. 

It looks more like some firmware hiccup in your specific device. 

- You can try [Hard reset EC controller](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset) to see if it helps
- You can try to reset all BIOS settings (F2 on boot) to defaults
- You can try to install (again) latest BIOS version from Asus website using Asus EZ Flash utility

Besides that I can't do much :)

Thanks and good luck.
