### ISSUE TITLE
Automatic "Scan for hardware changes"

### ISSUE THREAD

**Issue by alexb5dh** [seerge/g-helper#3366]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

NVIDIA card can sometimes "disappear" after sleep or hibernation. It can't be used by any app and both NVIDIA Control Panel and NVIDIA app don't start. This seems to be a relatively common laptop problem, but can often be resolved by a simple "Scan for hardware changes" in Windows Device Manager.

G-Helper "Enable GPU on shutdown" doesn't seem to resolve this specific case. When the issue happens, GPU Mode is shown as "iGPU + dGPU", but opening Fans and Power settings shows only CPU.

### Describe the solution you'd like

Add an automatic call to "Scan for hardware changes" to the app when some conditions are met.
For example after waking up from sleep/hibernation, when G-Helper expects GPU device to be enabled, but detects that it's not present.

### Device and Model

ROG Strix SCAR 15 G533QS, but happens on many Optimus-enabled laptops.

### Additional information.

![image](https://github.com/user-attachments/assets/4e6a1628-bee0-4fc8-bf54-09e23b773c75)

**Comment by seerge** [comment]
@alexb5dh hello,

When GPU is completely disabled on Asus devices (i.e set to Eco or Optimized on battery) - it disappears from device manager, so that's normal. And it's actually good - so windows can't wake it up and start draining battery :)

But if GPU is enabled on hardware level, it should be automatically detected by windows. This applies to any device that you "plug" into system in real-time.

Could it be something with windows / Nvidia driver itself ? In other issue I suggested you to try [Hard Reset](https://github.com/seerge/g-helper/wiki/Troubleshooting#hard-reset--embedded-controller-ec-reset) or fresh [GPU driver install](https://github.com/seerge/g-helper/wiki/Troubleshooting#reinstalling-gpu-drivers). Does it make any difference ?

--

As for actual manual "Scan for hardware changes" command, I think you can run it directly from powershell or create a new Task in windows Task Scheduler
```
pnputil.exe /scan-devices
```

You can also assign one of the macro-keys in G-Helper to run this command, but I'm not sure if this is not an overkill.

**Comment by alexb5dh** [comment]
Thanks, will try your suggestions.

Task Scheduler option also seems like a good idea if that won't help.

**Comment by seerge** [comment]
@alexb5dh ok, let me know what worked for you
