### ISSUE TITLE
FA507XV Realtek LAN driver updates shows wrong version issue

### ISSUE THREAD

**Issue by xpk20040228** [seerge/g-helper#3429]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

as in the picture, when realtek lan driver is installed, the version does not match the version expected, despite what is installed is newer than the recommended version (2024 vs 2022)

### How to reproduce the bug?

![image](https://github.com/user-attachments/assets/639110aa-4533-430b-8b75-8a1366ccd6c3)

![image2](https://github.com/user-attachments/assets/581f2ea0-85d2-46ee-8b20-9883036d4fb9)

### Logs

[log.txt](https://github.com/user-attachments/files/17975441/log.txt)

### Device and Model

ASUS TUF A15 2023 FA507XV

### Armoury Crate

Installed

### Asus Services

None

### Version

0.197.0

### OS

Windows 10 22H2 19045.5198

**Comment by seerge** [comment]
@xpk20040228 hello,

G-Helper takes drivers list and all versions from official Asus website for your specific model.

Since this specific driver on website has version number that is higher than what windows reports as installed one, it makrs it as red.

Most likely Asus has just marked driver version incorrectly.

If you have already downloaded and installed this driver once - you are already good, and can ignore that.

Thanks
