### ISSUE TITLE
Checking Apply Power Limits changes fan curve

### ISSUE THREAD

**Issue by injkgz** [seerge/g-helper#3455]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

If I checking "Apply Power Limits" then fan curve changing to something another, while on default balanced mode i have silent fans spinning at 50-55c on 1500-1800rpm
But when I make PL1 and PL2 on 20-25W it's starts to run about 2200-3000rpm

### How to reproduce the bug?

1. Be idle
2. Open G-helper and check fan speed, while on default Balanced mode without any changes
3. Change Power Limit to any other and check Apply Power Limits

### Logs

[log.txt](https://github.com/user-attachments/files/18051127/log.txt)

### Device and Model

ASUS Zephyrus G16 GU605MI

### Additional information.

Before BIOS 323 it wasn't work like that, fan curve didn't change.

### Armoury Crate

Uninstalled

### Asus Services

None

### Version

0.197

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@injkgz hello,

Some models (including yours) in order to make custom power limits work - also require custom fan curves to be applied as well. Same as in Armoury you can't set only power limits, you set all together.

In addition to that, as soon as you start applying any customizations - firmware / BIOS will treat this as a "custom" mode, so it also can affect fan behavior

So if fan behave differently when limits are set - it's normal, you can try to adjust a fan curve to your liking. 

If you don't like how firmware controls fans along default or custom fan curves you can try a [Experimental build with a manual fan control](https://github.com/seerge/g-helper/discussions/2272)

Thanks

**Comment by injkgz** [comment]
Thank you for you answer! Great software by the way! I'm using it on 3 laptops.
BTW do you know how ThrottleStop works? If i set PL1 and PL2 limit via ThrottleStop will I make BIOS think that i'm on manual mode?

**Comment by seerge** [comment]
@injkgz I don't know how ThrottleStop works, as it's not open source. But most likely it uses some Intel specific endpoints and changes power limits on "driver" level in windows.

G-Helper uses only existing Armoury Crate endpoints, that asus has prepared for their own software :)
