### ISSUE TITLE
force laptop to run on direct power and only use the battery when unplugged

### ISSUE THREAD

**Issue by Behroz666** [seerge/g-helper#3464]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I dont know if this is even possible or not but I mostly use my laptop on my room and it is **always** plugged in for best performance but I use the battery only when I'm not home (I think this is what most people do) but I think having battrey constantly plugged in is not ideal (Although I made 80% limit) 

### Describe the solution you'd like

I want a option to disable battery charge when its plugged in and disable battery (like its not connected at all) 

### Device and Model

ROG Flow X13 GV302XA

### Additional information.

this is irrelevant but mu model dont have dedicated gpu but gpu mode still show up in the app whats the point of those in igpu only device ?

**Comment by seerge** [comment]
@Behroz666 hello,

You can't "disable" battery charging when you are plugged in. But your battery stops charging by itself as soon as it reaches charge limit (whatever it's 100% or anything custom you have selected).

This is how any battery works and not only in laptops :)

Thanks

**Comment by Behroz666** [comment]
Hi thanks for your response 

I know that the battery stops charging as soon as it reaches the limit but after the battery loses some of its charges, the charger will resume and recharge battery to the limit. for example there is battery protection feature in phones that when you want to charge over night it will stop charging at 80% and estimate when to start charging again to be 100% when you are awake, there is also basic protection to avoid this constant discharge and charge cycle (it will stop charging until battery level drops to 95 and start over). 

But in a laptop that is used on a desk and you always have the power available why couldn't we disable battery completely ? some people recommend taking battery out completely but its not ideal.

**Comment by seerge** [comment]
@Behroz666 usually battery won't drop charge fast when you are plugged in, cause device uses wall power then.

The feature on the phones you explain is same thing already existing in Asus laptops, you can set charge limit to 80% and then to 100% whenever you want. Whole idea of that is to minimize time while device stays with a 100% charged battery. With the only difference that phone actually **needs** 100% charge to last through the day, so phone will still charge to 100%, while your laptop when plugged - doesn't.

Since you are constantly plugged in - you can keep charge limit at 80%, or even 60% all the time.

Besides that there are no extra control over charging that can be adjusted. It's all handled by firmware.

Thanks
