### ISSUE TITLE
Internal GPU fan uncontrollable when using XG mobile

### ISSUE THREAD

**Issue by MerApple** [seerge/g-helper#3471]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

First I have to say, Ghelper is alot better then the shitty armoury crate. This application saved me and I was able to make the system stable again something Armoury crate failed to do. I am forever grateful for this software, bringing back control over my computer.

However there is a problem with my x13 and XG mobile that Ghelper could not solve (Armoury crate have a similar bug) and thats control over the internal GPU fan when XG mobile is enabled. 
Fan on the external GPU works just fine, but the internal GPU fan gets stuck on whatever RPM it was set to when XG mobile is started.

This causes 2 issues.
1. If internal GPU fan was set to high when XG mobile was started, the fan remain on high RPM regardless temperature after XG mobile is started. Alot of noise is generated even when temperature is low, and the only way to reduce fan speeed is to disable XG mobile.

2. If internal GPU fan was set to 0 when XG mobile was started then when you want full power from CPU it causes heating inside laptop (yes even if internal GPU is not being used, the heat from the CPU is warming the internal GPU) the internal GPU fan never starts, and temperatures can easily go above the automatic shut down temperature and system gets unstable, this is exaclty what happened with the armoury crate software as well. GPU fan never helped cool down the system causing us users not being able to get that final juice from our cpu. I know it might not be much extra you can gain by having the GPU fan controllable in this situation but it should be some additional 100 points on CPU stress test that you can achive by having the GPU controllable during high loads and still remain sane whenever you want the computer to be silent in low power mode.

### How to reproduce the bug?

1. Enable XG mobile
2. Whatever RPM internal GPU was set to, that RPM will remain until XG mobile is shut down, temperature does not matter. And no reboot computer does not make any difference.

### Logs

[log.txt](https://github.com/user-attachments/files/18102536/log.txt)

### Device and Model

X13 Flow

### Armoury Crate

Uninstalled

### Asus Services

MyAsus

### Version

0.199

### OS

Windows 10 x64

**Comment by MerApple** [comment]
I checked through the C# code and at least I cant see that the internal GPU fan is set to 0 when XG mobile gets initialized. If you add code to do that when initializing XG mobile then issue number 1 could be easy fix.

For issue number 2, I was not able to see why internal GPU fan could not be controlled from the C# code when XG mobile is active, maybe this is a limitation in computer bios and not possible to solve? But at least issue 1 should be possible to solve?

**Comment by seerge** [comment]
@MerApple hello,

Fans (internal and XGM-ones) are controlled by firmware. And what you explain is how firmware is programmed on your device. That's why behavior you see is same in AC or G-Helper. 

I see that you use a custom fan curves for everything. Try to reset mode back to defaults by pressing `Factory Defaults` under `Fans + Power`. Sometimes it may help and change the things.

If you really want to use custom fan curves, you can try [Experimental build with a manual fan curve](https://github.com/seerge/g-helper/discussions/2272). There G-Helper can set fan speeds to internal fans of the laptop (but not for XGM)

P.S. G-Helper is not setting  fan to 0 :)

Thanks

**Comment by MerApple** [comment]
@seerge Thanks for responding!
You are indeed right, I am using custom fan speed curves. 

As soon as I disabled custom fan speed curve the internal gpu fan started reacting to tempertaures again.
But as soon as I turn on custom span feed then the intenal gpu freezes on whatever RPM it had regardless how the internal gpu speed curve is set.

Question 1: Do I understand you correctly that enabling custom fan speed disables control over the internal GPU fan when XG mobile is active is enabled and this is expected behaviour because of BIOS FW?

Question 2: The GPU temperature viewed in Ghelper is definitely showing the XG mobile temperature, however it is not clear what the GPU fan speed is showing, sometimes it is internal GPU fan speed and sometimes it is XG mobile fan speed showing, this is very confusing to me, is it possible to seperate XG mobile fan speed and internal GPU fan speed so you can see the actual RPM on both cards from the UI?

**Comment by seerge** [comment]
@MerApple 

1. Applying custom fan curves (i.e. "manual mode" in AC) doesn't disable fans. But it's still up to firmware what to do. It looks more like a firmware hiccup in your case.

2. G-Helper shows XGM temp as this is what Nvidia driver reports when it's enabled. But since fans are controlled by firmware / BIOS - firmware uses own measurements and sensor readings to do that, it's not affected by what G-Helper's UI shows. You can't read or show XGM fan speed to my best knowledge. You see internal fan speeds only.

3. Each "mode" is effectively a preset of multiple settings in a firmware, they also affect XGM behavior. So it's normal that XGM had different limits in different modes.
