### ISSUE TITLE
Fan Speeds Not Displayed on the App - Vivobook Pro 15 OLED

### ISSUE THREAD

**Issue by Lethalx13** [seerge/g-helper#3475]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

The fan speeds no longer appear next to the CPU and GPU temperatures on the latest version of the app. I recall it used to work on an earlier version (cannot remember exactly which one). They are not shown on the app's tooltip from the taskbar as well.

**However, do note that the fan speeds are still visible on the Experimental app (the app with manual fan control).**

Below screenshots are from the normal release v0.199.

![image](https://github.com/user-attachments/assets/c6a004fb-0741-4dc0-9f08-f6c920b004a6)
![image](https://github.com/user-attachments/assets/ecf233c7-f178-478f-8565-fc5449c5357c)

### How to reproduce the bug?

1. Open the app, on the main page there are no speeds for CPU and GPU.

### Logs

[log.txt](https://github.com/user-attachments/files/18112771/log.txt)

### Device and Model

Asus Vivobook Pro 15 OLED N6506MU

### Armoury Crate

Never installed

### Asus Services

6

### Version

0.199.1

### OS

Windows 11 23H2

**Comment by seerge** [comment]
@Lethalx13 hello,

Some Vivobooks (including yours) don't report fan speeds via "standard" endpoints (provided by Asus System Control Interface). So app won't show them.

But it is possible to read them via special separate "myasus" SystemDiagnosis driver. Experimental build is using that driver to set custom fan speeds and also read them. But I don't plan and can't merge that communication in the mainstream branch cause it will break app for other users who don't need experimental control :)

That's why if you want to see fan speeds - you can use Experimental build as that's the only way atm.

Thanks.

**Comment by Lethalx13** [comment]
Your explanation made it crystal clear, thanks a lot for the response.
