### ISSUE TITLE
Option to remapping Asus Rog Strix G16 multimedia key into Home, Pgup, Pg down, End button.

### ISSUE THREAD

**Issue by vathanac** [seerge/g-helper#3484]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

I can remap those keys into Home, Pgup, Pg down, End buttons by using autohotkey or power toys, but it won't work on software like VMware or AnyDesk, and it's annoying as I also have my mouse dpi button map as play/pause. I know that Asus have option to use these function with combination of FN key, but it is slower and unpredictable to use.

![image](https://github.com/user-attachments/assets/3c55b8d2-b533-4199-924d-7192e6d0e8cb)

### Describe the solution you'd like

Armory Crate doesn't have option to remapping key like MSI with their steelseires keyboard is such bumper. If you're able add this into G-helper would be totally awesome

### Device and Model

Asus Rog Strix G16 G614JV

**Comment by seerge** [comment]
@vathanac hello, those keys emit windows media commands on **hardware level,** that can't be changed unfortunately.

You can rebind them on **software** level, but that would work exactly same as it works right now with Autohotkey (or can also try Sharpkeys for same purpose btw). 

G-Helper won't make it different to those apps. And since this is not a proprietary Asus thing, but rather general hotkey change in windows - I don't want to overload app with an extra things that can be easily achieved with existing tools :)
