### ISSUE TITLE
Request to remove "disabled" option in Visual Mode for laptop TUF A16 FA617SNR

### ISSUE THREAD

**Issue by chenchen9687** [seerge/g-helper#3505]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

Upon selecting "disabled" in Visual Mode and restart the laptop, the screen colour will appear corrupted and only be fixed after select other visual modes

### Describe the solution you'd like

remove the "disabled" option to prevent other users encounter this issue in future

### Device and Model

Asus TUF Gaming A16 FA617NSR

**Comment by chenchen9687** [comment]
video:
https://youtu.be/bWuMgv4i00Q?si=BiZ5B6tsqo5LJPvl

**Comment by seerge** [comment]
@chenchen9687 hello,

I believe you :) But since all Visual Modes (Game Visual in AC) are actually handled by AsusSplendid.exe utility under the hood, including `Disabled`, it may be just incompatible with AMD drivers from AMD itself. As when you use ones from Asus website directly - it works fine.

I would say - just use `Default` instead ? :)

Thanks
