### ISSUE TITLE
Sleep shortcut not working

### ISSUE THREAD

**Issue by Meonthb** [seerge/g-helper#3520]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

After I uninstall armory crate and My ASUS app and using Ghelper, I find the shortcut Fn+F11, which is the sleep shortcut in my laptop, not working anymore. When I press this shortcut just nothing happen.

### How to reproduce the bug?

click Fn+F11

### Logs

[log.txt](https://github.com/user-attachments/files/18243323/log.txt)

### Device and Model

ROG Zephyrus G14 GA402XV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.199.0

### OS

Windows 11 24H2

**Comment by seerge** [comment]
@Meonthb hello,

Sleep hotkey is being processed, you can see it in the log
```
12/25/24 12:33:43 PM: Key: 108
12/25/24 12:33:43 PM: Sleep = 108 : OK <--- sleep command :)
```

You can try to start Asus Optimization Service (manually from windows services app) or via `Extra` settings in G-Helper and then it will process hotkeys instead of the app. Does it make any difference ? Cause if not - probably windows is simply ignoring sleep by some unrelated reason,

**Comment by Meonthb** [comment]
Thank you! When I start Asus Optimization Service it still has no difference. I finally figure out the causes is that the power plan has been changed during uninstallation of armory crate.
