### ISSUE TITLE
Fan stop spinning after windows force sleep mode 

### ISSUE THREAD

**Issue by sarhveshracktoo** [seerge/g-helper#3525]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

I have an ASUS ROG Strix G16, I always like to keep my laptop ON. Recently, I discovered that windows force it to go into sleep mode even if I put the sleep mode to ''Never''. After it goes into sleep mode, the fan stop spinning and overheat the laptop at 95*C . This could be very problematic in the future destroying some hardware.

It would be great if you can add an option to bypass or stop the windows force into sleep mode.

### How to reproduce the bug?

After windows force the laptop to go into sleep mode.

### Logs

[log.txt](https://github.com/user-attachments/files/18246416/log.txt)

### Device and Model

ASUS ROG Strix G16 (2023) G614JV

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.200

### OS

Windows 10 Pro (22H2)

**Comment by seerge** [comment]
@sarhveshracktoo hello, 

Please make yourself familiar with FAQ. Fans are always controlled by [firmware / BIOS](https://github.com/seerge/g-helper/wiki/FAQ#how-does-g-helper-control-my-fan-speeds). 

If you don't like how firmware handles them you can try to use default fan curves instead of custom ones that you set (just click Factory Defaults under Fans + Power)

Sleep is a windows functionality, G-Helper is not putting your laptop to sleep and not waking it up obviously.

Thanks.
