### ISSUE TITLE
addition of two power mode fields for on battery or plugged in

### ISSUE THREAD

**Issue by kiomarg** [seerge/g-helper#3533]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

in the windows settings power menu, there are two options for on battery power mode or plugged; 
in the Ghelper there is only one and these conflict when the laptop is unplugged the app doesn't hold the settings properly.

### Describe the solution you'd like

to add two power mode like the windows menu

### Device and Model

Asus zephyrus G15 GA503RW

**Comment by seerge** [comment]
@kiomarg hello, I was answering this before.

This is a new thing introduced in  in Windows **24H2**. From the two power options you are talking about only one is currently active.

Windows API (that G-Helper uses) allows to change only currently active Power Mode. So when device is plugged in - setting that you see in G-Helper is able to adjust plugged dropdown in settings, and when it's on battery - correspondingly battery one. You can't adjust inactive mode from API.

And this is not needed since app already remembers last used mode for plugged in / on battery states it switches them already :)

Thanks.

**Comment by kiomarg** [comment]
Hi Seerge,
thank you for your reply,
sorry I did not find an earlier post on this,
Anyways thank you so much for your help and making a great app, I enjoy
using it everytime.
regards
Karan
