### ISSUE TITLE
2023 G14s: "Manage Display Settings" / Advanced Optimus no longer appearing

### ISSUE THREAD

**Issue by Maxusmusti** [seerge/g-helper#451]
**Describe the bug**
Before switching to g-helper, there was a setting in the NVIDIA Control Panel called "Manage Display Settings" with options of `automatic select` (advanced optimus), `optimus`, and `NVIDIA GPU only`. There was also an option under "Desktop" to add a notification tray icon to switch between the three. Since switching from Armory Crate to g-helper, however (no other system changes), these options have disappeared from both the control panel and the notification tray. Now the only way to switch to the GPU for internal display is via `ultimate` GPU mode, which requires a system restart (unlike just switching the display option to `NVIDIA GPU only`.

**Clear scenario to Reproduce**
On a 2023 model:
 - Go to NVIDIA control panel
 - The display settings are missing

**Expected behavior**
The display settings shouldn't be missing 

**App Logs**
log.txt from ``%AppData%\GHelper``:
[log.txt](https://github.com/seerge/g-helper/files/11549525/log.txt)

**Screenshots or screencasts**
Should be under "Manage 3D Settings"
![image](https://github.com/seerge/g-helper/assets/10506868/fa730c77-0918-4849-9c16-3433350fbd0b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: 3023 G14 (4060)

**Asus software**
- MyASUS installed
- Other Asus services running in background:
![image](https://github.com/seerge/g-helper/assets/10506868/a369a7b8-f485-477f-8f81-816d0ddc897b)

**Comment by Maxusmusti** [comment]
UPDATE: After experimenting further, I was able to (maybe temporarily, maybe permanently) resolve the issue. All I did was switch to GPU ultimate mode (and restart), then switch back to standard mode (and restart again), and now the setting seems to exist again?

![image](https://github.com/seerge/g-helper/assets/10506868/de45e56f-fa4f-4ab5-b8aa-a3d4ef64ecff)
Not sure exactly what part of the process resolved this, maybe uninstalling AC / debloating also switched DDS off in the BIOS, and switching back and forth from ultimate mode switched it back on? Not sure, will update again if issue re-appears...

**Comment by seerge** [comment]
@Maxusmusti hello, app doesn't touch optimus or any nvidia control panel in any way. 

What it does it uses built in command (in bios) to power off / on dGPU. 

I can imagine that after disabling Nvidia GPU, there is no nvidia in the sytem and control panel (obviously) don't show optimus. And after enabling GPU Nvidia control panel may not refresh / reload itself? Try killing NV control panel process / restarting it (or restarting laptop)? :)

**Comment by Noisrevid** [comment]
For what it's worth - I have a 2023 G14 and the machine entirely locks up when I select Optimus or Automatic Select when i'm in "NVIDIA GPU only" mode.     I don't think has anything to do with G-Helper as i'm experiencing issues without using G-Helper or ArmouryCrate on that machine.

**Comment by Maxusmusti** [comment]
@seerge nothing yet, everything seems to be working normally now, notably there have also been two nvidia driver updates out since the issue. I'll try experimenting between switching back and forth from eco mode, as well as booting the machine unplugged vs plugged in before, to see if I can hit any weird edge cases

**Comment by Noisrevid** [comment]
Everything is working well for me now, I did a fresh reinstall of the Nvidia drivers so not sure..    I still occasionally get to the point where G-Helper times out trying to switch to Eco mode and asks me to restart the GPU, which works..   Since the time out feature you implemented takes a while (and i'm very impatient) would it just be faster to have it restart the GPU driver every single time to ensure it switches to Eco mode?

**Comment by seerge** [comment]
@Maxusmusti ok, anyway - it looks more like nvidia driver/software related :)

**Comment by seerge** [comment]
@Noisrevid your case is from another issue :) and time-out takes time, cause app waits for a bios to respond. I can't make that faster.

**Comment by seerge** [comment]
@Noisrevid did you try to check "stop GPU apps" under extra? does it help in your case?

**Comment by seerge** [comment]
@Noisrevid you need to update to latest one (0.74). If it failed to auto-update by some reason, it could be that exe is located in some protected folder (i.e. where windows doesn't let it replace itself?)

**Comment by Noisrevid** [comment]
Gotcha, it was in my Downloads folder so not sure.   I see the new Extra settings now..   I clicked the "stop GPU apps" option and it still timed out for me the very next time I switched to Eco mode.   It asked me again "Something is using dGPU and preventing Eco mode" and I clicked "Restart GPU" and it just closes G-Helper and never re-opens G-Helper.   First time i've seen it just close G-Helper doing that.

**Comment by seerge** [comment]
@seerge try to run it as admin

**Comment by seerge** [comment]
@Noisrevid try to run it as admin (i assume it tried to restart itself as admin), but looks like some (unknown) windows permissions prevent app from running itself (same as prevent it from updating)

**Comment by Noisrevid** [comment]
@seerge Restarted machine, launched G-Helper in Admin mode..  It was in Standard mode at the time, clicked Eco, worked fine.   Then switched back to Standard again, worked fine.    Then again, switched back to Eco mode, it had to time out again and ask to restart dGPU driver, then clicked Eco mode again and it worked.    It's weird that it works once very quickly but then the second time I do it, it has to go through the time out thing.    What if you put another checkbox under Extra for "Always restart dGPU" for Eco mode since this ultimately is the fix.. It seems like something is grabbing the dGPU the moment I switch to it even though nothing is running on my machine (I don't have Armoury Crate installed) and i'm just sitting on the desktop, no apps are open.

**Comment by seerge** [comment]
@Noisrevid i don't want to automate that, as the way restarting works, it's very "invasive" (it literally disables and enables device in device manager). And it's being used only as a last resort workaround for apparently bugging bios (or windows?).

Based on feedback on reddit / here, it seem to be quite rare case (at least lots of G14 2023 work fine). But I really hope asus / nvidia will address that somewhere in next updates.

**Comment by Noisrevid** [comment]
@seerge Got it, I edited my post, I missed the post about it being another issue above.    I'll just be patient, it works, I just have to wait for the time out and let it restart the device.

**Comment by Noisrevid** [comment]
@seerge Also how do I allow G-Helper to be in admin mode every time without me launching it manually with a right-click Admin?    It's in my Downloads folder, I would assume it should have access to be an admin automatically but it doesn't seem so since it doesn't work if I launch it without a right-click admin.

**Comment by seerge** [comment]
Closing this, as for topic started @Maxusmusti everything seem to be fine now.

@Noisrevid 's issue is absolutely different, and it's also "sorted out" in a way, while we wait for a permanent fix from asus ;)
