### ISSUE TITLE
Strix G15 Advantage Edition - No gpu modes showing up - Keyboard backlight never comes back after timeout on battery

### ISSUE THREAD

**Issue by CrimsonSoul** [seerge/g-helper#488]
**Describe the bug**
No GPU modes show up within the app such as eco etc. and when on battery once the keyboard backlight times out it never comes back on unless you go into ghelper and change the brightness level.

**Clear scenario to Reproduce**
1. Open ghelper
2. view gpu section
4. only the section header and gpu fan speed and gpu temp are shown

**Expected behavior**
multiple gpu modes should show up

keyboard backlight should come back on when using the keyboard after timeout on battery
** Log**
[log.txt](https://github.com/seerge/g-helper/files/11605543/log.txt)

**Screenshots**
<img width="322" alt="image" src="https://github.com/seerge/g-helper/assets/1158934/7bd8ef15-14e8-4af9-ad57-f41a016fe40d">

<img width="374" alt="image" src="https://github.com/seerge/g-helper/assets/1158934/81bca075-9a58-4de8-b12a-b092918abf8a">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G513QY - Strix G15 Advantage Edition

**Asus software**
- ASUS System Control Service

**Comment by CrimsonSoul** [comment]
> @CrimsonSoul hello, your laptop reports both Eco / Mux flags as not supported
> 
> ```
> 5/30/2023 3:41:52 PM: Eco flag : -65536
> 5/30/2023 3:41:52 PM: Mux flag : -65536
> ```
> 
> Did you have GPU modes in AC ?
> 
> P.S. Just googled, your device doesn't have mux switch initially ...
> 
> --
> 
> As for backlight - is it on battery or when plugged ? if on battery, try to uncheck "lower backlight brightness"

I did reinstall AC to verify. It looks like there is no eco mode for this laptop however there is a section to close all processes using the dgpu so it can go into deep sleep effectively shutting it off. This probably would be a feature request now but would there be a way to close all those processes using the dgpu automatically when switching to battery?

As for the backlight im currently testing the option you mentioned and will report back.

**Comment by CrimsonSoul** [comment]
Also AC will actually notify you if the dgpu is still enabled because there is a process running that is using it.

**Comment by seerge** [comment]
@CrimsonSoul closing processes from my experience doesn't guarantee GPU will enter sleep mode (that's why in all new models asus added real GPU power off switch). Also often windows own processes such as DWM (desktop window manager) or so use GPU, and killing them will require admin permissions.

You can set your power plan to "force integrated graphics" or something like that on battery instead.

**Comment by CrimsonSoul** [comment]
> @CrimsonSoul closing processes from my experience doesn't guarantee GPU will enter sleep mode (that's why in all new models asus added real GPU power off switch). Also often windows own processes such as DWM (desktop window manager) or so use GPU, and killing them will require admin permissions.
> 
> You can set your power plan to "force integrated graphics" or something like that on battery instead.

I thought that may be the case. Thanks for the info. 

As for the keyboard backlight it does look like unchecking lower brightness does actually fix the keyboard backlight not coming back on issue im not sure how that setting is related but it works.

**Comment by seerge** [comment]
@CrimsonSoul also, since you are on AMD GPU checking for GPU processes are cumbersome there (and not worth the effort only for 1 single model that is like 1% of total users)

As for backlight - that setting is pretty much competing with timeout. It will turn off backlight every time laptop is off grid or wakes up off grid (as in your logs). I may review or just remove that setting at all in future (it was added in times it was no timeout control).
