### ISSUE TITLE
Battery stuck at 83%

### ISSUE THREAD

**Issue by Zzzeeroo** [seerge/g-helper#496]
Hello I had the battery precentage set to 80% and it was stuck at 83 and I recently just changed it to 50% but no difference on the battery indicator. I do not have armoury create installed, I have myasus but I ran the debloat so I cant change anything in there anymore. OS is Windows 11, model is ROG Strix G15 with ryzen 5800h and rtx 3060. 

2023-06-01 01:30:38: BatteryLimit = 50 : OK

It says this but nothing is changing anyone have any idea what to do?

**Comment by seerge** [comment]
@Zzzeeroo hello. If you battery is 83% now and you set target to 50% it won't automatically discharge to that unless you unplug (i assume it's pretty obvious). Try to discharge laptop and charge again.

Since from the log you see that limit is being set, rest - is on your hardware / battery controller :)

**Comment by Zzzeeroo** [comment]
Oh I did not know u needed to unplug it to get the right charging, my macbook just stops using ac power until its at the right percentage but now I know and it works fine
