### ISSUE TITLE
Add Aggressive at Guaranteed and Efficient Aggressive at Guaranteed Boost Options

### ISSUE THREAD

**Issue by rockethot** [seerge/g-helper#613]
**Is your feature request related to a problem? Please describe.**
The app does not have the option to set CPU boost to either Aggressive at Guaranteed or Efficient Aggressive at Guaranteed Boost.

**Describe the solution you'd like**
The ability to select Aggressive at Guaranteed and Efficient Aggressive at Guaranteed from the CPU Boost drop down menu in the app.

**Describe alternatives you've considered**
The two CPU boost options mentioned above are selectable from power options in control panel. However since G-Helper does not have these as options it changes back to one of the boost options that G-Helper does show in the drop-down menu under CPU Boost.

**Comment by seerge** [comment]
@rockethot i can add it, but what is practical purpose of that? :)

**Comment by rockethot** [comment]
@seerge On my 2022 model using Aggressive at Guaranteed leads to lower CPU temperatures without lowering performance when compared to the other boost modes

According to Microsoft "Windows calculates the desired extra performance above the guaranteed performance level and asks the processor to deliver that specific performance level" when in this mode.

I don't really use Efficient Aggressive at Guaranteed so don't have any practical uses for it. Just figured I'd include it since it's the only other boost mode not included in the drop-down menu.

**Comment by seerge** [comment]
@rockethot oke, not sure if someone else will use this, but i have added 2 more entries to the dropdown :) 
[GHelper.zip](https://github.com/seerge/g-helper/files/11725849/GHelper.zip)

**Comment by rockethot** [comment]
@seerge Thank you! Really appreciate it.

**Comment by seerge** [comment]
Ok, closing this as completed, and will try to include it in next release

**Comment by attakuart** [comment]
Hi, do I have to select "Apply power limits" in order to use different CPU Boost modes from the drop down box? It's kinda confusing now. Before it was a separate option but now it's under "power limits" section. And now it seems like it will apply whatever that CPU SLow (SPL + sPPT) thing means with default 125W value and I don't have any idea what does it do, and honestly don't even wanna get in to it :) .  But I really need CPU Boost options. Thanks.

**Comment by seerge** [comment]
@attakuart you don't have to "apply" boost, as it's just a shortcut dropdown to a same one in your power plan. But I may move it (or add a separate section for such things later) that doesn't need to be "applied"

**Comment by iatacs19** [comment]
Just wanted to add some information about the Processor performance boost modes:

https://learn.microsoft.com/en-us/dotnet/api/microsoft.windows.eventtracing.power.processorperformanceboostmode?view=trace-processor-dotnet-1.0

https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/hardware/power/power-performance-tuning#processor-performance-boost-mode

**Comment by Solarriors** [comment]
overload of options. What is the best mode mode for silent, economical light work and reaching optimal performance for heavy work loads (gaming, rendering, other computing) is not clear.

**Comment by seerge** [comment]
@Solarriors all options except Disabled seem to do same thing , enabling boost (check links in this thread for more info)

**Comment by Solarriors** [comment]
I did, I'm doing some research since a few days but still not certain to find the best option. I also want to thank you for writing this software and not making it bloated and as lightweight as possible. Ideally with a little fiddling out of the box as necessary. 

As said I'm just concerned to not have noise and useless power usage while using my 2023 X16 casually but want to be able to have a high (naturally not always identically sustained but still long term) performance. And I do not care in the slighest about RGB lights, switching color/display profiles on the fly and drawing my own fan curves lol.
What I mean is I don't have issues with performance spikes above "100%" and back, it should just not start to throttle much under "guaranteed" in long terms because of heating.

Thank you again for your time, efforts and dedication. And I hope you have a merry time with your relatives and loved ones for this Year's End Celebrations.
