### ISSUE TITLE
[Bug] No battery limit applied before user logged in

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#62]
Hi, when the laptop is just turned on and loaded, but no user password entered yet, the battery is charging ignoring the limit set (60%).
Maybe, the startup way should be changed to run earlier or regardless of the user authenticated?
P.S. I have a dimly feeling that it worked OK previously, but can't remember which version it was.

G15 2021, Win 11, GH 0.22

**Comment by ke1ne** [comment]
I have myasus with the same limit set (60%). But its services were disabled, so no interference.

**Comment by seerge** [comment]
I see. Well anyway - running app before/or after login shouldn't matter. As again if nothing else is messing a setting, you set it once and forget (but who knows asus bios quirks :D) You can manually edit a startup task in Task Scheduler and set it to run on computer start instead of login tho and see if it works for you. That scheduling setting requires admin permission i think, so I won't be adding it to the app :)
