### ISSUE TITLE
[Bug] The Battery charge limit doesn't work if the user is not logged in yet

### ISSUE THREAD

**Issue by ke1ne** [seerge/g-helper#658]
**Describe the bug**
The Battery charge limit doesn't apply when the laptop is just turned on but the user is not logged in yet.

**Clear scenario to Reproduce**
1. Turn the laptop on.
2. The Log In dialog appears.
3. Do nothing.
4. The laptop battery is charging over the limit set (60%).

**Expected behavior**
Enable the battery charge limit after Windows loaded before the user logged in

**Desktop (please complete the following information):**
 - OS: Windows 11
 - G-Helper v0.89
 - Laptop model GA503QR

**Asus software**
Software uninstalled and services disabled via G-Helper debloat.

**Comment by seerge** [comment]
Then probably your hardware doesn't remember settings after reboot. As soon as app is started - it will set a new limit anyway, before that it obviously can't set anything as it's not running :)

**Comment by seerge** [comment]
@ke1ne  P.S. On a side note - do you have fast boost enabled in bios ? it could be that if not, it will reset all hardware settings each reboot.  Try to swtich it off/on

**Comment by ke1ne** [comment]
> Then probably your hardware doesn't remember settings after reboot. As soon as app is started - it will set a new limit anyway, before that it obviously can't set anything as it's not running :)
> 
> What do you expect me to do here? :)

This didn't happen previously, so that's why I become curious. I've changed nothing in BIOS or system globally.

P.S. Also, now G-Helper sometimes don't start automatically, and this happens kind of randomly, with no errors in logs.

**Comment by seerge** [comment]
@ke1ne well, as for charge limit : in general it should be remembered by hardware (i.e. when laptop is completely off - it shouldn't charge above limit as well). But I can imagine that sometimes hardware glitches / resets it.

G-Helper can't start before login due to way it's done (it's a windows app, that stays in tray) and not a windows service :) So it's not much can be done here unless I will split g-helper into 2 pieces ( service + control app) but that's sort of against of a logic of being lightweight and easy to use :)

So for now it will stay as is.

**Comment by nirexnova111** [comment]
@seerge  Hey my asus rog zephyrus battery says charging but its stuck at 19% , if i remove the power cord laptop turns off any idea whats the issue
