### ISSUE TITLE
When the laptop boots up, the laptop screen brightness resets to max.

### ISSUE THREAD

**Issue by nussland** [seerge/g-helper#687]
## NOTE
Bug reports without clear information or scenario to reproduce and logs from ``%AppData%\GHelper`` will be closed without answer. 
Please respect time of the developer. Thanks.

**Describe the bug**

**Clear scenario to Reproduce**
1. After booting up, adjust the screen to moderate brightness after the laptop boots up.
2. Cold shut down the laptop.
3. Turn on the laptop.
4. The screen is set to maximum brightness.

**Expected behavior**
When the laptop boots up, the laptop screen brightness resets to max.

**App Logs**
[log.txt](https://github.com/seerge/g-helper/files/11877476/log.txt)

**Screenshots or screencasts**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Asus ROG Flow X13 GV301QC with xgm 3070

**Asus software**
- MyASUS installed
- ASUS Hotplug Controller

**Additional context**
This phenomenon was not a problem in 0.82. 
It is not possible to specify the time, but it occurred recently from 0.86 or 0.89.

**Comment by seerge** [comment]
@nussland hello, this is not due to the app, but due to recent windows update that started changing brightness every time a "power mode" is set.

Try to change power modes in settings by hand and see if brightness changes ?
![Screenshot 2023-06-18 001657](https://github.com/seerge/g-helper/assets/5920850/5dc91518-8515-48df-bc13-98c0961b1ce0)

If so, most probably 0.82 (or pretty much any version) of the app would behave same (again due to the new changes in windows)

You can disable power modes setting by unchecking Extra -> Auto adjust power modes . Does it help ?

**Comment by nussland** [comment]
@seerge I think your reply is correct. This seems to be a problem after a Windows update.
thanks, that was helpful!!

**Comment by seerge** [comment]
@nussland just FYI - i have installed cumulative update for June for windows, and it seem to fix brightness issue
