### ISSUE TITLE
Rog Ally Some Improvements 

### ISSUE THREAD

**Issue by Nidre** [seerge/g-helper#769]
Hello, I am the owner of Rog Ally and I have discovered some possible improvements to the program.

1. From the general when setting fan speed you could do like this: 
![1](https://github.com/seerge/g-helper/assets/24737075/7170fe2f-a147-4546-aada-5f3b78d9040b)

It would be cool if there were "barriers" for example 10% for each slider.

Now about Rog Ally:
2. By default we have 1920x1080 and a scale of 150%, so the Extra window looks like this:
![2](https://github.com/seerge/g-helper/assets/24737075/b71cc1fc-132c-4410-a2d5-9cbdc058d83c)

3. There is no dGPU on Ally and the "Eco" and "Optimized" mods should ideally not be displayed and ignored for XG Mobile connectivity.

4, I would also like to see a function to disable tracking  of "Mode" and "Fans" to give control of this to another app. For example, it's almost mandatory for Ally to use Handheld Companion, which better adjusts the TDP for handheld computers.

5. The maximum CPU limit looks like this:
![3](https://github.com/seerge/g-helper/assets/24737075/f66064b5-f34e-48ba-98ab-30a6fcf2a28c)

6. There are 2 fans (left and right) on the Ally, both cooling the CPU, the program also shows CPU/GPU fans.

Also can I ask what you use to connect/disconnect XG Mobile?
> Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x090019; Control_status=1}

Or something a bit trickier?

And thank you for your program)

**Comment by seerge** [comment]
@Nidre hello

1. Do you mean locking dots to 10% , 20%, 30% only instead of smooth dragging? I'm not sure if it's a good idea, even AC allows flexible settings :) (but i can imagine dots can be small enough for a small touch screen)
2. In latest build I have made Extras screen a bit more compact [GHelper.zip](https://github.com/seerge/g-helper/files/12016580/GHelper.zip) so it should fit into 1080P
3. I know about absence of dGPU but by some reason Eco flag exists in bios (and even does something, i just didn't figure out what ... mb it adjusts RAM dedicated to GPU?)
4. In this case I would advice to set TDP to max in g-helper (as they are anyway linked to one of predefined modes, and device is always in one of those modes, as they are baked in bios) and then apply custom limits via other apps.
5. In AC maximum values are a bit lower than they can be in reality, when I cranked sliders in g-helper on my Ally it was sustaining 43-45W all the time (just in case in g-helper sPPT and SPL are merged into 1 slider cause i don't see sense to separate 2 min "boost" from sustained limit)
6. I think even AC calls second fan "GPU fan", right ?
7. Yes, that command is correct one (1 to connect, 0 to disconnect in Control_status), but g-helper also does that

````
Invoke-CimMethod (Get-CimInstance -Namespace root/wmi -ClassName AsusAtkWmi_WMNB) -MethodName DEVS -Arguments @{Device_ID=0x090019; Control_status=1}
```

**Comment by Nidre** [comment]
1. In AC sliders just have barriers, the point is that it is impossible to overlap them, because they can be separated only by the reset button. There are probably no scenarios where one-degree control is required.
2. Its latest build:
![5](https://github.com/seerge/g-helper/assets/24737075/32c8b3d7-903e-438e-aa7c-2438c4f18224)

3. We have a separate VRAM adjustment. I would assume "asus team" just left it "for later", and now it's really useless.
4. I wanna use handless companion for cpu and msi afterburner for xg mobile, but on gpu tab there's no apply checkbox, like a cpu. I think it's not a bad idea to add a checkbox to the GPU tab.
6. Fan 1 and Fan 2. (Fan 1 i think near the SD reader, its left and fan 2 is right)

In addition you have the files bloat.bat and debloat.bat There's no Ally service there: **ArmouryCrateSEService**
![image](https://github.com/seerge/g-helper/assets/24737075/f53f9177-8777-4924-b73c-81333a8a4f81)
