### ISSUE TITLE
Causing sleep mode to shut down?

### ISSUE THREAD

**Issue by musm** [seerge/g-helper#788]
I'm not sure if this is from G-helper or what, but  ever since I switched over to G-helper my computer shuts down when going into sleep mode.  Basically logging me out of my account and requiring me to restart everything. 

My power plan is selected to "ASUS recommended"

**Expected behavior**
Computer successfully resumes from sleep without shutdown.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: 2021 ROG 15

**Asus software**
- Armoury crate uninstalled (used script in repo to disable services)
- MyASUS installed

**Comment by seerge** [comment]
@musm hello

Laptop sleep is controlled by your windows and power plan, not by g-helper :) 

When you have uninstalled AC it has deleted all it's power plans, and left only Balanced / asus (which is ok) - so that was a change. Check settings in power plan (mb reset it to defaults) or select Balanced, and check system settings :)

**Comment by musm** [comment]
Ok I didn't think so but perhaps disabling AC causing some unintended side effects. To be clear, do you recommend to stick to ASUS recommended or Windows Balanced. I've had issues with both after uninstalling AC for some odd reason.

**Comment by seerge** [comment]
@musm Balanced is the only plan that comes with Windows by default, so i would recommend to stick with that :)
