### ISSUE TITLE
[Feature Request] Set different screen brightness for Battery and Plugged in modes

### ISSUE THREAD

**Issue by stuli1989** [seerge/g-helper#868]
It would be extremely beneficial to be able to have a toggle which lets the user set different brightness levels when on battery and a different one for when they are plugged in. When on battery they are out and about and probably care a lot about battery life, a dimmer display helps with that. When plugged in they want everything turned up including brightness.

**Comment by seerge** [comment]
@stuli1989 hello.

Currently app would remember mode per battery / plugged state. And with each mode it would also adjust windows ["power mode"](https://images.idgesg.net/images/article/2021/07/windows-11-power-mode-100895295-large.jpg?auto=webp&quality=85,70)

In recent windows updates, windows started saving it's brightness settings per power mode as well. So it technically does that already, but since it's windows it does it in own bugged way :)) 

At the same time - this is the reason I don't want to force app to override those settings, and it will only cause conflicts with system that already adjusts brightness. So I don't plan to add it atm.
