### ISSUE TITLE
Add cpu max frequency limit

### ISSUE THREAD

**Issue by middaysan** [seerge/g-helper#912]
Hello!
I have the 7945hx in my laptop  and it has a high cpu frequency and power consumption even I'm just surfing the internet. 

I would like to be abble to lower the cpu frequency, for example from 54.5x multiplier to 44x. It helps to me with undervolting, because most errors occur at high frequency and has low  power consumption in simple tasks.

I tried to use "Max cpu frequency" in Windows 11 Power Plan. I use this trick:
`powercfg -attributes SUB_PROCESSOR 75b0ae3f-bce0-45a7-8c89-c9611c25e100 +ATTRIB_HIDE`
And it worked as I  expected but it didn't work in games.  Cpu has been ignoring this setting since last windows update and I don't know how I to get it back. I'm not sure if last update broke this setting =(

It would be great if you could add this feature to your app. Thanks!

**Comment by seerge** [comment]
@middaysan how do you expect me to add it, if power plan configuration doesn't have effect? :) Maximum that app can do - is to adjust same setting in power plan.

Try to disable turbo boost completely, that will limit your clocks :)

**Comment by IceStormNG** [comment]
The reason is: this only works if the CPU does not use autonomous mode (hardware P-States) which is the default for any halfway recent CPU. In this state, the CPU decides its frequency on its own. You can however edit the processor energy efficiency with powercfg using

`powercfg /setacvalueindex scheme_current SUB_PROCESSOR PERFEPP 33` This sets the effiency to 33. 0 is "full performance". 100 is "best energy saving".
This will impact  the scaling aggressiveness and also the max frequency. At least on Intel CPUs. You can test how it affects AMD CPUs.
Btw: This only works if your CPU is set to "balanced" in the Windows 11 energy overlay I do not mean the power plan balanced, but the power overlay in the new settings app in the battery options. If it is set to "Best performance" it will always run the CPU full tilt for just moving the cursor. This is what ASUS tends to set by default on most machines.

**Comment by middaysan** [comment]
@seerge I assumed this could be done through some internal functionality of Asus, like how you set the amount of power consumed by the CPU. And I merely gave an example of how I did this thanks to the capabilities of Windows.

@IceStormNG  Thanks, I'll try it.

Ok, If this can't be implemented with the existing methods, then I think we can close this issue.

Thanks a lot.

**Comment by seerge** [comment]
@middaysan all endpoints that Asus exposes are already in the app :) The rest is power-plan settings in windows (at best).

You may also try https://github.com/JamesCJ60/AMD-APU-Tuning-Utility/releases to see if allows refined control over CPU

Closing for now
